### ISSUE TITLE
Can't start rainloop

### ISSUE THREAD

**Issue by dkm** [RainLoop/rainloop-webmail#1027]
I've cloned rainloop this morning and configured my nginx server for using rainloop.

When I try to access the home page (or the /?admin page), I always get:

```
Loading
An Error occurred,
please refresh the page and try again. 
```

The logs are very short : 
```
"GET / HTTP/1.1" 200 1835 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
"GET /rainloop/v/0.0.0/static/css/app.min.css?vo HTTP/1.1" 200 1835 "http://rl.kataplop.net/" "Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
"GET /rainloop/v/0.0.0/static/js/min/boot.js?vo HTTP/1.1" 200 1835 "http://rl.kataplop.net/" "Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0"
```

I've read that this issue might occur when using a php accelerator, which is my case : I'm using php5-apcu, but I'm not willing to remove it... Is there any way to work around this problem (if the acpu is involved, of course).

**Comment by ervee** [comment]
It is accessing v/0.0.0/ should it not access another version? Did you clone all files?

**Comment by RainLoop** [comment]
Did you build static files?

```
npm install
npm install -s gulp
gulp
```

**Comment by dkm** [comment]
That's probably related, but not enough. I did not see these instructions in the doc I've been reading. But even after running the above commands, I still get the same error and logs.

I thing I may have overlooked the doc somewhere, but can't find the above commands anywhere. Maybe you can point me to the correct doc ? Thanks and sorry for opening this ticket...

Here's the log for `gulp`.:
```
 ./node_modules.bin/gulp                                                                                                                                          
[15:17:31] Using gulpfile /srv/BLA/rainloop-webmail/gulpfile.js
[15:17:31] Starting 'js:libs'...
[15:17:31] Starting 'js:openpgp'...
[15:17:31] Starting 'js:openpgpworker'...
[15:17:31] Starting 'js:webpack'...
[15:17:31] Starting 'js:lint'...

/srv/BLA/rainloop-webmail/node_modules/google-closure-compiler/lib/gulp/index.js:106
          let outputFiles;
          ^^^
[15:17:31] 'js:lint' errored after 18 ms
[15:17:31] SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/srv/BLA/rainloop-webmail/node_modules/google-closure-compiler/index.js:26:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[15:17:32] Finished 'js:openpgpworker' after 424 ms
[15:17:32] Finished 'js:openpgp' after 1.33 s
[15:17:44] Finished 'js:webpack' after 12 s
[15:17:44] Finished 'js:libs' after 13 s
```

**Comment by RainLoop** [comment]
hmm, try to update your Node.

**Comment by dkm** [comment]
That's what I was avoiding by using a php project... Updating nodejs on my debian (stable) server is not something I'm comfortable with... :/ Is 0.10.29 too old ?

**Comment by RainLoop** [comment]
Well, it is a version for developers. It requires some these things.
But, you always may install release version from site.

http://www.rainloop.net/

**Comment by dkm** [comment]
Ah, ok... If I had used .zip, I wouldn't need node ?
I've tried to simply extract node 4.4 and use it to generate the files, and everything works great.
