### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by MrKeiKun** [RainLoop/rainloop-webmail#1049]
```
/var/www/rainloop-webmail/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/var/www/rainloop-webmail/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/var/www/rainloop-webmail/node_modules/postcss/lib/lazy-result.js:79:21)
    at DestroyableTransform._transform (/var/www/rainloop-webmail/node_modules/gulp-autoprefixer/index.js:24:6)
    at DestroyableTransform.Transform._read (/var/www/rainloop-webmail/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/var/www/rainloop-webmail/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/var/www/rainloop-webmail/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/var/www/rainloop-webmail/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/var/www/rainloop-webmail/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/var/www/rainloop-webmail/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at DestroyableTransform.emit (events.js:95:17)
```

using 4f2a8b5b9b694f88d427aa8d7f0739a6e7fd7498

**Comment by RainLoop** [comment]
Try to update your node.js version

**Comment by MrKeiKun** [comment]
@RainLoop 

what version is best? i went with nodejs stable
```
(node:21104) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[23:31:57] Using gulpfile /var/www/rainloop-webmail/gulpfile.js
[23:31:57] Starting 'js:libs'...
[23:31:57] Starting 'js:openpgp'...
[23:31:57] Starting 'js:openpgpworker'...
[23:31:57] Starting 'js:webpack'...
[23:31:57] Starting 'js:lint'...
[23:31:58] Starting 'js:eslint'...
[23:31:58] Starting 'less:main'...
(node:21104) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[23:31:58] Starting 'ckeditor:clear'...
[23:31:58] Starting 'fontastic-fonts:clear'...
[23:31:58] Starting 'fontastic-svg:clear'...
[23:31:58] Finished 'fontastic-fonts:clear' after 41 ms
[23:31:58] Starting 'fontastic-fonts:copy'...
[23:31:58] Finished 'fontastic-svg:clear' after 43 ms
[23:31:58] Starting 'fontastic-svg:copy'...
[23:31:58] Finished 'fontastic-svg:copy' after 9.81 ms
[23:31:58] Finished 'ckeditor:clear' after 93 ms
[23:31:58] Starting 'ckeditor:copy'...
[23:31:59] Finished 'js:openpgpworker' after 1.78 s
[23:31:59] Finished 'js:openpgp' after 2.27 s
[23:31:59] Starting 'js:pgp'...
[23:31:59] Finished 'js:pgp' after 7.75 μs
[23:32:00] Finished 'less:main' after 2.5 s
[23:32:00] Starting 'css:main-begin'...
[23:32:02] Finished 'fontastic-fonts:copy' after 3.78 s
[23:32:02] Starting 'fontastic'...
[23:32:02] Finished 'fontastic' after 6.6 μs
[23:32:10] Finished 'css:main-begin' after 9.66 s
[23:32:10] Starting 'css:clear-less'...
[23:32:10] Finished 'css:clear-less' after 112 ms
[23:32:10] Starting 'css:main'...
[23:32:10] Finished 'css:main' after 4.87 μs
[23:32:10] Starting 'css:main:min'...
[23:32:12] Finished 'js:webpack' after 15 s
[23:32:12] Starting 'js:app'...
[23:32:12] Starting 'js:admin'...
[23:32:12] Starting 'js:chunks'...
[23:32:12] Finished 'js:chunks' after 23 ms
[23:32:12] Finished 'css:main:min' after 2.23 s
[23:32:12] Finished 'js:admin' after 620 ms
[23:32:12] Finished 'js:app' after 622 ms
[23:32:13] Finished 'js:libs' after 16 s
[23:32:14] Finished 'js:eslint' after 16 s
[23:32:16] Finished 'js:lint' after 19 s
[23:32:16] Starting 'js:validate'...
[23:32:16] Finished 'js:validate' after 5.26 μs
[23:32:16] Starting 'js:min'...
[23:32:24] Finished 'js:min' after 7.19 s
[23:32:24] Finished 'ckeditor:copy' after 26 s
[23:32:24] Starting 'ckeditor:copy-plugins'...
[23:32:24] Finished 'ckeditor:copy-plugins' after 12 ms
[23:32:24] Starting 'ckeditor'...
[23:32:24] gulp-stripbom: build-config.js ✔
[23:32:24] gulp-stripbom: ckeditor.js ✔
[23:32:24] gulp-stripbom: config.js ✔
[23:32:24] gulp-stripbom: styles.js ✔
[23:32:24] Finished 'ckeditor' after 55 ms
[23:32:24] Starting 'default'...
[23:32:24] Finished 'default' after 4.62 μs
```

**Comment by RainLoop** [comment]
Your log looks great. I do not see any error (except graceful-fs, but it does not matter)

**Comment by MrKeiKun** [comment]
@RainLoop 

btw

found out this
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
```
on npm install

if fsevents important? im using centos 7 and npm 3.9.3
