### ISSUE TITLE
IMAP authentication errors with Dovecot after upgrade from rainloop 1.9.3.363 to 1.10.1.127

### ISSUE THREAD

**Issue by sllawap** [RainLoop/rainloop-webmail#1063]
[18:35:10.313][b038396b] INFO[DATA]: [DATE:10.06.16][RL:1.10.1.127][PHP:5.6.19-0+deb8u1][IP:172.17.0.4][PID:50][Apache/2.4.10 (Debian)][apache2handler]
[18:35:10.313][b038396b] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[18:35:10.313][b038396b] REQUEST[NOTE]: [POST] https://mail.**DOMAIN**/?/Ajax/&q[]=/0/
[18:35:10.313][b038396b] AJAX[NOTE]: Action: DoLogin
[18:35:10.313][b038396b] POST[DATA]: {"Email":"**USER**","Login":"","Password":"****_**","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"1","Action":"Login","XToken":"2eeb4b330eaed383c47ad65aebef4e69"}
[18:35:10.313][b038396b] LOGIN[DATA]: The email address "__USER__" is not complete
[18:35:10.313][b038396b] LOGIN[DATA]: Default domain "__DOMAIN__" was used. (__USER_\* > **USER**@**DOMAIN**)
[18:35:10.314][b038396b] IMAP[NOTE]: Start connection to "tcp://imap.**DOMAIN**:143"
[18:35:10.316][b038396b] IMAP[NOTE]: Connected (success)
[18:35:10.328][b038396b] IMAP[DATA]: < \* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS LOGINDISABLED AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Dovecot ready.\r\n
[18:35:10.328][b038396b] IMAP[DATA]: > TAG1 STARTTLS\r\n
[18:35:10.328][b038396b] IMAP[DATA]: < TAG1 OK Begin TLS negotiation now.\r\n
[18:35:10.345][b038396b] IMAP[DATA]: > TAG2 CAPABILITY\r\n
[18:35:10.345][b038396b] IMAP[DATA]: < \* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5\r\n
[18:35:10.345][b038396b] IMAP[DATA]: < TAG2 OK Pre-login capabilities listed, post-login capabilities have more.\r\n
[18:35:10.345][b038396b] IMAP[DATA]: > TAG3 AUTHENTICATE CRAM-MD5\r\n
[18:35:10.345][b038396b] IMAP[DATA]: < + **MD5SUM**=\r\n
[18:35:10.346][b038396b] INFO[DATA]: ticket: <3998735336083930.1465583710@imap.**DOMAIN**>
[18:35:10.346][b038396b] IMAP[SECURE]: > ****_**\r\n
[18:35:12.348][b038396b] IMAP[DATA]: < TAG3 NO [AUTHENTICATIONFAILED] Authentication failed.\r\n
[18:35:12.348][b038396b] IMAP[WARNING]: exception 'MailSo\Imap\Exceptions\NegativeResponseException' with message 'MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1874)' in /var/www/__OMITTED_*/htdocs/rainloop/v/1.10.1.127/app/libraries/MailSo/Imap/ImapClient.php:1874
Stack trace:
#0 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/MailSo/Imap/ImapClient.php(1951): MailSo\Imap\ImapClient->validateResponse(Array)
#1 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/MailSo/Imap/ImapClient.php(247): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/MailSo/Mail/MailClient.php(92): MailSo\Imap\ImapClient->Login('**USER**', '*******', '', true, true)
#3 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/Model/Account.php(451): MailSo\Mail\MailClient->Login('**USER**', '*******', '', true, true)
#4 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(2086): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#5 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(2327): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#6 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(2413): RainLoop\Actions->LoginProcess('**USER**@**DOMAIN**...', '****_**', '__HASH_*...', '', false)
#7 [internal function]: RainLoop\Actions->DoLogin()
#8 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#9 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#10 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#11 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#12 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#13 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/app/handle.php(94): RainLoop\Service::Handle()
#14 /var/www/**OMITTED**/htdocs/rainloop/v/1.10.1.127/include.php(225): include('/var/www/**OMITTED**...')
#15 /var/www/**OMITTED**/htdocs/index.php(14): include('/var/www/**OMITTED**...')
#16 {main}

**Comment by sllawap** [comment]
Mutt and Thunderbird continue to function over IMAP without a hitch.

Is there any way for me to fetch an old version of rainloop community edition? I mistakenly deleted the copy I had and would like to use it for a behavior comparison (and selfishly, to unbreak my system).

**Comment by RainLoop** [comment]
You may disable  CRAM-MD5 authentication in the RainLoop.

`./data/.../application.ini`

```ini
[labs]
imap_use_auth_cram_md5 = Off
smtp_use_auth_cram_md5 = Off
```

Could you give me a test email account? I will try to fix CRAM-MD5 authentication.

**Comment by sllawap** [comment]
@RainLoop Indeed, your suggestion works. I anticipated an issue with the hashing algorithm but wanted to compare the hashes being produced by each Rainloop version. I may be able to set you up with a test account this evening. In the interim, if it helps you to reproduce, I'm running dovecot-imapd 1:2.2.13-12~deb8u1 from Debian jessie.

**Comment by RainLoop** [comment]
Old RainLoop doesn't support CRAM-MD5 authentication method and it uses AUTH=LOGIN to work.

**Comment by cortexx** [comment]
Ok, thanks for this fix, after updating my application.ini, I can now send mails without authentication error.

**Comment by cusco** [comment]
Thank you, my non related issue was auth plain for SMTP. Disabled and it works now :)
