### ISSUE TITLE
Server unreachable

### ISSUE THREAD

**Issue by benjbubu** [RainLoop/rainloop-webmail#1085]
I got a dedicated server on Debian 8 with my own Dovecot+Postfix server. I just install rainloop on the server and i got a weird issue.

Sometimes i can connect directly to a mailbox, sometimes i have the message "Server unreachable".

After i login successfully, if i switch between the folders (Trash/Sent etc), sometimes it works, sometimes i got a server unreachable message instead of the mail list. 

I enabled login in rainloop and i got the message stream_socket_client(): unable to connect to ssl://domain.com:993.

Any idea ? Thank you for your help

```
[11:58:56.259][8d2aeaa9] IMAP[NOTE]: Start connection to "ssl://domain.com.com:993"
[11:59:06.265][8d2aeaa9] IMAP[NOTE]: Connected (unsuccess)
[11:59:06.267][8d2aeaa9] IMAP[NOTICE]: Socket: [2] stream_socket_client(): unable to connect to ssl:/domain.com:993 (Connection timed out)
[11:59:06.268][8d2aeaa9] IMAP[NOTICE]: exception 'MailSo\Net\Exceptions\SocketCanNotConnectToHostException' with message 'Can't connect to host "ssl://domain.com:993"' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Net/NetClient.php:292
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Imap/ImapClient.php(153): MailSo\Net\NetClient->Connect('domain.com', 993, 1, false, true)
#1 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Mail/MailClient.php(72): MailSo\Imap\ImapClient->Connect('domain.comm', 993, 1, false)
#2 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Model/Account.php(424): MailSo\Mail\MailClient->Connect('domain.com', 993, 1, false, true)
#3 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(9008): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#4 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(5843): RainLoop\Actions->initMailClientConnection()
#5 [internal function]: RainLoop\Actions->DoMessageList()
#6 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#7 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#8 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#9 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#10 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#11 /var/www/rainloop/rainloop/v/1.10.1.127/app/handle.php(94): RainLoop\Service::Handle()
#12 /var/www/rainloop/rainloop/v/1.10.1.127/include.php(225): include('/var/www/rainlo...')
#13 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#14 {main}
[11:59:06.272][8d2aeaa9] INFO[ERROR]: exception 'MailSo\Net\Exceptions\SocketCanNotConnectToHostException' with message 'Can't connect to host "ssl://domain.com:993"' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Net/NetClient.php:292
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Imap/ImapClient.php(153): MailSo\Net\NetClient->Connect('domain.com', 993, 1, false, true)
#1 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Mail/MailClient.php(72): MailSo\Imap\ImapClient->Connect('domain.com', 993, 1, false)
#2 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Model/Account.php(424): MailSo\Mail\MailClient->Connect('domain.com', 993, 1, false, true)
#3 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(9008): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#4 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(5843): RainLoop\Actions->initMailClientConnection()
#5 [internal function]: RainLoop\Actions->DoMessageList()
#6 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#7 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#8 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#9 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#10 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#11 /var/www/rainloop/rainloop/v/1.10.1.127/app/handle.php(94): RainLoop\Service::Handle()
#12 /var/www/rainloop/rainloop/v/1.10.1.127/include.php(225): include('/var/www/rainlo...')
#13 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#14 {main}

Next exception 'RainLoop\Exceptions\ClientException' with message 'ConnectionError[104]' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php:9012
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(5843): RainLoop\Actions->initMailClientConnection()
#1 [internal function]: RainLoop\Actions->DoMessageList()
#2 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#3 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#4 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#5 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#6 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#7 /var/www/rainloop/rainloop/v/1.10.1.127/app/handle.php(94): RainLoop\Service::Handle()
#8 /var/www/rainloop/rainloop/v/1.10.1.127/include.php(225): include('/var/www/rainlo...')
#9 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#10 {main}
[11:59:06.272][8d2aeaa9] AJAX[DATA]: {"Action":"MessageList","Result":false,"ErrorCode":104,"ErrorMessage":"","ErrorMessageAdditional":"","Time":10052}
[11:59:06.300][8d2aeaa9] INFO[MEMORY]: Memory peak usage: 1.25MB
[11:59:06.300][8d2aeaa9] INFO[TIME]: Time delta: 10.080131053925

```

**Comment by zessx** [comment]
I'm facing this problem at least 1 or 2 times per week.  
Same config: Debian 8 / Postfix

**Comment by ervee** [comment]
I think this is more a network or server issue. So I'd start monitoring that. When RainLoop logs "unable to connect" it probably is just that.

**Comment by zessx** [comment]
I'm not that sure. From the same network, my Android app has always been able to reach the server.  
When this error occurs (in Rainloop), I won't be able to be connected for a bunch a minutes, but the app will still works during this time.
