### ISSUE TITLE
Rainloop 1.10.1.127 not working with PHP 7.0

### ISSUE THREAD

**Issue by takenek** [RainLoop/rainloop-webmail#1086]
Hello
After upgrade my PHP from 5.6 to 7.0 Rainloop stop working in logs got it:

[Mon Jun 27 12:49:20.723811 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 577, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723824 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 578, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723829 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_FAILONERROR - assumed 'CURLOPT_FAILONERROR' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 579, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723832 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 580, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723836 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 581, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723839 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 582, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723842 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_MAXREDIRS - assumed 'CURLOPT_MAXREDIRS' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 583, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723845 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_FILE - assumed 'CURLOPT_FILE' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 584, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723848 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 585, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723852 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 590, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723902 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 460, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723921 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 460, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723924 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 462, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723927 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Notice:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 462, referer: https://poczta.localhost.pl/
[Mon Jun 27 12:49:20.723968 2016] [:error] [pid 12676] [client 9X.4X.1X6.1X:45144] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php:618\nStack trace:\n#0 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php(661): MailSo\\Base\\Http->SaveUrlToFile('http://api.rain...', Resource id #14, 'RainLoop/1.10.1...', '', 0, Object(MailSo\\Log\\Logger), 5, '', '', Array, false)\n#1 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Prem/Provider.php(197): MailSo\\Base\\Http->GetUrlAsString('http://api.rain...', 'RainLoop/1.10.1...', '', 0, Object(MailSo\\Log\\Logger), 5, '', '', Array, false)\n#2 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Prem/Provider.php(25): RainLoop\\Prem\\Provider->Fetcher(false, true)\n#3 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Prem/Provider.php(67): RainLoop\\Prem\\Provider->Type()\n#4 /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/RainLoop/Actions.php(1563): RainLoop\\Prem\\Provider->PopulateAppData(Array)\n#5 /var/www/rainloop/rainl in /var/www/rainloop/rainloop/v/1.10.1.127/app/libraries/MailSo/Base/Http.php on line 618, referer: https://poczta.localhost.pl/

Best Regards
Marek

**Comment by takenek** [comment]
Ehhh CURL module not enable - my fault.
