### ISSUE TITLE
Can't save or even send msg

### ISSUE THREAD

**Issue by jurassicpark23** [RainLoop/rainloop-webmail#1110]
Helllo,

why i cant reply or even save msg? the button changed to red... here is my log 

> [10:07:17.482][c7374c59] INFO[DATA]: [DATE:15.07.16][RL:1.10.2.143][PHP:5.6.23][IP:36.80.112.236][PID:1006556][LiteSpeed][litespeed]
[10:07:17.482][c7374c59] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:dblib,mysql,odbc,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[10:07:17.482][c7374c59] REQUEST[NOTE]: [POST] https://sbsjewellery.com/mail/?/Ajax/&q[]=/0/
[10:07:17.486][c7374c59] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'InvalidToken[101]' in /home/sbsjewel/public_html/mail/rainloop/v/1.10.2.143/app/libraries/RainLoop/ServiceActions.php:133
Stack trace:
#0 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#1 /home/sbsjewel/public_html/mail/rainloop/v/1.10.2.143/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#2 /home/sbsjewel/public_html/mail/rainloop/v/1.10.2.143/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /home/sbsjewel/public_html/mail/rainloop/v/1.10.2.143/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /home/sbsjewel/public_html/mail/rainloop/v/1.10.2.143/app/handle.php(94): RainLoop\Service::Handle()
#5 /home/sbsjewel/public_html/mail/rainloop/v/1.10.2.143/include.php(225): include('/home/sbsjewel/...')
#6 /home/sbsjewel/public_html/mail/index.php(12): include('/home/sbsjewel/...')
#7 {main}
[10:07:17.486][c7374c59] AJAX[DATA]: {"Action":"Login","Result":false,"ErrorCode":101,"ErrorMessage":"","ErrorMessageAdditional":"","Time":45}
[10:07:17.502][c7374c59] INFO[MEMORY]: Memory peak usage: 7.75MB
[10:07:17.502][c7374c59] INFO[TIME]: Time delta: 0.060961961746216

[10:08:25.201][0fb18392] INFO[DATA]: [DATE:15.07.16][RL:1.10.2.143][PHP:5.6.23][IP:36.78.52.223][PID:1007468][LiteSpeed][litespeed]
[10:08:25.201][0fb18392] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:dblib,mysql,odbc,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[10:08:25.201][0fb18392] REQUEST[NOTE]: [POST] https://sbsjewellery.com/mail/?/Ajax/&q[]=/_CH40r3V-Ad-OkrVCYXGavdrYjIaabCtU5zpVRh3RUi5hccMPjPYkUGhVuanKeTL2G14Ffn8SPo6CBK75_Dmw-VBjDAsS71n60uE5SIS3Xz6VYdx83IuX81C1quoTIDj0S-LbNLyUMDyVWi89M9HBRtVdNS9f1FjUr8v3Ksi19p33IrV61q90nvM167WlZ42GIv8toMrg8kJSTn1gW7tAi_xpXGCmSey7im1gXm4srURo62p6vpwRMrNZ3GubjHZ4cPNXI8Yvs9jmGoVbsKvBELle75mWaR6rqSVKufYFMtXK_EDN_4uS009XpUCDcf8KAZhIhHTpm6eWQ4XDpfEiTnzlNPEPG-iPRYHhNOqmvIdmDGFI1f7et3P01iBfHb5krQ_gmA../
[10:08:25.204][0fb18392] AJAX[NOTE]: Action: DoFolderInformation
[10:08:25.204][0fb18392] POST[DATA]: {"Folder":"INBOX.Drafts","FlagsUids":"","UidNext":"","Action":"FolderInformation","XToken":"5fd24110d5ba9ba562f16a3e5a333bc9"}
[10:08:25.216][0fb18392] IMAP[NOTE]: Start connection to "ssl://sbsjewellery.com:993"

[10:08:26.315][9a819129] INFO[DATA]: [DATE:15.07.16][RL:1.10.2.143][PHP:5.6.23][IP:36.78.52.223][PID:1007565][LiteSpeed][litespeed]
[10:08:26.315][9a819129] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:dblib,mysql,odbc,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[10:08:26.315][9a819129] REQUEST[NOTE]: [POST] https://sbsjewellery.com/mail/?/Ajax/&q[]=/_CH40r3V-Ad-OkrVCYXGavdrYjIaabCtU5zpVRh3RUi5hccMPjPYkUGhVuanKeTL2G14Ffn8SPo6CBK75_Dmw-VBjDAsS71n60uE5SIS3Xz6VYdx83IuX81C1quoTIDj0S-LbNLyUMDyVWi89M9HBRtVdNS9f1FjUr8v3Ksi19p33IrV61q90nvM167WlZ42GIv8toMrg8kJSTn1gW7tAi_xpXGCmSey7im1gXm4srURo62p6vpwRMrNZ3GubjHZ4cPNXI8Yvs9jmGoVbsKvBELle75mWaR6rqSVKufYFMtXK_EDN_4uS009XpUCDcf8KAZhIhHTpm6eWQ4XDpfEiTnzlNPEPG-iPRYHhNOqmvIdmDGFI1f7et3P01iBfHb5krQ_gmA../
[10:08:26.317][9a819129] AJAX[NOTE]: Action: DoFolderInformation
[10:08:26.317][9a819129] POST[DATA]: {"Folder":"INBOX.Drafts","FlagsUids":"","UidNext":"","Action":"FolderInformation","XToken":"5fd24110d5ba9ba562f16a3e5a333bc9"}
[10:08:26.324][9a819129] IMAP[NOTE]: Start connection to "ssl://sbsjewellery.com:993"
[10:08:30.307][0fb18392] IMAP[NOTE]: Connected (success)
[10:08:30.346][0fb18392] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n
[10:08:30.347][0fb18392] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[10:08:30.347][0fb18392] IMAP[DATA]: < + \r\n
[10:08:30.347][0fb18392] IMAP[SECURE]: > *******\r\n
[10:08:30.394][0fb18392] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE NAMESPACE SPECIAL-USE COMPRESS=DEFLATE QUOTA] Logged in\r\n
[10:08:30.395][0fb18392] IMAP[DATA]: > TAG2 CAPABILITY\r\n
[10:08:30.395][0fb18392] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE NAMESPACE SPECIAL-USE COMPRESS=DEFLATE QUOTA\r\n
[10:08:30.395][0fb18392] IMAP[DATA]: < TAG2 OK Capability completed.\r\n
[10:08:30.395][0fb18392] IMAP[DATA]: > TAG3 STATUS "INBOX.Drafts" (MESSAGES UNSEEN UIDNEXT HIGHESTMODSEQ)\r\n
[10:08:30.396][0fb18392] IMAP[DATA]: < * STATUS INBOX.Drafts (MESSAGES 0 UIDNEXT 796 UNSEEN 0 HIGHESTMODSEQ 2310)\r\n
[10:08:30.396][0fb18392] IMAP[DATA]: < TAG3 OK Status completed (0.000 + 0.000 secs).\r\n
[10:08:30.396][0fb18392] AJAX[DATA]: {"Action":"FolderInformation","Result":{"Folder":"INBOX.Drafts","Hash":"2802c4b3b80249352f8dd255520160f3","MessageCount":0,"MessageUnseenCount":0,"UidNext":"796","Flags":[],"HighestModSeq":"2310","NewMessages":[],"Version":"1.10.2.143"},"Time":5224}
[10:08:30.400][0fb18392] IMAP[DATA]: > TAG4 LOGOUT\r\n
[10:08:30.400][0fb18392] IMAP[DATA]: < * BYE Logging out\r\n
[10:08:30.400][0fb18392] IMAP[DATA]: < TAG4 OK Logout completed.\r\n
[10:08:30.400][0fb18392] IMAP[NOTE]: Disconnected from "ssl://sbsjewellery.com:993" (success)
[10:08:30.400][0fb18392] INFO[MEMORY]: Memory peak usage: 8.5MB
[10:08:30.400][0fb18392] INFO[TIME]: Time delta: 5.2285130023956
[10:08:31.415][9a819129] IMAP[NOTE]: Connected (success)

**Comment by gambeex** [comment]
hi  i cant move message to the trash  memory storageis full how I can recover ??
