### ISSUE TITLE
CardDAV sync reset modifications to a contact

### ISSUE THREAD

**Issue by EtienneM** [RainLoop/rainloop-webmail#1115]
Hi!

I have the last version of Rainloop and I am using [Cozy Cloud](http://cozy.io/fr/) as a CardDAV server. I noticed the following problem. When I do a modification on a contact, after a couple of minutes the modification are cancelled. If I put my Rainloop offline, I do not have this problem anymore so the problem comes from here. I activated the log and I noticed the following:

Plenty of lines like that, probably for all my contacts:
```
[18:23:45.567][216c0b9d] SQL[DATA]: SELECT * FROM rainloop_ab_contacts WHERE deleted = 0 AND id_user = :id_user AND id_contact = :id_contact LIMIT 1
[18:23:45.569][216c0b9d] SQL[DATA]: SELECT * FROM rainloop_ab_properties WHERE id_contact = 12
[18:23:45.587][216c0b9d] DAV[DATA]: GET /public/sync/addressbooks/me/all-contacts/2a578e8d52ee348e4a6adfaf1b6c1ee8.vcf
[18:23:45.771][216c0b9d] DAV[DATA]: PUT /public/sync/addressbooks/me/all-contacts/2a578e8d52ee348e4a6adfaf1b6c1ee8.vcf (343)
[18:23:45.884][216c0b9d] SQL[DATA]: SELECT * FROM rainloop_ab_contacts WHERE deleted = 0 AND id_user = :id_user AND id_contact = :id_contact LIMIT 1
[18:23:45.885][216c0b9d] SQL[DATA]: SELECT * FROM rainloop_ab_properties WHERE id_contact = 13
[18:23:45.903][216c0b9d] DAV[DATA]: GET /public/sync/addressbooks/me/all-contacts/2a578e8d52ee348e4a6adfaf1b6c25ea.vcf
[18:23:46.066][216c0b9d] DAV[DATA]: PUT /public/sync/addressbooks/me/all-contacts/2a578e8d52ee348e4a6adfaf1b6c25ea.vcf (353)
```

In the middle of these lines:
```
[18:24:05.893][216c0b9d] INFO[NOTICE]: exception 'SabreForRainLoop\DAV\Exception' with message 'Internal server error' in /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/SabreForRainLoop/DAV/Client.php:445
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(203): SabreForRainLoop\DAV\Client->request('PUT', '/public/sync/ad...', 'BEGIN:VCARD??VE...', Array)
#1 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(756): RainLoop\Providers\AddressBook\PdoAddressBook->davClientRequest(Object(SabreForRainLoop\DAV\Client), 'PUT', '/public/sync/ad...', 'BEGIN:VCARD??VE...')
#2 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/Providers/AddressBook.php(75): RainLoop\Providers\AddressBook\PdoAddressBook->Sync('XXXXX@...', 'https://XXXX...', 'XXX', 'XXXX')
#3 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/Actions.php(6717): RainLoop\Providers\AddressBook->Sync('XXXX@...', 'https://XXXXX...', 'XXXX', 'XXXX')
#4 [internal function]: RainLoop\Actions->DoContactsSync()
#5 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#6 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#7 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#8 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#9 /var/www/rainloop/rainloop/v/1.10.2.145/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#10 /var/www/rainloop/rainloop/v/1.10.2.145/app/handle.php(94): RainLoop\Service::Handle()
#11 /var/www/rainloop/rainloop/v/1.10.2.145/include.php(225): include('/var/www/rainlo...')
#12 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#13 {main}
```

And eventually:
```
[18:24:08.962][216c0b9d] AJAX[DATA]: {"Action":"ContactsSync","Result":true,"Time":34212}
[18:24:08.983][216c0b9d] INFO[MEMORY]: Memory peak usage: 3MB
[18:24:08.983][216c0b9d] INFO[TIME]: Time delta: 34.23201584816
```

This is a really annoying problem as I cannot modify any of my contact... Is it a known problem? Any idea on how to solve it? Isn't it a proble with the PUT request you do right after the GET? I would have assumed that you only access my CardDAV server in read-only mode...

**Comment by ruliane** [comment]
Same problem here, so I temporarily disabled CardDav sync in Rainloop.
A workaround to prevent new contacts from being deleted, would be to access contacts with a read-only account.
