### ISSUE TITLE
Attachments dont work

### ISSUE THREAD

**Issue by bbspike** [RainLoop/rainloop-webmail#1207]
### Server Centos 7, PHP -v 5.5.38 Apache -v 2.4.6

Rainloop don't download and send emails with attachments bigger then 238 KB. 
If i recieve a email with attachment bigger then 238 KB i can't download the file. The download keeps ungoing and always stops at around 238 KB. Sending mails with attachments bigger then 238 KB doesn't work. There is no error, just the text after several minutes. "Email could not send"

![image](https://cloud.githubusercontent.com/assets/10287934/19112897/9b3b7796-8b07-11e6-9dab-b9377e3c0aa3.png)

Here my log, it clearly give a error but i don't understand:

[18:35:42.688][7ba290ff] INFO[DATA]: [DATE:03.10.16][RL:1.10.4.183][PHP:5.5.38][IP:192.168.2.254][PID:6915][Apache][apache2handler]^M
[18:35:42.688][7ba290ff] INFO[DATA]: [Suhosin:on][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls]^M
[18:35:42.689][7ba290ff] REQUEST[NOTE]: [POST] http://*****************/?/Ajax/&q[]=/_647-6YblOWojdoxHV8WN9w8M-F2pmt5MNdWdlyu_bGaggmPmxGAn1r4m7HLcok1W7xfBYkE91uXtaHApL9dGaEx-x_iUoxweMLFRI73FvSf1wNqyu4PU6-w3ufjLiibKp3Bngkn4DL8GRqDsel7DbMWbenNtHVuLFJCAV9WZZm_SQ7pJa2bGaSa2tEQuYrcI66yAhDxRpw7WVfckTDbyGeRFZrGHESBk91ps9u5EF__eonDQlV41TQZelLZRNPYzI7IitGyx5VvmNEkCun5qSzv-g4mFSQFkrjNrsKDdxtG459z60QKIye7ZX5tAw2OEYaycWHq3D5k5DhtYW0Mi2f8uhfk/^M
[18:35:42.693][7ba290ff] AJAX[NOTE]: Action: DoSendMessage^M
[18:35:42.693][7ba290ff] POST[DATA]: {"IdentityID":"","MessageFolder":"","MessageUid":"","SentFolder":"Sent","To":"\"JOY JOY\" <****@****.nl>","Cc":"","Bcc":"","ReplyTo":"","Subject":"asdasd","TextIsHtml":"1","Text":"<div data-html-editor-font-wrapper=\"true\" style=\"font-family: arial, sans-serif; font-size: 13px;\"><signature><\/signature><\/div>","DraftInfo":"","InReplyTo":"","References":"","Dsn":"0","ReadReceiptRequest":"0","MarkAsImportant":"0","Attachments":{"upload-post-7f18cbdf9085db98bea618ed4d0bf500":["metaltexturebg.jpg","0","",""]},"Action":"SendMessage","XToken":"a9283b511bd5c9e085eae72bb3684177"}^M
[18:35:42.712][7ba290ff] IMAP[NOTE]: Start connection to "ssl://*****************:993"^M
[18:35:42.755][7ba290ff] IMAP[NOTE]: Connected (success)^M
[18:35:42.795][7ba290ff] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n^M
[18:35:42.796][7ba290ff] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n^M
[18:35:42.796][7ba290ff] IMAP[DATA]: < + \r\n^M
[18:35:42.797][7ba290ff] IMAP[SECURE]: > *******\r\n^M
[18:35:42.802][7ba290ff] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE QUOTA] Logged in\r\n^M
[18:35:42.833][7ba290ff] SMTP[NOTE]: Start connection to "tcp://*******************:587"^M
[18:35:42.851][7ba290ff] SMTP[NOTE]: Connected (success)^M
[18:35:42.868][7ba290ff] SMTP[DATA]: < 220 ***************** ESMTP\r\n^M
[18:35:42.869][7ba290ff] SMTP[DATA]: > EHLO *****************\r\n^M
[18:35:42.869][7ba290ff] SMTP[DATA]: < 250-*****************\r\n^M
[18:35:42.869][7ba290ff] SMTP[DATA]: < 250-PIPELINING\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250-SIZE 52428800\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250-ETRN\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250-STARTTLS\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250-AUTH PLAIN LOGIN\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250-AUTH=PLAIN LOGIN\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250-8BITMIME\r\n^M
[18:35:42.870][7ba290ff] SMTP[DATA]: < 250 DSN\r\n^M
[18:35:42.871][7ba290ff] SMTP[DATA]: > STARTTLS\r\n^M
[18:35:42.871][7ba290ff] SMTP[DATA]: < 220 2.0.0 Ready to start TLS\r\n^M
[18:35:42.884][7ba290ff] SMTP[DATA]: > EHLO *******************\r\n^M
[18:35:42.884][7ba290ff] SMTP[DATA]: < 250-*****************\r\n^M
[18:35:42.884][7ba290ff] SMTP[DATA]: < 250-PIPELINING\r\n^M
[18:35:42.884][7ba290ff] SMTP[DATA]: < 250-SIZE 52428800\r\n^M
[18:35:42.884][7ba290ff] SMTP[DATA]: < 250-ETRN\r\n^M
[18:35:42.885][7ba290ff] SMTP[DATA]: < 250-AUTH PLAIN LOGIN\r\n^M
[18:35:42.885][7ba290ff] SMTP[DATA]: < 250-AUTH=PLAIN LOGIN\r\n^M
[18:35:42.885][7ba290ff] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n^M
[18:35:42.885][7ba290ff] SMTP[DATA]: < 250-8BITMIME\r\n^M
[18:35:42.885][7ba290ff] SMTP[DATA]: < 250 DSN\r\n^M
[18:35:42.885][7ba290ff] SMTP[DATA]: > AUTH PLAIN\r\n^M
[18:35:42.886][7ba290ff] SMTP[DATA]: < 334 \r\n^M
[18:35:42.886][7ba290ff] SMTP[SECURE]: > ********\r\n^M
[18:35:42.888][7ba290ff] SMTP[DATA]: < 235 2.7.0 Authentication successful\r\n^M
[18:35:42.888][7ba290ff] SMTP[DATA]: > MAIL FROM:<*********>\r\n^M
[18:35:42.889][7ba290ff] SMTP[DATA]: < 250 2.1.0 Ok\r\n^M
[18:35:42.890][7ba290ff] SMTP[DATA]: > RCPT TO:<********************>\r\n^M
[18:35:42.900][7ba290ff] SMTP[DATA]: < 250 2.1.5 Ok\r\n^M
[18:35:42.900][7ba290ff] SMTP[DATA]: > DATA\r\n^M
[18:35:42.901][7ba290ff] SMTP[DATA]: < 354 End data with <CR><LF>.<CR><LF>\r\n^M
[18:35:42.901][7ba290ff] SMTP[NOTE]: Message data.^M
[18:37:19.889][93c0b314] IMAP[ERROR]: exception 'MailSo\Net\Exceptions\SocketReadException' with message 'MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 515)' in /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Net/NetClient.php:515
Stack trace:
#0 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Imap/ImapClient.php(2033): MailSo\Net\NetClient->getNextBuffer()
#1 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Imap/ImapClient.php(1899): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response))
#2 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Imap/ImapClient.php(1951): MailSo\Imap\ImapClient->parseResponse(NULL, false)
#3 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Imap/ImapClient.php(1708): MailSo\Imap\ImapClient->parseResponseWithValidation()
#4 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Mail/MailClient.php(677): MailSo\Imap\ImapClient->MessageAppendStream('Drafts', Resource id #98, 1864893, Array, 0)
#5 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Actions.php(6141): MailSo\Mail\MailClient->MessageAppendStream(Resource id #98, 1864893, 'Drafts', Array, 0)
#6 [internal function]: RainLoop\Actions->DoSaveMessage()
#7 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#8 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#9 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#10 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#11 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#12 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/handle.php(94): RainLoop\Service::Handle()
#13 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/include.php(225): include('/etc/sentora/pa...')
#14 /var/etc/apps/rainloop/index.php(13): include('/etc/sentora/pa...')
#15 {main}^M
[18:37:19.890][93c0b314] AJAX[DATA]: {"Action":"SaveMessage","Result":false,"ErrorCode":999,"ErrorMessage":"0 - MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 515)","ErrorMessageAdditional":"","Time":802266}^M
[18:37:19.919][93c0b314] IMAP[ERROR]: exception 'MailSo\Net\Exceptions\SocketUnreadBufferException' with message 'MailSo-Net-Exceptions-SocketUnreadBufferException (NetClient.php ~ 426)' in /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Net/NetClient.php:426
Stack trace:
#0 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Imap/ImapClient.php(1790): MailSo\Net\NetClient->sendRaw('TAG3 LOGOUT', true, '')
#1 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Imap/ImapClient.php(1830): MailSo\Imap\ImapClient->SendRequest('LOGOUT', Array)
#2 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Imap/ImapClient.php(393): MailSo\Imap\ImapClient->SendRequestWithCheck('LOGOUT', Array)
#3 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Mail/MailClient.php(118): MailSo\Imap\ImapClient->Logout()
#4 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/MailSo/Mail/MailClient.php(140): MailSo\Mail\MailClient->Logout()
#5 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Actions.php(373): MailSo\Mail\MailClient->LogoutAndDisconnect()
#6 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(251): RainLoop\Actions->BootEnd()
#7 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/app/handle.php(94): RainLoop\Service::Handle()
#10 /var/etc/apps/rainloop/rainloop/v/1.10.4.183/include.php(225): include('/etc/sentora/pa...')
#11 /var/etc/apps/rainloop/index.php(13): include('/etc/sentora/pa...')
#12 {main}^M
[18:37:19.919][93c0b314] INFO[MEMORY]: Memory peak usage: 9.25MB^M
[18:37:19.919][93c0b314] INFO[TIME]: Time delta: 802.2936630249^M

**Comment by Pofilo** [comment]
I just tested with 2 accounts on my rainloop and it works very well ! (even with huge attachments ..)
Can you test the download of attachments with another client like roundcube or another ?

**Comment by bbspike** [comment]
With roudcube no problem..
