### ISSUE TITLE
CantSendMessage[302]

### ISSUE THREAD

**Issue by dows** [RainLoop/rainloop-webmail#1269]
**RainLoop version, browser, OS:**
1.10.5.192 (beta channel) Firefox 50.0 on Windows 7
**Expected behavior and actual behavior:**
answering on a  mail
**Steps to reproduce the problem:**
None. I can't reproduce it from scratch, but if this error appears I'm unable to send the message.
**Logs or screenshots:**

I get _CantSendMessage[302]_ after trying to send answer to a text-mail (no HTML).
This is the log:

> [11:56:47.583][cb01113f] INFO[DATA]: [DATE:23.11.16][OFFSET:-00][RL:1.10.5.192][PHP:5.6.23][IP:80.150.xx.xx][PID:24030][Apache/2.4.23 (Debian) mod_fcgid/2.3.9 OpenSSL/1.0.2j][cgi-fcgi]
> [11:56:47.583][cb01113f] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
> [11:56:47.583][cb01113f] REQUEST[NOTE]: [POST] https://[removed]/?/Ajax/&q[]=/_OQ1j4W-jMWCfVqKlNOBIJA9tVwgurPhTC0suKd1HA56CuNZMnCWKXtMwcygTBLHWSgIcCBqZjBED3TQMnjtcCj4-pEgl-2t7IL_s8adCuIGp-xyAW3ccBV53wTIb4Wu0hT70UFni92nHbfYtBA2rscNirMCdHfcMHYbA0zaWlk41zKMbzf9O8hZq4YosZ6akATWndon5hrpHQ_cLOkseH9_GnRxBiwS58jSSvvsPm4vgAU2Jsbd1NE6Q8QIY37QTKKIY25ERBZOmVOhNnqURKTL2vbSyBbh80K3UZkIIHP01WfEnJHhSg6fOMyAzucqN0KEk-7jjXfxKfy_ddcJyvQ/
> [11:56:47.584][cb01113f] AJAX[NOTE]: Action: DoSendMessage
> [11:56:47.584][cb01113f] POST[DATA]: {"IdentityID":"v18uw67ctqdnkt3rp6ei4qcdm2svtj44","MessageFolder":"INBOX.Drafts","MessageUid":"1297","SentFolder":"INBOX.Sent","To":[removed],"Cc":"","Bcc":"","ReplyTo":"","Subject":"Re: [removed]","TextIsHtml":"0","Text":"[removed]","DraftInfo":["reply","6426","INBOX"],"InReplyTo":"<[removed]>","References":"<[removed]>","Dsn":"0","ReadReceiptRequest":"0","MarkAsImportant":"0","Action":"SendMessage","XToken":"96c0e007b63e3e3f6b788abb05e63724"}
> [11:56:47.586][cb01113f] IMAP[NOTE]: Start connection to "ssl://[removed]:993"
> [11:56:47.609][cb01113f] IMAP[NOTE]: Connected (success)
> [11:56:47.649][cb01113f] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE SORT IDLE QUOTA THREAD=REFERENCES MULTIAPPEND UNSELECT LITERAL+] perdition ready on [removed] 0002a13c\r\n
> [11:56:47.650][cb01113f] IMAP[SECURE]: > TAG1 LOGIN "[removed]" "********"\r\n
> [11:56:47.678][cb01113f] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE QUOTA\r\n
> [11:56:47.719][cb01113f] IMAP[DATA]: < TAG1 OK You are so in\r\n
> [11:56:47.794][cb01113f] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'CantSendMessage[302]' in /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php:6252
> Stack trace:
> #0 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #93, 2769, false, true)
> #1 [internal function]: RainLoop\Actions->DoSendMessage()
> #2 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
> #3 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
> #4 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
> #5 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
> #6 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
> #7 /www/tools/rainloop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
> #8 /www/tools/rainloop/rainloop/v/1.10.5.192/include.php(225): include('/www/tools/rain...')
> #9 /www/tools/rainloop/index.php(13): include('/www/tools/rain...')
> #10 {main}
> [11:56:47.794][cb01113f] INFO[ERROR]: exception 'RainLoop\Exceptions\ClientException' with message 'CantSendMessage[302]' in /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php:6252
> Stack trace:
> #0 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #93, 2769, false, true)
> #1 [internal function]: RainLoop\Actions->DoSendMessage()
> #2 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
> #3 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
> #4 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
> #5 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
> #6 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
> #7 /www/tools/rainloop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
> #8 /www/tools/rainloop/rainloop/v/1.10.5.192/include.php(225): include('/www/tools/rain...')
> #9 /www/tools/rainloop/index.php(13): include('/www/tools/rain...')
> #10 {main}
> 
> Next exception 'RainLoop\Exceptions\ClientException' with message 'CantSendMessage[302]' in /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php:6315
> Stack trace:
> #0 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #93, 2769, false, true)
> #1 [internal function]: RainLoop\Actions->DoSendMessage()
> #2 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
> #3 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
> #4 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
> #5 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
> #6 /www/tools/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
> #7 /www/tools/rainloop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
> #8 /www/tools/rainloop/rainloop/v/1.10.5.192/include.php(225): include('/www/tools/rain...')
> #9 /www/tools/rainloop/index.php(13): include('/www/tools/rain...')
> #10 {main}
> [11:56:47.794][cb01113f] AJAX[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":902,"ErrorMessage":"CantSendMessage[302]","ErrorMessageAdditional":"","Time":226}
> [11:56:47.799][cb01113f] IMAP[DATA]: > TAG2 LOGOUT\r\n
> [11:56:47.801][cb01113f] IMAP[DATA]: < * BYE Logging out\r\n
> [11:56:47.801][cb01113f] IMAP[DATA]: < TAG2 OK Logout completed.\r\n
> [11:56:47.804][cb01113f] IMAP[NOTE]: Disconnected from "ssl://[removed]:993" (success)
> [11:56:47.804][cb01113f] INFO[MEMORY]: Memory peak usage: 1.75MB
> [11:56:47.804][cb01113f] INFO[TIME]: Time delta: 0.23592209815979
> 
> [11:56:47.858][0b8aa365] INFO[DATA]: [DATE:23.11.16][OFFSET:-00][RL:1.10.5.192][PHP:5.6.23][IP:80.150.xx.xx][PID:24030][Apache/2.4.23 (Debian) mod_fcgid/2.3.9 OpenSSL/1.0.2j][cgi-fcgi]
> [11:56:47.858][0b8aa365] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
> [11:56:47.858][0b8aa365] REQUEST[NOTE]: [POST] https://[removed]/?/Ajax/&q[]=/_OQ1j4W-jMWCfVqKlNOBIJA9tVwgurPhTC0suKd1HA56CuNZMnCWKXtMwcygTBLHWSgIcCBqZjBED3TQMnjtcCj4-pEgl-2t7IL_s8adCuIGp-xyAW3ccBV53wTIb4Wu0hT70UFni92nHbfYtBA2rscNirMCdHfcMHYbA0zaWlk41zKMbzf9O8hZq4YosZ6akATWndon5hrpHQ_cLOkseH9_GnRxBiwS58jSSvvsPm4vgAU2Jsbd1NE6Q8QIY37QTKKIY25ERBZOmVOhNnqURKTL2vbSyBbh80K3UZkIIHP01WfEnJHhSg6fOMyAzucqN0KEk-7jjXfxKfy_ddcJyvQ/
> [11:56:47.859][0b8aa365] AJAX[NOTE]: Action: DoFolderInformation
> [11:56:47.859][0b8aa365] POST[DATA]: {"Folder":"INBOX.Drafts","FlagsUids":"","UidNext":"","Action":"FolderInformation","XToken":"96c0e007b63e3e3f6b788abb05e63724"}
> [11:56:47.862][0b8aa365] IMAP[NOTE]: Start connection to "ssl://[removed]:993"
> [11:56:47.885][0b8aa365] IMAP[NOTE]: Connected (success)
> [11:56:47.925][0b8aa365] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE SORT IDLE QUOTA THREAD=REFERENCES MULTIAPPEND UNSELECT LITERAL+] perdition ready on [removed] 0002a16e\r\n
> [11:56:47.926][0b8aa365] IMAP[SECURE]: > TAG1 LOGIN "[removed]" "********"\r\n
> [11:56:51.955][0b8aa365] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE QUOTA\r\n
> [11:56:51.996][0b8aa365] IMAP[DATA]: < TAG1 OK You are so in\r\n
> [11:56:51.996][0b8aa365] IMAP[DATA]: > TAG2 CAPABILITY\r\n
> [11:56:51.999][0b8aa365] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE QUOTA\r\n
> [11:56:52.000][0b8aa365] IMAP[DATA]: < TAG2 OK Capability completed.\r\n
> [11:56:52.000][0b8aa365] IMAP[DATA]: > TAG3 STATUS "INBOX.Drafts" (MESSAGES UNSEEN UIDNEXT HIGHESTMODSEQ)\r\n
> [11:56:53.996][0b8aa365] IMAP[DATA]: < * STATUS INBOX.Drafts (MESSAGES 1 UIDNEXT 1298 UNSEEN 0 HIGHESTMODSEQ 3876)\r\n
> [11:56:53.996][0b8aa365] IMAP[DATA]: < TAG3 OK Status completed.\r\n
> [11:56:53.997][0b8aa365] AJAX[DATA]: {"Action":"FolderInformation","Result":{"Folder":"INBOX.Drafts","Hash":"ec021d07b160ce512f8daccc9346413c","MessageCount":1,"MessageUnseenCount":0,"UidNext":"1298","Flags":[],"HighestModSeq":"3876","NewMessages":[],"Version":"1.10.5.192"},"Time":6153}
> [11:56:54.001][0b8aa365] IMAP[DATA]: > TAG4 LOGOUT\r\n
> [11:56:54.004][0b8aa365] IMAP[DATA]: < * BYE Logging out\r\n
> [11:56:54.004][0b8aa365] IMAP[DATA]: < TAG4 OK Logout completed.\r\n
> [11:56:54.006][0b8aa365] IMAP[NOTE]: Disconnected from "ssl://[removed]:993" (success)
> [11:56:54.006][0b8aa365] INFO[MEMORY]: Memory peak usage: 1.25MB
> [11:56:54.007][0b8aa365] INFO[TIME]: Time delta: 6.162446975708

The mail I'm trying to answer:

> Return-path: [removed: senders mail]
> X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on vserverimap74
> X-Spam-Level: 
> X-Spam-Status: No, score=-5.6 required=4.5 tests=BAYES_00,RCVD_IN_DNSWL_LOW,
> 	RCVD_IN_MSPIKE_H2,RP_MATCHES_RCVD,SPF_PASS autolearn=ham autolearn_force=no
> 	version=3.4.0
> Envelope-to: [removed:username]@[removed:servername]
> Delivery-date: Mon, 21 Nov 2016 19:23:21 +0000
> Received: from [removed:smtpservername] ([84.38.xx.xx])
> 	by [removed:servername] with esmtps (TLS1.2:ECDHE_RSA_AES_128_GCM_SHA256:128)
> 	(Exim 4.84_2)
> 	(envelope-from [removed: senders mail])
> 	id 1c8uBV-0006qN-HD
> 	for [removed:username]@[removed:servername]; Mon, 21 Nov 2016 19:23:21 +0000
> Received: from [removed:senders domain] ([185.67.xx.xx])
> 	by [removed:smtpservername] with esmtps (TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256)
> 	(Exim 4.84_2)
> 	(envelope-from [removed: senders mail])
> 	id 1c8uBV-0006Dj-AL
> 	for [removed:my mail]; Mon, 21 Nov 2016 19:23:21 +0000
> Received: from submission ([removed:senders domain] [89.146.220.130]) 
> 	by mout02.[removed:senders domain] (Postfix) with ESMTPS id B8C7121ADF
> 	for [removed:my mail]; Mon, 21 Nov 2016 20:23:15 +0100 (CET)
> Received: from customer (localhost [127.0.0.1])
> 	by submission ([removed:senders domain]) with ESMTPSA id 3tMz5v0H1mzyyQ
> 	for [removed:my mail]; Mon, 21 Nov 2016 20:23:14 +0100 (CET)
> From: [removed: senders mail]
> Content-Type: text/plain; charset=utf-8
> Content-Transfer-Encoding: quoted-printable
> Subject: =?utf-8?Q?[removed:subject]
> Message-Id: <88A2F413-207C-4E6A-8E65-047C3666A2B0@[removed:senders domain]>
> Date: Mon, 21 Nov 2016 20:23:14 +0100
> To: [removed:my mail]
> Mime-Version: 1.0 (Mac OS X Mail 9.3 \(3124\))
> X-Mailer: Apple Mail (2.3124)
> 
> [removed:Text]

**Comment by dows** [comment]
can be closed
error appeared due to a hosted webspace/mailspace issue
