### ISSUE TITLE
Sieve rules/filters stop to work

### ISSUE THREAD

**Issue by russel-online** [RainLoop/rainloop-webmail#1274]
**RainLoop version, browser, OS:**
[RL:1.10.5.192]
[PHP:5.6.25]
[Apache]

**Expected behavior and actual behavior:**
I add a lot of sieve rules under one of my account and now I'm not able to add any new rule. I can delete existing or change there state. But I can not add new email to rules or new Filter. 
Every time when I try to "Save" I have an message "Invalid Token".
Under all others accounts everything is still working well.

**Logs or screenshots:**
`[09:23:06.540][3de9cfbd] INFO[DATA]: [DATE:30.11.16][OFFSET:-00][RL:1.10.5.192][PHP:5.6.25][IP:176.107.177.2][PID:28491][Apache][apache2handler]
[09:23:06.540][3de9cfbd] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[09:23:06.541][3de9cfbd] REQUEST[NOTE]: [POST] https://***.com/?/Ajax/&q[]=/_***
[09:23:06.544][3de9cfbd] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'InvalidToken[101]' in /Library/Server/Web/Data/Sites/***.com/rainloop/v/1.10.5.192/app/libraries/Rain$
Stack trace:
#0 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#1 /Library/Server/Web/Data/Sites/***.com/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#2 /Library/Server/Web/Data/Sites/***.com/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /Library/Server/Web/Data/Sites/***.com/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /Library/Server/Web/Data/Sites/***.com/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#5 /Library/Server/Web/Data/Sites/***.com/rainloop/v/1.10.5.192/include.php(225): include('/Library/Server...')
#6 /Library/Server/Web/Data/Sites/***.com/index.php(13): include('/Library/Server...')
#7 {main}
[09:23:06.544][3de9cfbd] AJAX[DATA]: {"Action":"Unknown","Result":false,"ErrorCode":101,"ErrorMessage":"","ErrorMessageAdditional":"","Time":42}
[09:23:06.558][3de9cfbd] INFO[MEMORY]: Memory peak usage: 6MB`

**Comment by ervee** [comment]
Duplicate of #1137?

**Comment by russel-online** [comment]
looks like yes.

at #1137 topic is about number of Filters, but I think the problem is in number of entered emails.

Any idea how to solve this?

**Comment by ervee** [comment]
I don't know if there is anything useful in the logs that @RainLoop can use.

Could you perhaps post the output of ```find . -ls | grep sieve``` when run in the user home dir?

And post the contents of sieve logfiles found with the above command  (if there is no sensitive info in that, else mail it to support@rainloop.net).

And the content of ./sieve/rainloop.user.sieve (if there is no sensitive info in that, else mail it to support@rainloop.net)

**Comment by russel-online** [comment]
I was not able to find sieve logs.

I sent you by email output of grep and rainloop.user.sieve with which I have a problem.

**Comment by russel-online** [comment]
Hi, any update?
