### ISSUE TITLE
Rainloop doesn't use application.ini after same time and looks default

### ISSUE THREAD

**Issue by insound** [RainLoop/rainloop-webmail#1287]
**RainLoop version, browser, OS:**
1.10.5.192]
**Expected behavior and actual behavior:**
When php-fpm restart - all ok., but after some time rainloop login page opened with default theme and doesnt use application.ini
even restart php-fpm all ok again, and when enter admin and change settings application.ini saves.

Sometime need hour, sometime day, sometime 5 minuts to this stuck.

Im try to changes rules of nginx and other, update php, change php-fpm config, but this issue come again.

**Logs or screenshots:**
[10:02:23.015][cf710b80] INFO[DATA]: [DATE:15.12.16][OFFSET:-00][RL:1.10.5.192][PHP:5.6.28][IP:*****][PID:29028][nginx/1.11.7][fpm-fcgi]
[10:02:23.015][cf710b80] INFO[DATA]: [Suhosin:on][APC:on][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[10:02:23.016][cf710b80] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'InvalidToken[101]' in /public_html/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php:133
Stack trace:
#0 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#1 public_html/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#2 public_html/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /public_html/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 public_html/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#5 public_html/rainloop/v/1.10.5.192/include.php(225): include('/home/webmail/w...')
#6 public_html/index.php(13): include('/home/webmail/w...')
#7 {main}{"Action":"FolderInformation","Result":false,"ErrorCode":101,"ErrorMessage":"","ErrorMessageAdditional":"","Time":13}

**Comment by megadr01d** [comment]
Reference: https://github.com/RainLoop/rainloop-webmail/issues/1509
Commit: https://github.com/RainLoop/rainloop-webmail/commit/f695a1acd2359cc2e94846b828265e9b11fdd402
