### ISSUE TITLE
SSL sslv3 alert handshake failure

### ISSUE THREAD

**Issue by voti** [RainLoop/rainloop-webmail#1304]
**RainLoop version, browser, OS:**
RainLoop 1.10.5.192
Firefox 50.0
Win10/Linux
**Mail server**
[docker-mailserver](https://github.com/tomav/docker-mailserver) with let's encrypt
it works well,with thunderbird and my phone IOS
**Steps to reproduce the problem:**
adding a domain with admin panel
click test
error
```
stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```
**Logs or screenshots:**
```
[19:55:55.227][3a55e7fd] POST[DATA]: {"Name":"domain.com","IncHost":"mail.domain.com","IncPort":"993","IncSecure":"1","UseSieve":"0","SieveHost":"","SievePort":"4190","SieveSecure":"0","OutHost":"mail.domain.com","OutPort":"587","OutSecure":"2","OutAuth":"1","OutUsePhpMail":"0","Action":"AdminDomainTest","XToken":"60d59d4ca52b04605f0539c13afbb69a"}
[19:55:55.228][3a55e7fd] IMAP[NOTE]: Start connection to "ssl://mail.domain.com:993"
[19:55:55.250][3a55e7fd] IMAP[NOTE]: Connected (unsuccess)
[19:55:55.407][3a55e7fd] IMAP[NOTICE]: Socket: [2] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[19:55:55.407][3a55e7fd] IMAP[NOTICE]: MailSo\Net\Exceptions\SocketCanNotConnectToHostException: Can't connect to host "ssl://mail.domain.com:993" in /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/MailSo/Net/NetClient.php:292
Stack trace:
#0 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/MailSo/Imap/ImapClient.php(153): MailSo\Net\NetClient->Connect('mail.domain....', 993, 1, true, false)
#1 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(4140): MailSo\Imap\ImapClient->Connect('mail.domain....', 993, 1, true, false)
#2 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoAdminDomainTest()
#3 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#4 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#5 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#6 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#7 /var/www/html/rainloop/rainloop/v/1.10.5.192/include.php(225): include('/var/www/html/r...')
#8 /var/www/html/rainloop/index.php(13): include('/var/www/html/r...')
#9 {main}
[19:55:55.422][3a55e7fd] SMTP[NOTE]: Start connection to "tcp://mail.domain.com:587"
[19:55:55.423][3a55e7fd] SMTP[NOTE]: Connected (success)
[19:55:55.491][3a55e7fd] SMTP[DATA]: < 220 mail.domain.com ESMTP Postfix (Ubuntu)\r\n
[19:55:55.491][3a55e7fd] SMTP[DATA]: > EHLO mail.domain.com\r\n
[19:55:55.491][3a55e7fd] SMTP[DATA]: < 250-mail.domain.com\r\n
[19:55:55.491][3a55e7fd] SMTP[DATA]: < 250-PIPELINING\r\n
[19:55:55.491][3a55e7fd] SMTP[DATA]: < 250-SIZE 10240000\r\n
[19:55:55.491][3a55e7fd] SMTP[DATA]: < 250-VRFY\r\n
[19:55:55.491][3a55e7fd] SMTP[DATA]: < 250-ETRN\r\n
[19:55:55.491][3a55e7fd] SMTP[DATA]: < 250-STARTTLS\r\n
[19:55:55.492][3a55e7fd] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n
[19:55:55.492][3a55e7fd] SMTP[DATA]: < 250-8BITMIME\r\n
[19:55:55.492][3a55e7fd] SMTP[DATA]: < 250 DSN\r\n
[19:55:55.492][3a55e7fd] SMTP[DATA]: > STARTTLS\r\n
[19:55:55.492][3a55e7fd] SMTP[DATA]: < 220 2.0.0 Ready to start TLS\r\n
[19:55:55.598][3a55e7fd] SMTP[DATA]: > EHLO mail.domain.com\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-mail.domain.com\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-PIPELINING\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-SIZE 10240000\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-VRFY\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-ETRN\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-AUTH PLAIN LOGIN\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-AUTH=PLAIN LOGIN\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250-8BITMIME\r\n
[19:55:55.599][3a55e7fd] SMTP[DATA]: < 250 DSN\r\n
[19:55:55.599][3a55e7fd] SMTP[NOTE]: Disconnected from "tcp://mail.domain.com:587" (success)
[19:55:55.599][3a55e7fd] AJAX[DATA]: {"Action":"AdminDomainTest","Result":{"Imap":"stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure","Smtp":true,"Sieve":true},"Time":384}

```

**HELP OR ANY SUGGESTIONS！！！**

**Comment by butlerx** [comment]
having same issue

**Comment by RainLoop** [comment]
It looks like your server is blocking the connection to the remote mail server. A timeout occurs after 10 seconds. Check the firewall configuration or something like that.

**Comment by mitchal01** [comment]
MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 515)

**Comment by e-stonia** [comment]
I have the issue only for Sieve. Email works.

**Comment by arghyadeep-k** [comment]
@kdaye Is `ENABLE_MANAGESIEVE` flag = 1 in the environment variables file?

**Comment by azriel49** [comment]
Same problem here, with SIEVE enabled. Any idea?
