### ISSUE TITLE
NextCloud Cardav Synchronization: Error while syncing contacts

### ISSUE THREAD

**Issue by jkalousek** [RainLoop/rainloop-webmail#1320]
I use NextCloud CardDav with my Android phone and with my desktop e-mail client, but when I type addressbook URL and correct credentials, and then try to sync it gives me popup window with text "Error while syncing contacts" (maybe not accurate translated from my native language)

**RainLoop version, browser, OS:**
Server: RainLoop 1.10.4.183 on Ubuntu 14.04 LTS/NextCloud 11.0.1 (stable)
Client: Win 10, Chrome 55.0.2883.87

**Logs or screenshots:**
Nothing in Appache logs.

RainLoop logs:
```
[09:19:13.932][aab9de5f] INFO[NOTICE]: RainLoop\Exceptions\ClientException: ContactsSyncError[140] in /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.10.4.183/app/libraries/RainLoop/Actions.php:6699
Stack trace:
#0 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.10.4.183/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoContactsSync()
#1 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#2 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.10.4.183/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.10.4.183/app/handle.php(94): RainLoop\Service::Handle()
#5 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.10.4.183/include.php(225): include('/var/www/nextcl...')
#6 /var/www/nextcloud/apps/rainloop/app/index.php(13): include('/var/www/nextcl...')
#7 /var/www/nextcloud/apps/rainloop/app.php(35): include('/var/www/nextcl...')
#8 /var/www/nextcloud/lib/private/Route/Route.php(155) : runtime-created function(1): require_once('/var/www/nextcl...')
#9 [internal function]: __lambda_func()
#10 /var/www/nextcloud/lib/private/Route/Router.php(299): call_user_func('\x00lambda_1942', Array)
#11 /var/www/nextcloud/lib/base.php(1010): OC\Route\Router->match('/apps/rainloop/...')
#12 /var/www/nextcloud/index.php(40): OC::handleRequest()
#13 {main}
[09:19:13.932][aab9de5f] AJAX[DATA]: {"Action":"ContactsSync","Result":false,"ErrorCode":140,"ErrorMessage":"","ErrorMessageAdditional":"","Time":20}
[09:19:13.933][aab9de5f] INFO[MEMORY]: Memory peak usage: 4MB
[09:19:13.933][aab9de5f] INFO[TIME]: Time delta: 0.020653963088989

[09:19:15.286][4141fabb] INFO[DATA]: [DATE:20.01.17][RL:1.10.4.183][PHP:7.0.13-0ubuntu0.16.04.1][IP:192.168.6.88][PID:395][Apache/2.4.18 (Ubuntu)][apache2handler]
[09:19:15.286][4141fabb] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][ownCloud:true][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[09:19:15.286][4141fabb] REQUEST[NOTE]: [POST] http://***REDACTED***.net/index.php/apps/rainloop/app/?/Ajax/&q[]=/_np2nCAYU9XGqryvvNy7TQQYtF00xh2iTlsgnkra2zn-mAy16yYD5ZttOl9edm5-hltmRxUQP9X_aZIFJVAwu6-Ai6YBLVm8hRLXgOEPQNx9MlCY5_JiqbCSaf8cerebeZmk8cz-_qruzEgKawxmcHfH8J5VSOWkrpL3v5mrpM0MQ4DkpB1xbyqXg-yfasd2w3hPkfSuLcolFKWkf5PNtXmXLZL5qrovenRrWTQ2-BOMi4wmUjc-wl5RsePzqXKTk9aEl325KnVbpLCyED9Tv418HGf7DaGY-FZTTWcAH5rsy9-QPazlQMGxRMTVrsfUtHUCML5TzOHI7_9OzaO1_oj8C1jvSxafWh78UBQ/
[09:19:15.287][4141fabb] AJAX[NOTE]: Action: DoContacts
[09:19:15.287][4141fabb] POST[DATA]: {"Offset":"0","Limit":"50","Search":"","Action":"Contacts","XToken":"c2a63cc915e1260170d3e347640283aa"}
[09:19:15.288][4141fabb] SQL[DATA]: SELECT value_int FROM rainloop_system WHERE sys_name = ?
[09:19:15.288][4141fabb] SQL[DATA]: SELECT id_user FROM rainloop_users WHERE rl_email = :rl_email
[09:19:15.288][4141fabb] SQL[DATA]: SELECT COUNT(DISTINCT id_contact) as contact_count FROM rainloop_ab_properties WHERE id_user = :id_user
[09:19:15.288][4141fabb] AJAX[DATA]: {"Action":"Contacts","Result":{"Offset":0,"Limit":50,"Count":0,"Search":"","List":[]},"Time":13}
[09:19:15.289][4141fabb] INFO[MEMORY]: Memory peak usage: 4MB
[09:19:15.289][4141fabb] INFO[TIME]: Time delta: 0.013586044311523
```

Problem is maybe here: `http://***REDACTED***.net/` it should be **https://** but for some reason it uses **http://**.
Maybe it is because NC it behind reverse proxy. Is there option to force usage of https?

**Comment by jkalousek** [comment]
BTW option `force_https = On` is not solution. If set On, I can't access the app.

**Comment by jkalousek** [comment]
As I search thru options I came across `owncloud_suggestions = On`.
I didn't realize at all that RainLoop automatically take suggestions from OC/NC addressbook. I'm sorry. :)
