### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by Prodigys** [RainLoop/rainloop-webmail#1372]
**RainLoop version, browser, OS:**
v1.11.0.203

**Logs or screenshots:**

[23:37:21.236][47f7322e] INFO[DATA]: [DATE:16.03.17][OFFSET:-00][RL:1.11.0.203][PHP:5.6.29-1~dotdeb+7.1][IP:193.70.43.196][PID:11330][Apache/2.2.22 (Debian)][apache2handler]
[23:37:21.236][47f7322e] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[23:37:21.236][47f7322e] REQUEST[NOTE]: [GET] http://mail.nazahost.pt/?admin
[23:37:21.252][47f7322e] INFO[MEMORY]: Memory peak usage: 1.25MB
[23:37:21.252][47f7322e] INFO[TIME]: Time delta: 0.04474401473999

[23:37:21.374][abb2d957] INFO[DATA]: [DATE:16.03.17][OFFSET:-00][RL:1.11.0.203][PHP:5.6.29-1~dotdeb+7.1][IP:193.70.43.196][PID:11338][Apache/2.2.22 (Debian)][apache2handler]
[23:37:21.375][abb2d957] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[23:37:21.375][abb2d957] REQUEST[NOTE]: [GET] http://mail.nazahost.pt/?/Css/0/Admin/-/Default/-/3669df9ebb2896aea386540b93e6d56a/Hash/-/
[23:37:21.377][abb2d957] INFO[MEMORY]: Memory peak usage: 1024KB
[23:37:21.377][abb2d957] INFO[TIME]: Time delta: 0.019003868103027

[23:37:21.514][d4cd04b2] INFO[DATA]: [DATE:16.03.17][OFFSET:-00][RL:1.11.0.203][PHP:5.6.29-1~dotdeb+7.1][IP:193.70.43.196][PID:11339][Apache/2.2.22 (Debian)][apache2handler]
[23:37:21.514][d4cd04b2] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[23:37:21.514][d4cd04b2] REQUEST[NOTE]: [GET] http://mail.nazahost.pt/?/AdminAppData@no-mobile-0/0/8392644683251037/
[23:37:21.529][d4cd04b2] APPDATA[DATA]: if(window.__initAppData){window.__initAppData({"Auth":false,"AccountHash":"","AccountSignMe":false,"AuthAccountHash":"","MailToEmail":"","Email":"","DevEmail":"","DevPassword":"","Title":"Nazahost Webmail","LoadingDescription":"Nazahost","LoadingDescriptionEsc":"Nazahost","FaviconUrl":"","LoginDescription":"","LoginPowered":true,"LoginLogo":"","LoginBackground":"","LoginCss":"","UserLogo":"","UserLogoTitle":"","UserLogoMessage":"","UserCss":"","WelcomePageUrl":"","WelcomePageDisplay":"none","IncludeCss":"","IncludeBackground":"","LoginDefaultDomain":"","DetermineUserLanguage":true,"DetermineUserDomain":true,"UseLoginWelcomePage":false,"StartupUrl":"","ContactsIsAllowed":false,"ChangePasswordIsAllowed":false,"RequireTwoFactor":false,"Community":false,"PremType":false,"Admin":[],"Capa":["FOLDERS","MESSAGELIST_ACTIONS","DANGEROUS_ACTIONS","RELOAD","QUOTA","SETTINGS","ADDITIONAL_ACCOUNTS","IDENTITIES","THEMES","FILTERS","SIEVE","TWO_FACTOR","HELP","ATTACHMENTS_ACTIONS","MESSAGE_ACTIONS","COMPOSER","CONTACTS","SEARCH","SEARCH_ADV","GRAVATAR","ATTACHMENT_THUMBNAILS","PREFETCH","AUTOLOGOUT"],"Plugins":{"video-on-login-screen":{"mp4_file":"","webm_file":"","ogv_file":"","playback_rate":"100%","muted":true},"recaptcha":{"public_key":"6LeKURkUAAAAAJwfdN5-vaabNCytdJA80V59iVDH","theme":"light"}},"System":{"version":"1.11.0.203","admin":true,"mobile":false,"mobileDevice":false,"webPath":"","webVersionPath":"rainloop\/v\/1.11.0.203\/","token":"9eb08bcbda0a3be2e9067e7f418728e8","inIframe":false,"allowHtmlEditorSourceButton":false,"allowHtmlEditorBitiButtons":false,"allowCtrlEnterOnCompose":false,"customLoginLink":"","customLogoutLink":"","forgotPasswordLinkUrl":"","registrationLinkUrl":"","loginGlassStyle":true,"hideSubmitButton":true,"activeBackgroud":false,"jsHash":"7ffdbac453e5a6104cf08e89a0a99453","useImapThread":true,"useImapSubscribe":true,"allowAppendMessage":false,"materialDesign":true,"folderSpecLimit":50,"faviconStatus":true,"allowCmdInterface":false,"useNativeScrollbars":false,"listPermanentFiltered":false,"themes":["Default","A","Blurred","DarkShine","Linen","Love","Snow","Squares","SquaresDark","Stripes","Wood","Xv","Clear"],"languages":["ar_SA","bg_BG","cs_CZ","da_DK","de_DE","el_GR","en_GB","en_US","es_ES","et_EE","fa_IR","fi_FI","fr_FR","hu_HU","is_IS","it_IT","ja_JP","ko_KR","lt_LT","lv_LV","nb_NO","nl_NL","pl_PL","pt_BR","pt_PT","ro_RO","ru_RU","sk_SK","sl_SI","sv_SE","tr_TR","uk_UA","zh_CN","zh_TW"],"languagesAdmin":["cs_CZ","da_DK","de_DE","en_US","es_ES","fa_IR","fi_FI","fr_FR","hu_HU","it_IT","ja_JP","lt_LT","nb_NO","nl_NL","pl_PL","pt_BR","ru_RU","sl_SI","sv_SE","zh_CN"],"appVersionType":"standard","attachmentsActions":["zip"],"adminHostUse":false,"adminPath":"admin","allowAdminPanel":true},"SupportedFacebookSocial":true,"ProjectHash":"3669df9ebb2896aea386540b93e6d56a","NewMoveToFolder":true,"AllowLanguagesOnSettings":true,"AllowLanguagesOnLogin":true,"AttachmentLimit":26214400,"SignMe":"DefaultOff","UseLocalProxyForExternalImages":false,"ShowImages":false,"MPP":20,"SoundNotification":false,"DesktopNotifications":false,"Layout":1,"EditorDefaultType":"Html","UseCheckboxesInList":true,"AutoLogout":30,"UseThreads":false,"ReplySameFolder":false,"ContactsAutosave":true,"EnableTwoFactor":false,"ParentEmail":"","InterfaceAnimation":true,"UserBackgroundName":"","UserBackgroundHash":"","Theme":"Default","NewThemeLink":".\/?\/Css\/0\/Admin\/-\/Default\/-\/3669df9ebb2896aea386540b93e6d56a\/Hash\/-\/","Language":"pt_PT","LanguageAdmin":"pt_BR","UserLanguageRaw":"en_US","UserLanguage":"en_US","UserLanguageAdmin":"en_US","PluginsLink":"","LangLink":".\/?\/Lang\/0\/Admin\/pt_BR\/3669df9ebb2896aea386540b93e6d56a\/","TemplatesLink":".\/?\/Templates\/0\/Admin\/3669df9ebb2896aea386540b93e6d56a\/","StaticLibJsLink":"rainloop\/v\/1.11.0.203\/static\/js\/min\/libs.min.js?standard","StaticAppJsLink":"rainloop\/v\/1.11.0.203\/static\/js\/min\/admin.min.js?standard","StaticAppJsNextLink":"rainloop\/v\/1.11.0.203\/static\/js\/admin.next.js?standard","StaticEditorJsLink":"rainloop\/v\/1.11.0.203\/static\/ckeditor\/ckeditor.js?standard"});}
[23:37:21.532][d4cd04b2] INFO[MEMORY]: Memory peak usage: 1.25MB
[23:37:21.532][d4cd04b2] INFO[TIME]: Time delta: 0.036265850067139

[23:37:21.620][8410c086] INFO[DATA]: [DATE:16.03.17][OFFSET:-00][RL:1.11.0.203][PHP:5.6.29-1~dotdeb+7.1][IP:193.70.43.196][PID:11340][Apache/2.2.22 (Debian)][apache2handler]
[23:37:21.621][8410c086] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[23:37:21.621][8410c086] REQUEST[NOTE]: [GET] http://mail.nazahost.pt/?/Templates/0/Admin/3669df9ebb2896aea386540b93e6d56a/
[23:37:21.621][8410c086] INFO[MEMORY]: Memory peak usage: 1024KB
[23:37:21.622][8410c086] INFO[TIME]: Time delta: 0.021575927734375

[23:37:21.624][b4d14256] INFO[DATA]: [DATE:16.03.17][OFFSET:-00][RL:1.11.0.203][PHP:5.6.29-1~dotdeb+7.1][IP:193.70.43.196][PID:11337][Apache/2.2.22 (Debian)][apache2handler]
[23:37:21.624][b4d14256] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[23:37:21.624][b4d14256] REQUEST[NOTE]: [GET] http://mail.nazahost.pt/?/Lang/0/Admin/pt_BR/3669df9ebb2896aea386540b93e6d56a/
[23:37:21.628][b4d14256] INFO[MEMORY]: Memory peak usage: 1024KB
[23:37:21.628][b4d14256] INFO[TIME]: Time delta: 0.024555921554565

[23:37:27.935][cb999542] INFO[DATA]: [DATE:16.03.17][OFFSET:-00][RL:1.11.0.203][PHP:5.6.29-1~dotdeb+7.1][IP:193.70.43.196][PID:11332][Apache/2.2.22 (Debian)][apache2handler]
[23:37:27.935][cb999542] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[23:37:27.935][cb999542] REQUEST[NOTE]: [POST] http://mail.nazahost.pt/?/Ajax/&q[]=/0/
[23:37:27.936][cb999542] AJAX[NOTE]: Action: DoAdminLogin
[23:37:27.936][cb999542] POST[DATA]: {"Login":"borntogo123@gmail.com","Password":"*******","Action":"AdminLogin","XToken":"9eb08bcbda0a3be2e9067e7f418728e8"}
[23:37:27.937][cb999542] PLUGIN[NOTE]: Hook: ajax.action-pre-call
[23:37:28.939][cb999542] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'AuthError[102]' in /home/admin/web/mail.nazahost.pt/public_html/rainloop/v/1.11.0.203/app/libraries/RainLoop/Actions.php:3837
Stack trace:
#0 [internal function]: RainLoop\Actions->DoAdminLogin()
#1 /home/admin/web/mail.nazahost.pt/public_html/rainloop/v/1.11.0.203/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#2 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#3 /home/admin/web/mail.nazahost.pt/public_html/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#4 /home/admin/web/mail.nazahost.pt/public_html/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#5 /home/admin/web/mail.nazahost.pt/public_html/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#6 /home/admin/web/mail.nazahost.pt/public_html/rainloop/v/1.11.0.203/app/handle.php(94): RainLoop\Service::Handle()
#7 /home/admin/web/mail.nazahost.pt/public_html/rainloop/v/1.11.0.203/include.php(225): include('/home/admin/web...')
#8 /home/admin/web/mail.nazahost.pt/public_html/index.php(13): include('/home/admin/web...')
#9 {main}
[23:37:28.939][cb999542] PLUGIN[NOTE]: Hook: filter.ajax-response
[23:37:28.939][cb999542] AJAX[DATA]: {"Action":"AdminLogin","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1030}
[23:37:28.942][cb999542] INFO[MEMORY]: Memory peak usage: 1.25MB
[23:37:28.943][cb999542] INFO[TIME]: Time delta: 1.0333671569824

The line that i see more relevant is this one < {"Action":"AdminLogin","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1030} >

**Comment by ervee** [comment]
Are you trying to use a Gmail account to login to the RainLoop amin page?

**Comment by Prodigys** [comment]
Yes i am. Gmail blocks it i viewed now. I'm using my own domain as a mail server. This is solved anyways :P
