### ISSUE TITLE
Authentication failed while sending email

### ISSUE THREAD

**Issue by bobalo2** [RainLoop/rainloop-webmail#1373]
**RainLoop version, browser, OS:**
1.11.0.203 , Firefox , Ubuntu 14.04 LTS

**Expected behavior and actual behavior:**
After a working environment , where rainloop used to send messages before , it now shows authentication failed in the js console while trying to send an e-mail message. Receiving messages works fine.

**Steps to reproduce the problem:**
New Message -> Send Message

**Logs or screenshots:**
```
`

[14:32:53.886][f2254d92] SMTP[SECURE]: > ********\r\n
[14:32:53.886][f2254d92] SMTP[DATA]: < 435 Unable to authenticate at present\r\n
[14:32:53.886][f2254d92] SMTP[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: 435 Unable to authenticate at present in /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php:789
Stack trace:
#0 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(670): MailSo\Smtp\SmtpClient->validateResponse(Array)
#1 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(296): MailSo\Smtp\SmtpClient->sendRequestWithCheck('Ym9ibzIxMjE=', 235, '', true)
#2 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(521): MailSo\Smtp\SmtpClient->Login('admin@***.c...', '*******', true, false)
#3 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#4 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #83, 903, false, true)
#5 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#6 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#7 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /srv/RainLoop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#10 /srv/RainLoop/rainloop/v/1.10.5.192/include.php(225): include('/srv/RainLoop/r...')
#11 /srv/RainLoop/index.php(13): include('/srv/RainLoop/r...')
#12 {main}
[14:32:53.886][f2254d92] SMTP[NOTICE]: MailSo\Smtp\Exceptions\NegativeResponseException: 435 Unable to authenticate at present in /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php:789
Stack trace:
#0 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(670): MailSo\Smtp\SmtpClient->validateResponse(Array)
#1 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(296): MailSo\Smtp\SmtpClient->sendRequestWithCheck('Ym9ibzIxMjE=', 235, '', true)
#2 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(521): MailSo\Smtp\SmtpClient->Login('admin@***.c...', '*******', true, false)
#3 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#4 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #83, 903, false, true)
#5 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#6 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#7 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /srv/RainLoop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#10 /srv/RainLoop/rainloop/v/1.10.5.192/include.php(225): include('/srv/RainLoop/r...')
#11 /srv/RainLoop/index.php(13): include('/srv/RainLoop/r...')
#12 {main}

Next MailSo\Smtp\Exceptions\LoginBadCredentialsException: 435 Unable to authenticate at present in /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php:301
Stack trace:
#0 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(521): MailSo\Smtp\SmtpClient->Login('admin@***.c...', '*******', true, false)
#1 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#2 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #83, 903, false, true)
#3 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#4 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#5 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#6 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#7 /srv/RainLoop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#8 /srv/RainLoop/rainloop/v/1.10.5.192/include.php(225): include('/srv/RainLoop/r...')
#9 /srv/RainLoop/index.php(13): include('/srv/RainLoop/r...')
#10 {main}
[14:32:53.887][f2254d92] INFO[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: 435 Unable to authenticate at present in /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php:789
Stack trace:
#0 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(670): MailSo\Smtp\SmtpClient->validateResponse(Array)
#1 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(296): MailSo\Smtp\SmtpClient->sendRequestWithCheck('Ym9ibzIxMjE=', 235, '', true)
#2 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(521): MailSo\Smtp\SmtpClient->Login('admin@***.c...', '*******', true, false)
#3 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#4 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #83, 903, false, true)
#5 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#6 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#7 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /srv/RainLoop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#10 /srv/RainLoop/rainloop/v/1.10.5.192/include.php(225): include('/srv/RainLoop/r...')
#11 /srv/RainLoop/index.php(13): include('/srv/RainLoop/r...')
#12 {main}

Next MailSo\Smtp\Exceptions\LoginBadCredentialsException: 435 Unable to authenticate at present in /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php:301
Stack trace:
#0 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(521): MailSo\Smtp\SmtpClient->Login('admin@***.c...', '*******', true, false)
#1 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#2 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #83, 903, false, true)
#3 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#4 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#5 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#6 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#7 /srv/RainLoop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#8 /srv/RainLoop/rainloop/v/1.10.5.192/include.php(225): include('/srv/RainLoop/r...')
#9 /srv/RainLoop/index.php(13): include('/srv/RainLoop/r...')
#10 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php:6309
Stack trace:
#0 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #83, 903, false, true)
#1 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#2 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#3 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#4 /srv/RainLoop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#5 /srv/RainLoop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#6 /srv/RainLoop/rainloop/v/1.10.5.192/include.php(225): include('/srv/RainLoop/r...')
#7 /srv/RainLoop/index.php(13): include('/srv/RainLoop/r...')
#8 {main}
[14:32:53.887][f2254d92] AJAX[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1037}
[14:32:53.887][f2254d92] SMTP[DATA]: > QUIT\r\n
[14:32:53.887][f2254d92] SMTP[DATA]: < 221 ubuntu-***closing connection\r\n
[14:32:53.888][f2254d92] SMTP[NOTE]: Disconnected from "tcp://mail.***.com:25" (success)
[14:32:53.889][f2254d92] IMAP[DATA]: > TAG2 LOGOUT\r\n
[14:32:53.890][f2254d92] IMAP[DATA]: < * BYE Courier-IMAP server shutting down\r\n
[14:32:53.890][f2254d92] IMAP[DATA]: < TAG2 OK LOGOUT completed\r\n
[14:32:53.890][f2254d92] IMAP[NOTE]: Disconnected from "tcp://mail.***.com:143" (success)
[14:32:53.890][f2254d92] INFO[MEMORY]: Memory peak usage: 2MB
[14:32:53.890][f2254d92] INFO[TIME]: Time delta: 1.0413198471069
```
```

**Comment by bobalo2** [comment]
This was solved and was not RainLoop's issue to begin with. 
Problem was inside the permissions of /var/run/courier/authdaemon/ which were set to 750 and required 755. It seems those perms are returning back to 750 after reboot but you can prevent that by modifying file in /etc/init.d/courier-authdaemon where there is this line (around 39): mkdir -m 0750 $rundir , which you change into mkdir -m 0755 $rundir . Worked wonders.

**Comment by ervee** [comment]
Thanks for the info, could help others! 

Ps: You can close the issue yourself ;-)
