### ISSUE TITLE
Authentication failed on sending a mail

### ISSUE THREAD

**Issue by xxvirusxx6767** [RainLoop/rainloop-webmail#1389]
I can login and receiving mails with no problem
but when I want to send a new message it gives me "Authentication failed"

My log file:

`
[17:04:16.432][dfe5d1ed] INFO[DATA]: [DATE:02.04.17][OFFSET:-00][RL:1.10.5.192][PHP:5.6.30-0+deb8u1][IP:108.162.229.137][PID:26626][nginx/1.6.2][fpm-fcgi]
[17:04:16.433][dfe5d1ed] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[17:04:16.433][dfe5d1ed] REQUEST[NOTE]: [POST] https://0network.fr/rainloop/?/Ajax/&q[]=/_LzNy40UifXmpCXF5p13UsJGyUNCMRQeF9FMaxUsBQycazI-GH-9ubNqmbxGqwDorU7Kf-8zzMxbBZ-Jumyqw5hyNaneIDJz82yp60Nh0NB2H3oYtsepmsr0FZ3eR7Esq2kOD5G1CZt0gSkqaPnXr0iidq8eqa_AJWRFnu3N9kkU3Pqai4XQ35NtihBXBe6j5iM-hZ41pOzqV7lX93DWM4C58jVqNFNLMGkOzcb-UbVQbWTPUDac5rj81k0DrhvzDGa7gQdsx71OQK6YLiW2iNiG9Mw_GLBoFBGfjx64nZchTxemsyk2PjrucZ4NiH66aYwyJhtikFQtWBSwBQrciANYBKGvbUI1q0fthrIbOrjKP4KvWGRkPJQAdbnzU3biQE2tj955RwcO5q2OQBHr6Nw/
[17:04:16.435][dfe5d1ed] AJAX[NOTE]: Action: DoSaveMessage
[17:04:16.435][dfe5d1ed] POST[DATA]: {"IdentityID":"","MessageFolder":"Drafts","MessageUid":"2","DraftFolder":"Drafts","To":"hfjjhjfd@gmail.com","Cc":"","Bcc":"","ReplyTo":"","Subject":"test","TextIsHtml":"1","Text":"<div data-html-editor-font-wrapper=\"true\" style=\"font-family: arial, sans-serif; font-size: 13px;\"><signature><\/signature><br \/>testtesttesttest<\/div>","DraftInfo":"","InReplyTo":"","References":"","MarkAsImportant":"0","Action":"SaveMessage","XToken":"7ef7cae618aacf6faae43cfed0af2c05"}
[17:04:16.447][dfe5d1ed] IMAP[NOTE]: Start connection to "tcp://mail.0network.fr:143"
[17:04:16.448][dfe5d1ed] IMAP[NOTE]: Connected (success)
[17:04:16.448][dfe5d1ed] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n
[17:04:16.448][dfe5d1ed] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[17:04:16.448][dfe5d1ed] IMAP[DATA]: < + \r\n
[17:04:16.449][dfe5d1ed] IMAP[SECURE]: > *******\r\n
[17:04:16.452][dfe5d1ed] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE] Logged in\r\n
[17:04:16.463][dfe5d1ed] IMAP[DATA]: > TAG2 APPEND "Drafts" (\Seen) {938}\r\n
[17:04:16.464][dfe5d1ed] IMAP[DATA]: < + OK\r\n
[17:04:16.464][dfe5d1ed] IMAP[NOTE]: Write to connection stream
[17:04:16.464][dfe5d1ed] IMAP[DATA]: > \r\n
[17:04:16.742][dfe5d1ed] IMAP[DATA]: < TAG2 OK [APPENDUID 1491043137 3] Append completed.\r\n
[17:04:16.743][dfe5d1ed] IMAP[DATA]: > TAG3 SELECT "Drafts"\r\n
[17:04:16.744][dfe5d1ed] IMAP[DATA]: < * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)\r\n
[17:04:16.744][dfe5d1ed] IMAP[DATA]: < * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.\r\n
[17:04:16.745][dfe5d1ed] IMAP[DATA]: < * 2 EXISTS\r\n
[17:04:16.745][dfe5d1ed] IMAP[DATA]: < * 1 RECENT\r\n
[17:04:16.745][dfe5d1ed] IMAP[DATA]: < * OK [UIDVALIDITY 1491043137] UIDs valid\r\n
[17:04:16.745][dfe5d1ed] IMAP[DATA]: < * OK [UIDNEXT 4] Predicted next UID\r\n
[17:04:16.745][dfe5d1ed] IMAP[DATA]: < * OK [HIGHESTMODSEQ 6] Highest\r\n
[17:04:16.745][dfe5d1ed] IMAP[DATA]: < TAG3 OK [READ-WRITE] Select completed (0.001 secs).\r\n
[17:04:16.746][dfe5d1ed] IMAP[DATA]: > TAG4 UID STORE 2 +FLAGS.SILENT (\Deleted)\r\n
[17:04:16.746][dfe5d1ed] IMAP[DATA]: < TAG4 OK Store completed.\r\n
[17:04:16.746][dfe5d1ed] IMAP[DATA]: > TAG5 CAPABILITY\r\n
[17:04:16.746][dfe5d1ed] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE\r\n
[17:04:16.747][dfe5d1ed] IMAP[DATA]: < TAG5 OK Capability completed.\r\n
[17:04:16.747][dfe5d1ed] IMAP[DATA]: > TAG6 UID EXPUNGE 2\r\n
[17:04:16.747][dfe5d1ed] IMAP[DATA]: < * 1 EXPUNGE\r\n
[17:04:16.747][dfe5d1ed] IMAP[DATA]: < TAG6 OK Expunge completed.\r\n
[17:04:16.747][dfe5d1ed] AJAX[DATA]: {"Action":"SaveMessage","Result":{"NewFolder":"Drafts","NewUid":3},"Time":331}
[17:04:16.759][dfe5d1ed] IMAP[DATA]: > TAG7 LOGOUT\r\n
[17:04:16.759][dfe5d1ed] IMAP[DATA]: < * BYE Logging out\r\n
[17:04:16.759][dfe5d1ed] IMAP[DATA]: < TAG7 OK Logout completed.\r\n
[17:04:16.759][dfe5d1ed] IMAP[NOTE]: Disconnected from "tcp://mail.0network.fr:143" (success)
[17:04:16.759][dfe5d1ed] INFO[MEMORY]: Memory peak usage: 5.5MB
[17:04:16.759][dfe5d1ed] INFO[TIME]: Time delta: 0.34323191642761

[17:04:16.878][1f052e7a] INFO[DATA]: [DATE:02.04.17][OFFSET:-00][RL:1.10.5.192][PHP:5.6.30-0+deb8u1][IP:108.162.229.137][PID:23527][nginx/1.6.2][fpm-fcgi]
[17:04:16.878][1f052e7a] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[17:04:16.878][1f052e7a] REQUEST[NOTE]: [POST] https://0network.fr/rainloop/?/Ajax/&q[]=/_LzNy40UifXmpCXF5p13UsJGyUNCMRQeF9FMaxUsBQycazI-GH-9ubNqmbxGqwDorU7Kf-8zzMxbBZ-Jumyqw5hyNaneIDJz82yp60Nh0NB2H3oYtsepmsr0FZ3eR7Esq2kOD5G1CZt0gSkqaPnXr0iidq8eqa_AJWRFnu3N9kkU3Pqai4XQ35NtihBXBe6j5iM-hZ41pOzqV7lX93DWM4C58jVqNFNLMGkOzcb-UbVQbWTPUDac5rj81k0DrhvzDGa7gQdsx71OQK6YLiW2iNiG9Mw_GLBoFBGfjx64nZchTxemsyk2PjrucZ4NiH66aYwyJhtikFQtWBSwBQrciANYBKGvbUI1q0fthrIbOrjKP4KvWGRkPJQAdbnzU3biQE2tj955RwcO5q2OQBHr6Nw/
[17:04:16.881][1f052e7a] AJAX[NOTE]: Action: DoFolderInformation
[17:04:16.881][1f052e7a] POST[DATA]: {"Folder":"Drafts","FlagsUids":"","UidNext":"","Action":"FolderInformation","XToken":"7ef7cae618aacf6faae43cfed0af2c05"}
[17:04:16.892][1f052e7a] IMAP[NOTE]: Start connection to "tcp://mail.0network.fr:143"
[17:04:16.892][1f052e7a] IMAP[NOTE]: Connected (success)
[17:04:16.892][1f052e7a] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n
[17:04:16.893][1f052e7a] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[17:04:16.893][1f052e7a] IMAP[DATA]: < + \r\n
[17:04:16.894][1f052e7a] IMAP[SECURE]: > *******\r\n
[17:04:16.898][1f052e7a] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE] Logged in\r\n
[17:04:16.898][1f052e7a] IMAP[DATA]: > TAG2 CAPABILITY\r\n
[17:04:16.899][1f052e7a] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE\r\n
[17:04:16.899][1f052e7a] IMAP[DATA]: < TAG2 OK Capability completed.\r\n
[17:04:16.899][1f052e7a] IMAP[DATA]: > TAG3 STATUS "Drafts" (MESSAGES UNSEEN UIDNEXT HIGHESTMODSEQ)\r\n
[17:04:16.900][1f052e7a] IMAP[DATA]: < * STATUS Drafts (MESSAGES 1 UIDNEXT 4 UNSEEN 0 HIGHESTMODSEQ 8)\r\n
[17:04:16.900][1f052e7a] IMAP[DATA]: < TAG3 OK Status completed.\r\n
[17:04:16.900][1f052e7a] AJAX[DATA]: {"Action":"FolderInformation","Result":{"Folder":"Drafts","Hash":"52936981cc3ca92122a5343b34b8fe35","MessageCount":1,"MessageUnseenCount":0,"UidNext":"4","Flags":[],"HighestModSeq":"8","NewMessages":[],"Version":"1.10.5.192"},"Time":41}
[17:04:16.906][1f052e7a] IMAP[DATA]: > TAG4 LOGOUT\r\n
[17:04:16.907][1f052e7a] IMAP[DATA]: < * BYE Logging out\r\n
[17:04:16.907][1f052e7a] IMAP[DATA]: < TAG4 OK Logout completed.\r\n
[17:04:16.907][1f052e7a] IMAP[NOTE]: Disconnected from "tcp://mail.0network.fr:143" (success)
[17:04:16.907][1f052e7a] INFO[MEMORY]: Memory peak usage: 4MB
[17:04:16.907][1f052e7a] INFO[TIME]: Time delta: 0.047842979431152

[17:04:19.727][c8283608] INFO[DATA]: [DATE:02.04.17][OFFSET:-00][RL:1.10.5.192][PHP:5.6.30-0+deb8u1][IP:108.162.229.137][PID:22314][nginx/1.6.2][fpm-fcgi]
[17:04:19.727][c8283608] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[17:04:19.727][c8283608] REQUEST[NOTE]: [POST] https://0network.fr/rainloop/?/Ajax/&q[]=/_LzNy40UifXmpCXF5p13UsJGyUNCMRQeF9FMaxUsBQycazI-GH-9ubNqmbxGqwDorU7Kf-8zzMxbBZ-Jumyqw5hyNaneIDJz82yp60Nh0NB2H3oYtsepmsr0FZ3eR7Esq2kOD5G1CZt0gSkqaPnXr0iidq8eqa_AJWRFnu3N9kkU3Pqai4XQ35NtihBXBe6j5iM-hZ41pOzqV7lX93DWM4C58jVqNFNLMGkOzcb-UbVQbWTPUDac5rj81k0DrhvzDGa7gQdsx71OQK6YLiW2iNiG9Mw_GLBoFBGfjx64nZchTxemsyk2PjrucZ4NiH66aYwyJhtikFQtWBSwBQrciANYBKGvbUI1q0fthrIbOrjKP4KvWGRkPJQAdbnzU3biQE2tj955RwcO5q2OQBHr6Nw/
[17:04:19.731][c8283608] AJAX[NOTE]: Action: DoSendMessage
[17:04:19.731][c8283608] POST[DATA]: {"IdentityID":"","MessageFolder":"Drafts","MessageUid":"3","SentFolder":"Sent","To":"hfjjhjfd@gmail.com","Cc":"","Bcc":"","ReplyTo":"","Subject":"test","TextIsHtml":"1","Text":"<div data-html-editor-font-wrapper=\"true\" style=\"font-family: arial, sans-serif; font-size: 13px;\"><signature><\/signature><br \/>testtesttesttest<\/div>","DraftInfo":"","InReplyTo":"","References":"","Dsn":"0","ReadReceiptRequest":"0","MarkAsImportant":"0","Action":"SendMessage","XToken":"7ef7cae618aacf6faae43cfed0af2c05"}
[17:04:19.743][c8283608] IMAP[NOTE]: Start connection to "tcp://mail.0network.fr:143"
[17:04:19.743][c8283608] IMAP[NOTE]: Connected (success)
[17:04:19.743][c8283608] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n
[17:04:19.744][c8283608] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[17:04:19.744][c8283608] IMAP[DATA]: < + \r\n
[17:04:19.745][c8283608] IMAP[SECURE]: > *******\r\n
[17:04:19.747][c8283608] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE] Logged in\r\n
[17:04:19.756][c8283608] SMTP[NOTE]: Start connection to "tcp://mail.0network.fr:25"
[17:04:19.757][c8283608] SMTP[NOTE]: Connected (success)
[17:04:19.766][c8283608] SMTP[DATA]: < 220 mail.0network.fr ESMTP Postfix (Debian/GNU)\r\n
[17:04:19.767][c8283608] SMTP[DATA]: > EHLO 0network.fr\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250-mail.0network.fr\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250-PIPELINING\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250-SIZE 502400000\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250-ETRN\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250-STARTTLS\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250-8BITMIME\r\n
[17:04:19.767][c8283608] SMTP[DATA]: < 250 DSN\r\n
[17:04:19.768][c8283608] SMTP[NOTICE]: exception 'MailSo\Smtp\Exceptions\LoginBadMethodException' with message 'MailSo-Smtp-Exceptions-LoginBadMethodException (SmtpClient.php ~ 309)' in /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php:309
Stack trace:
#0 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(521): MailSo\Smtp\SmtpClient->Login('julien.knoell@0...', 'D2zm35yZD2zm35y...', true, false)
#1 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#2 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #85, 938, false, true)
#3 [internal function]: RainLoop\Actions->DoSendMessage()
#4 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#5 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#6 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#7 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#10 /var/www/html/rainloop/rainloop/v/1.10.5.192/include.php(225): include('/var/www/html/r...')
#11 /var/www/html/rainloop/index.php(13): include('/var/www/html/r...')
#12 {main}
[17:04:19.768][c8283608] INFO[ERROR]: exception 'MailSo\Smtp\Exceptions\LoginBadMethodException' with message 'MailSo-Smtp-Exceptions-LoginBadMethodException (SmtpClient.php ~ 309)' in /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php:309
Stack trace:
#0 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(521): MailSo\Smtp\SmtpClient->Login('julien.knoell@0...', 'D2zm35yZD2zm35y...', true, false)
#1 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#2 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #85, 938, false, true)
#3 [internal function]: RainLoop\Actions->DoSendMessage()
#4 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#5 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#6 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#7 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#10 /var/www/html/rainloop/rainloop/v/1.10.5.192/include.php(225): include('/var/www/html/r...')
#11 /var/www/html/rainloop/index.php(13): include('/var/www/html/r...')
#12 {main}

Next exception 'RainLoop\Exceptions\ClientException' with message 'AuthError[102]' in /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php:6309
Stack trace:
#0 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #85, 938, false, true)
#1 [internal function]: RainLoop\Actions->DoSendMessage()
#2 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#3 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#4 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#5 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#6 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#7 /var/www/html/rainloop/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#8 /var/www/html/rainloop/rainloop/v/1.10.5.192/include.php(225): include('/var/www/html/r...')
#9 /var/www/html/rainloop/index.php(13): include('/var/www/html/r...')
#10 {main}
[17:04:19.768][c8283608] AJAX[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":60}
[17:04:19.768][c8283608] SMTP[DATA]: > QUIT\r\n
[17:04:19.769][c8283608] SMTP[DATA]: < 221 2.0.0 Bye\r\n
[17:04:19.769][c8283608] SMTP[NOTE]: Disconnected from "tcp://mail.0network.fr:25" (success)
[17:04:19.776][c8283608] IMAP[DATA]: > TAG2 LOGOUT\r\n
[17:04:19.776][c8283608] IMAP[DATA]: < * BYE Logging out\r\n
[17:04:19.776][c8283608] IMAP[DATA]: < TAG2 OK Logout completed.\r\n
[17:04:19.776][c8283608] IMAP[NOTE]: Disconnected from "tcp://mail.0network.fr:143" (success)
[17:04:19.776][c8283608] INFO[MEMORY]: Memory peak usage: 5.5MB
[17:04:19.776][c8283608] INFO[TIME]: Time delta: 0.068706035614014

[17:04:19.885][b78e98db] INFO[DATA]: [DATE:02.04.17][OFFSET:-00][RL:1.10.5.192][PHP:5.6.30-0+deb8u1][IP:108.162.229.137][PID:26626][nginx/1.6.2][fpm-fcgi]
[17:04:19.886][b78e98db] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[17:04:19.886][b78e98db] REQUEST[NOTE]: [POST] https://0network.fr/rainloop/?/Ajax/&q[]=/_LzNy40UifXmpCXF5p13UsJGyUNCMRQeF9FMaxUsBQycazI-GH-9ubNqmbxGqwDorU7Kf-8zzMxbBZ-Jumyqw5hyNaneIDJz82yp60Nh0NB2H3oYtsepmsr0FZ3eR7Esq2kOD5G1CZt0gSkqaPnXr0iidq8eqa_AJWRFnu3N9kkU3Pqai4XQ35NtihBXBe6j5iM-hZ41pOzqV7lX93DWM4C58jVqNFNLMGkOzcb-UbVQbWTPUDac5rj81k0DrhvzDGa7gQdsx71OQK6YLiW2iNiG9Mw_GLBoFBGfjx64nZchTxemsyk2PjrucZ4NiH66aYwyJhtikFQtWBSwBQrciANYBKGvbUI1q0fthrIbOrjKP4KvWGRkPJQAdbnzU3biQE2tj955RwcO5q2OQBHr6Nw/
[17:04:19.889][b78e98db] AJAX[NOTE]: Action: DoFolderInformation
[17:04:19.889][b78e98db] POST[DATA]: {"Folder":"Drafts","FlagsUids":"","UidNext":"","Action":"FolderInformation","XToken":"7ef7cae618aacf6faae43cfed0af2c05"}
[17:04:19.901][b78e98db] IMAP[NOTE]: Start connection to "tcp://mail.0network.fr:143"
[17:04:19.901][b78e98db] IMAP[NOTE]: Connected (success)
[17:04:19.902][b78e98db] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n
[17:04:19.902][b78e98db] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[17:04:19.902][b78e98db] IMAP[DATA]: < + \r\n
[17:04:19.903][b78e98db] IMAP[SECURE]: > *******\r\n
[17:04:19.906][b78e98db] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE] Logged in\r\n
[17:04:19.907][b78e98db] IMAP[DATA]: > TAG2 CAPABILITY\r\n
[17:04:19.907][b78e98db] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE\r\n
[17:04:19.907][b78e98db] IMAP[DATA]: < TAG2 OK Capability completed.\r\n
[17:04:19.907][b78e98db] IMAP[DATA]: > TAG3 STATUS "Drafts" (MESSAGES UNSEEN UIDNEXT HIGHESTMODSEQ)\r\n
[17:04:19.968][b78e98db] IMAP[DATA]: < * STATUS Drafts (MESSAGES 1 UIDNEXT 4 UNSEEN 0 HIGHESTMODSEQ 8)\r\n
[17:04:19.969][b78e98db] IMAP[DATA]: < TAG3 OK Status completed.\r\n
[17:04:19.969][b78e98db] AJAX[DATA]: {"Action":"FolderInformation","Result":{"Folder":"Drafts","Hash":"52936981cc3ca92122a5343b34b8fe35","MessageCount":1,"MessageUnseenCount":0,"UidNext":"4","Flags":[],"HighestModSeq":"8","NewMessages":[],"Version":"1.10.5.192"},"Time":110}
[17:04:19.979][b78e98db] IMAP[DATA]: > TAG4 LOGOUT\r\n
[17:04:19.980][b78e98db] IMAP[DATA]: < * BYE Logging out\r\n
[17:04:19.980][b78e98db] IMAP[DATA]: < TAG4 OK Logout completed.\r\n
[17:04:19.980][b78e98db] IMAP[NOTE]: Disconnected from "tcp://mail.0network.fr:143" (success)
[17:04:19.980][b78e98db] INFO[MEMORY]: Memory peak usage: 4MB
[17:04:19.980][b78e98db] INFO[TIME]: Time delta: 0.12114405632019
`

if I goes into other webmail like virtualmin I can send mails with no problem ...

thanks,

**Comment by RainLoop** [comment]
It seems you should enable STARTTLS from SMTP connection

**Comment by xxvirusxx6767** [comment]
I had not seen his, thank you for your answer, the problem is solved
