### ISSUE TITLE
cannot login after upgrade to 1.11.0.203

### ISSUE THREAD

**Issue by simbalion** [RainLoop/rainloop-webmail#1406]
**RainLoop version, browser, OS:**
Debian Jessie, Rainloop 1.11.0.203

**Expected behavior and actual behavior:**
Cannot login, tested credentials using thunderbird and they work. Logins used to work, prior to updating to 1.11.0.203

**Steps to reproduce the problem:**
upgraded from 1.10.3.151 to 1.11.0.203, followed the instructions on the rainloop website, however this is the only server experiencing this issue, I did this same upgrade on a dozen servers and all of the others are working. I have not modified any of the rainloop files, and I carried over my config file from the previous version.

**Logs or screenshots:**
[18:50:40.264][cc0e75a6] INFO[DATA]: [DATE:21.04.17][OFFSET:-00][RL:1.11.0.203][PHP:5.6.30-0+deb8u1][IP:redactedIPAddress][PID:24075][nginx/1.10.3][fpm-fcgi]
[18:50:40.266][cc0e75a6] INFO[DATA]: [Suhosin:off][APC:on][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[18:50:40.266][cc0e75a6] REQUEST[NOTE]: [POST] https://rl.userdomain.com/?/Ajax/&q[]=/0/
[18:50:40.267][cc0e75a6] AJAX[NOTE]: Action: DoLogin
[18:50:40.267][cc0e75a6] POST[DATA]: {"Email":"useraccount@userdomain.com","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"0","Action":"Login","XToken":"f0d52be98bb28a020fa07616771ccb1a"}
[18:50:40.267][cc0e75a6] PLUGIN[NOTE]: Hook: filter.login-credentials
[18:50:40.268][cc0e75a6] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'AuthError[102]' in /var/www/rl/data/_data_/_default_/plugins/white-list/index.php:25
Stack trace:
#0 [internal function]: WhiteListPlugin->FilterLoginCredentials('useraccount...', 'useraccount...', 'redactedPassword...')
#1 /var/www/rl/rainloop/v/1.11.0.203/app/libraries/RainLoop/Plugins/Manager.php(437): call_user_func_array(Array, Array)
#2 /var/www/rl/rainloop/v/1.11.0.203/app/libraries/RainLoop/Actions.php(2239): RainLoop\Plugins\Manager->RunHook('filter.login-cr...', Array)
#3 /var/www/rl/rainloop/v/1.11.0.203/app/libraries/RainLoop/Actions.php(2379): RainLoop\Actions->LoginProcess('useraccount...', 'redactedPassword...', '', '', false)
#4 [internal function]: RainLoop\Actions->DoLogin()
#5 /var/www/rl/rainloop/v/1.11.0.203/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#6 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#7 /var/www/rl/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#8 /var/www/rl/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#9 /var/www/rl/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#10 /var/www/rl/rainloop/v/1.11.0.203/app/handle.php(94): RainLoop\Service::Handle()
#11 /var/www/rl/rainloop/v/1.11.0.203/include.php(225): include('/var/www/rl/rai...')
#12 /var/www/rl/index.php(13): include('/var/www/rl/rai...')
#13 {main}
[18:50:40.268][cc0e75a6] AJAX[DATA]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":21}
[18:50:40.278][cc0e75a6] INFO[MEMORY]: Memory peak usage: 1.25MB
[18:50:40.278][cc0e75a6] INFO[TIME]: Time delta: 0.029933929443359

**Comment by RainLoop** [comment]
Try to disable "white-list" plugin. It seems that plugin blocks your user.
