### ISSUE TITLE
Can't Login using domain gmail.com

### ISSUE THREAD

**Issue by oghuzima** [RainLoop/rainloop-webmail#1410]
i don't understand how to use localdomain, so i tried to use gmail.com domain.
always got "authentication failed"

System using Ubuntu 14.04 which rainloop already  v1.11.0.203 (12.03.2017).

UFW already open port 443, 80, 993 (IMAP SSL), 465 (SMTP SSL), STARTSSL, port 25, 143 (IMAP & SMTP) 
at my google acc, i already UnlockedChapta, Allowing less secure apps to access your account

This is the logs when i tried to login using gmail : 

> 
> [11:52:18.610][2b966007] INFO[DATA]: [DATE:27.04.17][OFFSET:-00][RL:1.10.5.192][PHP:7.0.18-1+deb.sury.org~trusty+1][IP:172.28.1.40][PID:3688][Apache/2.4.25 (Ubuntu)][a$
> [11:52:18.610][2b966007] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,odbc][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
> [11:52:18.610][2b966007] REQUEST[NOTE]: [GET] http://172.28.1.155/
> [11:52:18.657][2b966007] INFO[MEMORY]: Memory peak usage: 4MB
> [11:52:18.657][2b966007] INFO[TIME]: Time delta: 0.21340203285217
> 
> [11:52:18.836][bcda9101] INFO[DATA]: [DATE:27.04.17][OFFSET:-00][RL:1.10.5.192][PHP:7.0.18-1+deb.sury.org~trusty+1][IP:172.28.1.40][PID:3688][Apache/2.4.25 (Ubuntu)][a$
> [11:52:18.836][bcda9101] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,odbc][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
> [11:52:18.836][bcda9101] REQUEST[NOTE]: [GET] http://172.28.1.155/?/AppData@no-mobile-0/0/1771053437325354/
> [11:52:18.838][bcda9101] APPDATA[DATA]: if(window.__initAppData){window.__initAppData({"Auth":false,"AccountHash":"","AccountSignMe":false,"AuthAccountHash":"","MailTo$
> [11:52:18.840][bcda9101] INFO[MEMORY]: Memory peak usage: 2MB
> [11:52:18.840][bcda9101] INFO[TIME]: Time delta: 0.016274929046631
> 
> [11:52:26.347][d5341ea9] INFO[DATA]: [DATE:27.04.17][OFFSET:-00][RL:1.10.5.192][PHP:7.0.18-1+deb.sury.org~trusty+1][IP:172.28.1.40][PID:3689][Apache/2.4.25 (Ubuntu)][a$
> [11:52:26.347][d5341ea9] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,odbc][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
> [11:52:26.347][d5341ea9] REQUEST[NOTE]: [POST] http://172.28.1.155/?/Ajax/&q[]=/0/
> [11:52:26.348][d5341ea9] AJAX[NOTE]: Action: DoLogin
> [11:52:26.348][d5341ea9] POST[DATA]: {"Email":"xxx@gmail.com","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","Si$
> [11:52:26.358][d5341ea9] IMAP[NOTE]: Start connection to "ssl://imap.gmail.com:993"
> [11:52:26.495][d5341ea9] IMAP[NOTE]: Connected (success)
> [11:52:26.699][d5341ea9] IMAP[DATA]: < * OK Gimap ready for requests from 180.250.241.193 m15mb20469412oig\r\n
> [11:52:26.700][d5341ea9] IMAP[DATA]: > TAG1 CAPABILITY\r\n
> [11:52:26.931][d5341ea9] IMAP[DATA]: < * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLA$
> [11:52:26.932][d5341ea9] IMAP[DATA]: < TAG1 OK Thats all she wrote! m15mb20469412oig\r\n
> [11:52:26.935][d5341ea9] IMAP[DATA]: > TAG2 AUTHENTICATE PLAIN\r\n
> [11:52:27.179][d5341ea9] IMAP[DATA]: < + \r\n
> [11:52:27.182][d5341ea9] IMAP[SECURE]: > *******\r\n
> [11:52:27.708][d5341ea9] IMAP[DATA]: < * NO [WEBALERT https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbt3Y72jKrYZ1wcYYbTLbc9jEj2k5IdmZRBEQFXM1gicGrfA$
> [11:52:27.709][d5341ea9] IMAP[DATA]: < TAG2 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)\r\n
> [11:52:27.712][d5341ea9] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1874) in /$
> Stack trace:
> #0 /var/www/rainloop/rainloop/v/1.10.5.192/app/libraries/MailSo/Imap/ImapClient.php(1951): MailSo\Imap\ImapClient->validateResponse(Array)
> #1 /var/www/rainloop/rainloop/v/1.10.5.192/app/libraries/MailSo/Imap/ImapClient.php(281): MailSo\Imap\ImapClient->parseResponseWithValidation()
> #2 /var/www/rainloop/rainloop/v/1.10.5.192/app/libraries/MailSo/Mail/MailClient.php(92): MailSo\Imap\ImapClient->Login('xxx@gm...', '*******', '', true, false)
> #3 /var/www/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(451): MailSo\Mail\MailClient->Login('xxx@gm...', '*******', '', true, fals$
> #4 /var/www/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(2082): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager),$
> #5 /var/www/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(2323): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
> #6 /var/www/rainloop/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(2376): RainLoop\Actions->LoginProcess('xxx@gm...', '*******', 'd40029ee3c352da..$
>

**Comment by dmessina79** [comment]
Ensure that the IP address of your server is was not blocked here:

https://myaccount.google.com/device-activity

**Comment by timmi-on-rails** [comment]
This line here:
```
[11:52:27.709][d5341ea9] IMAP[DATA]: < TAG2 NO [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure)\r\n
```
If you follow the link and read at the end of the text, you'll find the following link:
https://www.google.com/accounts/DisplayUnlockCaptcha
I was logged in with the browser at google, when I clicked the link. I followed the instructions and then it worked for me.
