### ISSUE TITLE
CantSendMessage[302] over plain smtp

### ISSUE THREAD

**Issue by amedranogil** [RainLoop/rainloop-webmail#1436]
**RainLoop version, browser, OS:**
1.10.5.192, Chrome (does not matter), windowos (does not matter)
**Expected behavior and actual behavior:**
sending email, does not send. Connection is open server answers, rainloop is unable to send message back.
**Steps to reproduce the problem:**
Configure domain with plain smtp (other configurations fall in to the same issue).
Firewall is checked, and cleared: I can telnet to the mailserver on port 25 from the rainloop machine, and send commands manually without any issue.
**Logs or screenshots:**
```
[16:07:59.976][2356ae93] SMTP[NOTE]: Start connection to "tcp://smtp.myserver.com:25"
[16:07:59.978][2356ae93] SMTP[NOTE]: Connected (success)
[16:08:00.324][2356ae93] SMTP[DATA]: < 220  - Welcome to Qmail Toaster Ver. 1.3 SMTP Server ESMTP\r\n

[16:08:07.706][ca0f508a] INFO[DATA]: [DATE:25.05.17][OFFSET:-00][RL:1.10.5.192][PHP:5.4.45-0+deb7u8][IP:138.4.10.193][PID:26629][Apache/2.2.22 (Debian)][apache2handler]
[16:08:07.706][ca0f508a] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls]

IMAP LOGS (IMAP IS WORKING correctly)

[16:09:00.363][2356ae93] SMTP[ERROR]: exception 'MailSo\Net\Exceptions\SocketReadTimeoutException' with message 'MailSo-Net-Exceptions-SocketReadTimeoutException (NetClient.php ~ 506)' in /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/MailSo/Net/NetClient.php:506
Stack trace:
#0 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(781): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(170): MailSo\Smtp\SmtpClient->validateResponse(220)
#2 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(503): MailSo\Smtp\SmtpClient->Connect('smtp.myserver.com...', 25, 'myserver.com...', 0, false, true)
#3 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#4 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #85, 1380, false, true)
#5 [internal function]: RainLoop\Actions->DoSendMessage()
#6 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#7 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#8 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#9 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#10 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#11 /var/www/webmail/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#12 /var/www/webmail/rainloop/v/1.10.5.192/include.php(225): include('/var/www/webmai...')
#13 /var/www/webmail/index.php(13): include('/var/www/webmai...')
#14 {main}
[16:09:00.364][2356ae93] INFO[ERROR]: exception 'MailSo\Net\Exceptions\SocketReadTimeoutException' with message 'MailSo-Net-Exceptions-SocketReadTimeoutException (NetClient.php ~ 506)' in /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/MailSo/Net/NetClient.php:506
Stack trace:
#0 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(781): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/MailSo/Smtp/SmtpClient.php(170): MailSo\Smtp\SmtpClient->validateResponse(220)
#2 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Model/Account.php(503): MailSo\Smtp\SmtpClient->Connect('smtp.myserver.com...', 25, 'myserver.com...', 0, false, true)
#3 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6210): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#4 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php(6368): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #85, 1380, false, true)
#5 [internal function]: RainLoop\Actions->DoSendMessage()
#6 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#7 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#8 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#9 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#10 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#11 /var/www/webmail/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#12 /var/www/webmail/rainloop/v/1.10.5.192/include.php(225): include('/var/www/webmai...')
#13 /var/www/webmail/index.php(13): include('/var/www/webmai...')
#14 {main}

Next exception 'RainLoop\Exceptions\ClientException' with message 'CantSendMessage[302]' in /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Actions.php:6477
Stack trace:
#0 [internal function]: RainLoop\Actions->DoSendMessage()
#1 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#2 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#3 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#4 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#5 /var/www/webmail/rainloop/v/1.10.5.192/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#6 /var/www/webmail/rainloop/v/1.10.5.192/app/handle.php(94): RainLoop\Service::Handle()
#7 /var/www/webmail/rainloop/v/1.10.5.192/include.php(225): include('/var/www/webmai...')
#8 /var/www/webmail/index.php(13): include('/var/www/webmai...')
#9 {main}
[16:09:00.364][2356ae93] AJAX[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":302,"ErrorMessage":"","ErrorMessageAdditional":"","Time":60558}
[16:09:00.364][2356ae93] SMTP[NOTE]: Disconnected from "tcp://smtp.myserver.com:25" (success)

```

**Comment by RainLoop** [comment]
Wow, thanks! It was a bug.

**Comment by amedranogil** [comment]
replaced the changed file in the deployed installation and it works, also StartTSL which also had problems.
