### ISSUE TITLE
Rainloop is not able to connect so Sieve via PLAIN AUTH

### ISSUE THREAD

**Issue by akmet** [RainLoop/rainloop-webmail#1461]
**RainLoop version, browser, OS:**
RainLoop 1.11.0.203, Chrome 59, Firefox, Win10, dovecot 2.2

**Expected behavior and actual behavior:**
Rainloop is not able to authenticate on dovecot's sieve, so I am not able to view / edit them.

**Steps to reproduce the problem:**
Go to Settings->Filters then there is an error message "Die Filter sind nicht verfügbar" (Filters are not available)

**Logs or screenshots:**
[09:59:15.398][35f085d1] SIEVE[DATA]: < OK "Dovecot ready."\r\n
[09:59:15.398][35f085d1] SIEVE[TIME]: 0.00040793418884277
[09:59:15.398][35f085d1] SIEVE[DATA]: > AUTHENTICATE "PLAIN" {40+}\r\n
[09:59:15.398][35f085d1] SIEVE[DATA]: > CORRECT_AUTH_KEY=\r\n
[09:59:15.398][35f085d1] SIEVE[DATA]: < NO "Error in MANAGESIEVE command received by server."\r\n
[09:59:15.399][35f085d1] SIEVE[TIME]: 5.8174133300781E-5
[09:59:15.399][35f085d1] SIEVE[WARNING]: exception 'MailSo\Sieve\Exceptions\NegativeResponseException' with message 'MailSo-Sieve-Exceptions-NegativeResponseException (ManageSieveClient.php ~ 615)' in /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/MailSo/Sieve/ManageSieveClient.php:615
Stack trace:
#0 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/MailSo/Sieve/ManageSieveClient.php(175): MailSo\Sieve\ManageSieveClient->validateResponse(Array)
#1 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/Model/Account.php(570): MailSo\Sieve\ManageSieveClient->Login('USER', 'PASS')
#2 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/Providers/Filters/SieveStorage.php(64): RainLoop\Model\Account->SieveConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Sieve\ManageSieveClient), Object(RainLoop\Config\Application))
#3 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/Providers/Filters.php(30): RainLoop\Providers\Filters\SieveStorage->Load(Object(RainLoop\Model\Account), true)
#4 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/Actions.php(2778): RainLoop\Providers\Filters->Load(Object(RainLoop\Model\Account), true)
#5 [internal function]: RainLoop\Actions->DoFilters()
#6 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/ServiceActions.php(172): call_user_func(Array)
#7 [internal function]: RainLoop\ServiceActions->ServiceAjax('')
#8 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(146): call_user_func(Array, '')
#9 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#10 /var/www/webmail/rainloop/v/1.11.0.203/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#11 /var/www/webmail/rainloop/v/1.11.0.203/app/handle.php(94): RainLoop\Service::Handle()
#12 /var/www/webmail/rainloop/v/1.11.0.203/include.php(225): include('/var/www/webmai...')
#13 /var/www/webmail/index.php(13): include('/var/www/webmai...')
#14 {main}

I connected via telnet to the server with the same way of authentication and it states the same error. But when I send the Request at once ($this->sendRequest('AUTHENTICATE "PLAIN" "'.$sAuth); ) everything runs as expected.

**Comment by Fazik** [comment]
Faced the same issue after recent updates of dovecot/pigeonhole/rainloop
Not sure what caused this issue.

**Comment by M66B** [comment]
Same problem in version 1.11.1:

```
[11:15:17.981][491db00d] SIEVE[DATA]: < NO "Error in MANAGESIEVE command received by server."\r\n
[11:15:17.982][491db00d] SIEVE[WARNING]: exception 'MailSo\Sieve\Exceptions\NegativeResponseException' with message 'MailSo-Sieve-Exceptions-NegativeResponseException (ManageSieveClient.php ~ 613)' in .../rainloop/v/1.11.1/app/libraries/MailSo/Sieve/ManageSieveClient.php:613
Stack trace:
#0 .../rainloop/v/1.11.1/app/libraries/MailSo/Sieve/ManageSieveClient.php(173): MailSo\Sieve\ManageSieveClient->validateResponse(Array)
```

**Comment by HiTm4n** [comment]
Hi, I still have the same problem. It seems the fix didn't fix it...

**Comment by HiTm4n** [comment]
`Mar 22 15:51:27 mail dovecot: managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.1.1, TLS, session=<jd1AcQFoPqh/AAAB>`
