### ISSUE TITLE
Authentication failed with ldap user login

### ISSUE THREAD

**Issue by yiminfantw** [RainLoop/rainloop-webmail#1541]
**RainLoop version, browser, OS:**
1.11.3, Chrome, Ubuntu 16.04

**Expected behavior and actual behavior:**
LDAP(JumpCloud LDAP service) user is not able to log in and encountered **Authentication failed** error. 

**Steps to reproduce the problem:**
I installed Modoboa mail server on Linode with Ubuntu 16.04 and configured it to authenticate users from external LDAP. After that, I installed RainLoop on the same host. I can log in as admin and I made my domain settings look like this: 
![screen shot 2017-10-18 at 11 42 46 pm](https://user-images.githubusercontent.com/32536801/31757507-1d16c182-b45e-11e7-9b72-f3b5be2e1106.png)

Logging out admin and logging in with a LDAP user, I got **Authentication failed** error. Enabling **Use short login** doesn't work for me as well. Note that I'm able to log LDAP user in dovecot through openssl or Modoboa webmail client or even desktop client like Thunderbird.

**Logs or screenshots:**
Here is the log:
```
[06:46:26.941][3b5046ed] INFO[DATA]: [DATE:19.10.17][OFFSET:-00][RL:1.11.3][PHP:7.0.22-0ubuntu0.16.04.1][IP:70.79.37.210][PID:3719][nginx/1.10.3][fpm-fcgi]
[06:46:26.941][3b5046ed] INFO[DATA]: [Suhosin:off][APC:off][MB:off][PDO:~][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[06:46:26.941][3b5046ed] REQUEST[NOTE]: [POST] http://webmail.example.com/?/Ajax/&q[]=/0/
[06:46:26.941][3b5046ed] AJAX[NOTE]: Action: DoAdminLogin
[06:46:26.941][3b5046ed] POST[DATA]: {"Login":"user@example.com","Password":"*******","Action":"AdminLogin","XToken":"cb688c687af8a1636f55449451bb8e22"}
[06:46:27.942][3b5046ed] INFO[NOTICE]: RainLoop\Exceptions\ClientException: AuthError[102] in /var/www/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php:3831
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoAdminLogin()
#1 /var/www/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#2 /var/www/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /var/www/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /var/www/rainloop/rainloop/v/1.11.3/app/handle.php(94): RainLoop\Service::Handle()
#5 /var/www/rainloop/rainloop/v/1.11.3/include.php(228): include('/var/www/rainlo...')
#6 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#7 {main}
[06:46:27.942][3b5046ed] AJAX[DATA]: {"Action":"AdminLogin","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1013}
[06:46:27.943][3b5046ed] INFO[MEMORY]: Memory peak usage: 2MB
[06:46:27.943][3b5046ed] INFO[TIME]: Time delta: 1.0138230323792
```
Here is the auth log:
```
[2017-10-19 06:46:27] Auth failed: ip=70.79.37.210 user=user@example.com host=webmail.example.com port=imap
```
Should the host be 127.0.0.1 and port be 993 as what I set in domain setting? I tried using external IP or host name point to mail server(i.e. mail.example.com) but didn't work. My mail server log doesn't have any record when logging to RainLoop. Any idea? Thx

FYI, I have two sites up and running on the same host: Modoboa(mail.example.com) and RainLoop(webmail.example.com).

Cheers,
YiMin

**Comment by yiminfantw** [comment]
Looks like I was trying to log in email user in the admin login page. Switching to normal user login page works. No issue anymore. Thx
