### ISSUE TITLE
Can't send a message with attachment

### ISSUE THREAD

**Issue by alvosec** [RainLoop/rainloop-webmail#1542]
This issue was tested on Ubuntu 16.04 with latest Rainloop software.

So whenever attachment is added to the message it will return: "Can't send a message"

Without attachments it works fine.

Funny thing is that, that mail with given error: "Can't send a message", will arrive into INBOX with attachment.

Local mail works fine, firewall is also checked so no idea what can cause that error.

Log says:

```
[19:01:58.639][de62bc38] SMTP[ERROR]: MailSo\Net\Exceptions\SocketReadTimeoutException: MailSo-Net-Exceptions-SocketReadTimeoutException (NetClient.php ~ 506) in /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Net/NetClient.php:506
Stack trace:
#0 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Smtp/SmtpClient.php(781): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Smtp/SmtpClient.php(670): MailSo\Smtp\SmtpClient->validateResponse(Array)
#2 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Smtp/SmtpClient.php(513): MailSo\Smtp\SmtpClient->sendRequestWithCheck('.', 250)
#3 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php(6295): MailSo\Smtp\SmtpClient->DataWithStream(Resource id #25)
#4 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php(6377): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #25, 232771, false, true)
#5 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#6 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#7 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/www/mail/public_html/rainloop/v/1.11.3/app/handle.php(94): RainLoop\Service::Handle()
#10 /var/www/mail/public_html/rainloop/v/1.11.3/include.php(228): include('/var/www/mail/p...')
#11 /var/www/mail/public_html/index.php(13): include('/var/www/mail/p...')
#12 {main}
[19:01:58.639][de62bc38] SMTP[NOTE]: Disconnected from "tcp://mail.alvosec.com:587" (success)
[19:01:58.640][de62bc38] INFO[ERROR]: MailSo\Net\Exceptions\SocketReadTimeoutException: MailSo-Net-Exceptions-SocketReadTimeoutException (NetClient.php ~ 506) in /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Net/NetClient.php:506
Stack trace:
#0 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Smtp/SmtpClient.php(781): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Smtp/SmtpClient.php(670): MailSo\Smtp\SmtpClient->validateResponse(Array)
#2 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/MailSo/Smtp/SmtpClient.php(513): MailSo\Smtp\SmtpClient->sendRequestWithCheck('.', 250)
#3 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php(6295): MailSo\Smtp\SmtpClient->DataWithStream(Resource id #25)
#4 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php(6377): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #25, 232771, false, true)
#5 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#6 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#7 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/www/mail/public_html/rainloop/v/1.11.3/app/handle.php(94): RainLoop\Service::Handle()
#10 /var/www/mail/public_html/rainloop/v/1.11.3/include.php(228): include('/var/www/mail/p...')
#11 /var/www/mail/public_html/index.php(13): include('/var/www/mail/p...')
#12 {main}

Next RainLoop\Exceptions\ClientException: CantSendMessage[302] in /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php:6486
Stack trace:
#0 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#1 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#2 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /var/www/mail/public_html/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /var/www/mail/public_html/rainloop/v/1.11.3/app/handle.php(94): RainLoop\Service::Handle()
#5 /var/www/mail/public_html/rainloop/v/1.11.3/include.php(228): include('/var/www/mail/p...')
#6 /var/www/mail/public_html/index.php(13): include('/var/www/mail/p...')
#7 {main}
[19:01:58.640][de62bc38] AJAX[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":302,"ErrorMessage":"","ErrorMessageAdditional":"","Time":60558}
```

**Comment by alvosec** [comment]
Solved it was a problem in `body_checks = regexp:/etc/postfix/body_checks`, but strangely postfix didn't complain about it. So closed.
