### ISSUE TITLE
Sieve not working

### ISSUE THREAD

**Issue by sledzik1984** [RainLoop/rainloop-webmail#1649]
[20:33:03.462][2a0211e3] POST[DATA]: {"Action":"Filters","XToken":"5ea5bfe3dbc4848766f80d47081a567a"}
[20:33:03.463][2a0211e3] SIEVE[NOTE]: Start connection to "tcp://mail.cma.pl:4190"
[20:33:03.463][2a0211e3] SIEVE[NOTE]: Connected (success)
[20:33:03.475][2a0211e3] SIEVE[DATA]: < "IMPLEMENTATION" "Dovecot Pigeonhole"\r\n
[20:33:03.475][2a0211e3] SIEVE[DATA]: < "SIEVE" ""\r\n
[20:33:03.475][2a0211e3] SIEVE[DATA]: < "NOTIFY" ""\r\n
[20:33:03.475][2a0211e3] SIEVE[DATA]: < "SASL" ""\r\n
[20:33:03.475][2a0211e3] SIEVE[DATA]: < "STARTTLS"\r\n
[20:33:03.475][2a0211e3] SIEVE[DATA]: < "VERSION" "1.0"\r\n
[20:33:03.475][2a0211e3] SIEVE[DATA]: < OK "Dovecot ready."\r\n
[20:33:03.476][2a0211e3] SIEVE[ERROR]: MailSo\Sieve\Exceptions\LoginBadMethodException: MailSo-Sieve-Exceptions-LoginBadMethodException (ManageSieveClient.php ~ 219) in /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/MailSo/Sieve/ManageSieveClient.php:219
Stack trace:
#0 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Model/Account.php(576): MailSo\Sieve\ManageSieveClient->Login('piotr.gorski@cm...', '*******')
#1 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Providers/Filters/SieveStorage.php(64): RainLoop\Model\Account->SieveConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Sieve\ManageSieveClient), Object(RainLoop\Config\Application))
#2 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Providers/Filters.php(30): RainLoop\Providers\Filters\SieveStorage->Load(Object(RainLoop\Model\Account), false)
#3 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php(2782): RainLoop\Providers\Filters->Load(Object(RainLoop\Model\Account), false)
#4 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoFilters()
#5 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#6 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#7 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#8 /var/www/html/rainloop/rainloop/v/1.11.3/app/handle.php(94): RainLoop\Service::Handle()
#9 /var/www/html/rainloop/rainloop/v/1.11.3/include.php(228): include('/var/www/html/r...')
#10 /var/www/html/rainloop/index.php(13): include('/var/www/html/r...')
#11 {main}
[20:33:03.476][2a0211e3] INFO[ERROR]: MailSo\Sieve\Exceptions\LoginBadMethodException: MailSo-Sieve-Exceptions-LoginBadMethodException (ManageSieveClient.php ~ 219) in /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/MailSo/Sieve/ManageSieveClient.php:219
Stack trace:
#0 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Model/Account.php(576): MailSo\Sieve\ManageSieveClient->Login('piotr.gorski@cm...', '*******')
#1 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Providers/Filters/SieveStorage.php(64): RainLoop\Model\Account->SieveConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Sieve\ManageSieveClient), Object(RainLoop\Config\Application))
#2 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Providers/Filters.php(30): RainLoop\Providers\Filters\SieveStorage->Load(Object(RainLoop\Model\Account), false)
#3 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php(2782): RainLoop\Providers\Filters->Load(Object(RainLoop\Model\Account), false)
#4 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoFilters()
#5 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#6 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#7 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#8 /var/www/html/rainloop/rainloop/v/1.11.3/app/handle.php(94): RainLoop\Service::Handle()
#9 /var/www/html/rainloop/rainloop/v/1.11.3/include.php(228): include('/var/www/html/r...')
#10 /var/www/html/rainloop/index.php(13): include('/var/www/html/r...')
#11 {main}

Next RainLoop\Exceptions\ClientException: CantGetFilters[352] in /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Providers/Filters.php:38
Stack trace:
#0 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Actions.php(2782): RainLoop\Providers\Filters->Load(Object(RainLoop\Model\Account), false)
#1 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoFilters()
#2 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#3 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#4 /var/www/html/rainloop/rainloop/v/1.11.3/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#5 /var/www/html/rainloop/rainloop/v/1.11.3/app/handle.php(94): RainLoop\Service::Handle()
#6 /var/www/html/rainloop/rainloop/v/1.11.3/include.php(228): include('/var/www/html/r...')
#7 /var/www/html/rainloop/index.php(13): include('/var/www/html/r...')
#8 {main}
[20:33:03.476][2a0211e3] AJAX[DATA]: {"Action":"Filters","Result":false,"ErrorCode":352,"ErrorMessage":"","ErrorMessageAdditional":"","Time":27}
[20:33:03.476][2a0211e3] SIEVE[NOTE]: Disconnected from "tcp://mail.cma.pl:4190" (success)

**Comment by sledzik1984** [comment]
Tried also development version from Git and problem is the same

**Comment by wociscz** [comment]
Do you have php-net-sieve distribution package (php extension module) installed on your server? On both of my servers this module is present and sieve working fine - with dovecot managesieve.

**Comment by minto5050** [comment]
@wociscz Does it work with PHP 7.0 ? I have installed it but i am not able to get it to work

**Comment by wociscz** [comment]
@minto5050 Hi, I don't have installed server anymore, so can't help. But if I remember correctly, with all installed modules and especially `php-net-sieve` in its proper version, there shouldn't be a problem.

**Comment by gusarg81** [comment]
Hi, I know this is old, but is not working for me either, even having installed php-net-sieve.

OS: Ubuntu 18.04 Server
Rainloop: v1.14.0
Dovecot (with sieve configured and running): v2.2.33.2

**Comment by moqmar** [comment]
Are you sure that you have the same error message? This seems to be related to STARTTLS not working correctly, but in your case STARTTLS isn't even required. I've got `"SASL" ""` in the telnet output, which seems to mean that STARTTLS is required. When enabling STARTTLS with `sieve_secure = "TLS"`, everything's working fine.

**Comment by gusarg81** [comment]
Could someone in RainLoop post the right steeps to make Sieve works? (and to make sure, even steps and settings for Dovecot) Otherwise is a useless implementation I believe.

Thanks.

**Comment by moqmar** [comment]
@gusarg81 Generally it should be working, using either `sieve_secure = "None"`, `sieve_secure = "TLS"` or `sieve_secure = "SSL"`. If not: what does `nc mail.example.org 4190` output for your server?

**Comment by gusarg81** [comment]
> @gusarg81 Generally it should be working, using either `sieve_secure = "None"`, `sieve_secure = "TLS"` or `sieve_secure = "SSL"`. If not: what does `nc mail.example.org 4190` output for your server?

The thing is that under Rainloop settings (in admin), the "test" does not give any errors, but literally filters are not working because does nothing when enabled.

> telnet mail.gdnet.ar 4190
> Trying 200.80.30.242...
> Connected to mail.gdnet.ar.
> Escape character is '^]'.
> "IMPLEMENTATION" "Dovecot (Ubuntu) Pigeonhole"
> "SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext"
> "NOTIFY" "mailto"
> "SASL" "PLAIN LOGIN"
> "STARTTLS"
> "VERSION" "1.0"
> OK "Dovecot (Ubuntu) ready."
