### ISSUE TITLE
Error synchronizing with a CardDAV server

### ISSUE THREAD

**Issue by br0kenpipe** [RainLoop/rainloop-webmail#1731]
**RainLoop 1.12.0 on Debian Stable (Stretch)**

I run a CardDAV server with Radicale. I can synchronize with all devices and software on this server, but not with Rainloop.
It only shows me a standard error "Error during contact synchronization".

```
[06:55:16.266][dca6fb6e] INFO[NOTICE]: SabreForRainLoop\DAV\Exception: **[CURL] Error while making request: Empty reply from server (error code: 52) in /var/www/rainloop/rainloop/v/1.12.0/app/libraries/SabreForRainLoop/DAV/Client.php:421**
Stack trace:
```
But I have no idea what the mistake is.

```
[06:55:16.187][dca6fb6e] INFO[DATA]: [DATE:04.07.18][OFFSET:-00][RL:1.12.0][PHP:7.0.27-0+deb9u1][IP:1.2.3.4][PID:1178][nginx/1.15.0][fpm-fcgi]
[06:55:16.187][dca6fb6e] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv2,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[06:55:16.188][dca6fb6e] REQUEST[NOTE]: [POST] https://examplemail.example.de/?/Ajax/&q[]=/_MKw79n2xZSvvmFkeCvRAF-RVin3ws9SsMTQrpcEWdQ5GX9s-6MfjVH_reJQ62Qt24nJakcnemKSbqHR6f2JWSCNbGmFBtboYd2F68pR-9V34J3taERGjohCohlSedDCNb2gdVW0xMaIU1GDkt3r4uzAFjvJv_YYLBjs7IJj-tAfPGus6JnBNkoi0UZ0r__RfMDCZvf6c1Fx1lAQF_m9bFYzX69CshBlOvQ_Tl0UFvYFF7qm5BcUrsfX6sJ9aIa28zuD0cG0tsU0ZQCo4E8l8Ooipodue10F-3cA7fWxa6AtHW4nh03DOP3dewwGZaNwL185AxXSY1nuDpx40eQzzZvtSvL0/
[06:55:16.188][dca6fb6e] AJAX[NOTE]: Action: DoContactsSync
[06:55:16.188][dca6fb6e] POST[DATA]: {"Action":"ContactsSync","XToken":"d9fcc627a2021cdb7123b59e8b65f841"}
[06:55:16.189][dca6fb6e] SQL[DATA]: SELECT value_int FROM rainloop_system WHERE sys_name = ?
[06:55:16.190][dca6fb6e] SQL[DATA]: SELECT id_user FROM rainloop_users WHERE rl_email = :rl_email
[06:55:16.190][dca6fb6e] DAV[DATA]: DavClient: User: user, Url: https://dav.example.de/user/63567ce3-780d-a35a-646e-cb080b81f00f/
[06:55:16.190][dca6fb6e] DAV[DATA]: PROPFIND /user/63567ce3-780d-a35a-646e-cb080b81f00f/
[06:55:16.217][dca6fb6e] INFO[NOTICE]: SabreForRainLoop\DAV\Exception: [CURL] Error while making request: Empty reply from server (error code: 52) in /var/www/rainloop/rainloop/v/1.12.0/app/libraries/SabreForRainLoop/DAV/Client.php:421
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/SabreForRainLoop/DAV/Client.php(178): SabreForRainLoop\DAV\Client->request('PROPFIND', 'https://dav.example...', '<?xml version="...', Array)
#1 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(468): SabreForRainLoop\DAV\Client->propFind('/user/63567ce...', Array, 1)
#2 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(593): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath(Object(SabreForRainLoop\DAV\Client), '/user/63567ce...')
#3 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(677): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://dav.example...', 'user', '*******', '')
#4 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook.php(75): RainLoop\Providers\AddressBook\PdoAddressBook->Sync('user@example...', 'https://dav.example...', 'user', '*******')
#5 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Actions.php(6716): RainLoop\Providers\AddressBook->Sync('user@example...', 'https://dav.example...', 'user', '*******')
#6 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoContactsSync()
#7 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#8 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#9 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#10 /var/www/rainloop/rainloop/v/1.12.0/app/handle.php(94): RainLoop\Service::Handle()
#11 /var/www/rainloop/rainloop/v/1.12.0/include.php(228): include('/var/www/rainlo...')
#12 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#13 {main}
[06:55:16.217][dca6fb6e] DAV[DATA]: PROPFIND /.well-known/carddav
[06:55:16.241][dca6fb6e] INFO[NOTICE]: SabreForRainLoop\DAV\Exception: [CURL] Error while making request: Empty reply from server (error code: 52) in /var/www/rainloop/rainloop/v/1.12.0/app/libraries/SabreForRainLoop/DAV/Client.php:421
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/SabreForRainLoop/DAV/Client.php(178): SabreForRainLoop\DAV\Client->request('PROPFIND', 'https://dav.example...', '<?xml version="...', Array)
#1 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(242): SabreForRainLoop\DAV\Client->propFind('/.well-known/ca...', Array, 1)
#2 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(277): RainLoop\Providers\AddressBook\PdoAddressBook->detectionPropFind(Object(SabreForRainLoop\DAV\Client), '/.well-known/ca...')
#3 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(597): RainLoop\Providers\AddressBook\PdoAddressBook->getContactsPaths(Object(SabreForRainLoop\DAV\Client), 'user', '*******', '')
#4 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(677): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://dav.example...', 'user', '*******', '')
#5 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook.php(75): RainLoop\Providers\AddressBook\PdoAddressBook->Sync('user@example...', 'https://dav.example...', 'user', '*******')
#6 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Actions.php(6716): RainLoop\Providers\AddressBook->Sync('user@example...', 'https://dav.example...', 'user', '*******')
#7 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoContactsSync()
#8 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#9 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#10 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#11 /var/www/rainloop/rainloop/v/1.12.0/app/handle.php(94): RainLoop\Service::Handle()
#12 /var/www/rainloop/rainloop/v/1.12.0/include.php(228): include('/var/www/rainlo...')
#13 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#14 {main}
[06:55:16.241][dca6fb6e] INFO[DATA]: Array
(
)

[06:55:16.241][dca6fb6e] DAV[DATA]: PROPFIND
[06:55:16.266][dca6fb6e] INFO[NOTICE]: SabreForRainLoop\DAV\Exception: [CURL] Error while making request: Empty reply from server (error code: 52) in /var/www/rainloop/rainloop/v/1.12.0/app/libraries/SabreForRainLoop/DAV/Client.php:421
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/SabreForRainLoop/DAV/Client.php(178): SabreForRainLoop\DAV\Client->request('PROPFIND', 'https://dav.example...', '<?xml version="...', Array)
#1 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(468): SabreForRainLoop\DAV\Client->propFind('', Array, 1)
#2 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(643): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath(Object(SabreForRainLoop\DAV\Client), '')
#3 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(677): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('https://dav.example...', 'user', '*******', '')
#4 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Providers/AddressBook.php(75): RainLoop\Providers\AddressBook\PdoAddressBook->Sync('user@example...', 'https://dav.example...', 'user', '*******')
#5 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Actions.php(6716): RainLoop\Providers\AddressBook->Sync('user@example...', 'https://dav.example...', 'user', '*******')
#6 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoContactsSync()
#7 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#8 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#9 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#10 /var/www/rainloop/rainloop/v/1.12.0/app/handle.php(94): RainLoop\Service::Handle()
#11 /var/www/rainloop/rainloop/v/1.12.0/include.php(228): include('/var/www/rainlo...')
#12 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#13 {main}
[06:55:16.266][dca6fb6e] INFO[NOTICE]: RainLoop\Exceptions\ClientException: ContactsSyncError[140] in /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Actions.php:6722
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoContactsSync()
#1 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#2 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /var/www/rainloop/rainloop/v/1.12.0/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /var/www/rainloop/rainloop/v/1.12.0/app/handle.php(94): RainLoop\Service::Handle()
#5 /var/www/rainloop/rainloop/v/1.12.0/include.php(228): include('/var/www/rainlo...')
#6 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#7 {main}
[06:55:16.267][dca6fb6e] AJAX[DATA]: {"Action":"ContactsSync","Result":false,"ErrorCode":140,"ErrorMessage":"","ErrorMessageAdditional":"","Time":91}
[06:55:16.267][dca6fb6e] INFO[MEMORY]: Memory peak usage: 2MB
[06:55:16.267][dca6fb6e] INFO[TIME]: Time delta: 0.091389894485474

[06:55:18.057][d564f784] INFO[DATA]: [DATE:04.07.18][OFFSET:-00][RL:1.12.0][PHP:7.0.27-0+deb9u1][IP:1.2.3.4][PID:1182][nginx/1.15.0][fpm-fcgi]
[06:55:18.058][d564f784] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv2,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[06:55:18.058][d564f784] REQUEST[NOTE]: [POST] https://examplemail.example.de/?/Ajax/&q[]=/_MKw79n2xZSvvmFkeCvRAF-RVin3ws9SsMTQrpcEWdQ5GX9s-6MfjVH_reJQ62Qt24nJakcnemKSbqHR6f2JWSCNbGmFBtboYd2F68pR-9V34J3taERGjohCohlSedDCNb2gdVW0xMaIU1GDkt3r4uzAFjvJv_YYLBjs7IJj-tAfPGus6JnBNkoi0UZ0r__RfMDCZvf6c1Fx1lAQF_m9bFYzX69CshBlOvQ_Tl0UFvYFF7qm5BcUrsfX6sJ9aIa28zuD0cG0tsU0ZQCo4E8l8Ooipodue10F-3cA7fWxa6AtHW4nh03DOP3dewwGZaNwL185AxXSY1nuDpx40eQzzZvtSvL0/
[06:55:18.058][d564f784] AJAX[NOTE]: Action: DoContacts
[06:55:18.058][d564f784] POST[DATA]: {"Offset":"0","Limit":"50","Search":"","Action":"Contacts","XToken":"d9fcc627a2021cdb7123b59e8b65f841"}
[06:55:18.061][d564f784] SQL[DATA]: SELECT value_int FROM rainloop_system WHERE sys_name = ?
[06:55:18.061][d564f784] SQL[DATA]: SELECT id_user FROM rainloop_users WHERE rl_email = :rl_email
[06:55:18.062][d564f784] SQL[DATA]: SELECT COUNT(DISTINCT id_contact) as contact_count FROM rainloop_ab_properties WHERE id_user = :id_user
[06:55:18.062][d564f784] SQL[DATA]: SELECT * FROM rainloop_ab_contacts WHERE deleted = 0 AND id_user = :id_user ORDER BY display ASC LIMIT :limit OFFSET :offset
[06:55:18.063][d564f784] SQL[DATA]: SELECT * FROM rainloop_ab_properties WHERE id_contact IN (73,60,53,69,36,14,47,30,44,9,64,33,7,12,6,70,16,315,51,313,78,11,37,77,52,71,25,49,76,309,10,311,74,82,24,68,34,61,84,67,15,28,83,1,48,284,57,38,21,55)
[06:55:18.078][d564f784] AJAX[DATA]: {"Action":"Contacts","Result":{"Offset":0,"Limit":50,"Count":67,"Search":"","List":[{"@Object":"Object\/Contact","IdContact":"73","Display":"ADAC","ReadOnly":false,"IdPropertyFromSearch":0,"Properties":[{"@Object":"Object\/Property","IdProperty":632,"Type":10,"TypeStr":"","Value":"ADAC"},{"@Object":...
[06:55:18.079][d564f784] INFO[MEMORY]: Memory peak usage: 4MB
[06:55:18.079][d564f784] INFO[TIME]: Time delta: 0.033078908920288
```

**Comment by romu70** [comment]
Same for me. I'm running the Carddav server provided by my Synology NAS, and I can sync with my iPhone without any trouble, but no way with Rainloop.

@br0kenpipe : where did you get those logs? I can't find some in my Rainloop Docker container.

**Comment by MrksHfmn** [comment]
@romu70: You need to edit the application.ini file and enable debug logging. Sry I have no experience with Docker and Rainloop. I have unfortunately given up, because i did not get any support from the developers.
