### ISSUE TITLE
RainLoop\Exceptions\ClientException: AuthError[102]

### ISSUE THREAD

**Issue by pgaunet** [RainLoop/rainloop-webmail#1868]
**RainLoop version, browser, OS:**
rainloop/v/1.12.1, firefox quantum 65.0.2 (64 bits), CentOS 7.6.1810
**Expected behavior and actual behavior:**

**Steps to reproduce the problem:**
dovecot-2.2.36-3 imap service 
  using migrated maildir from courier 0.65.0-3 and courier-imap  4.8.0-3

**Logs or screenshots:**
--- FlushLogCache: WriteOnErrorOnly
[14:32:13.929][83d64ede] INFO[DATA]: [DATE:15.04.19][OFFSET:-00][RL:1.12.1][PHP:7.0.27][IP:10.30.8.192][PID:2525][Apache][fpm-fcgi]
[14:32:13.929][83d64ede] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[14:32:13.929][83d64ede] REQUEST[NOTE]: [POST] https://10.100.29.13/webmail/?/Ajax/&q[]=/0/
[14:32:13.929][83d64ede] AJAX[NOTE]: Action: DoLogin
[14:32:13.929][83d64ede] POST[DATA]: {"Email":"dev@podias.fr","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"0","Action":"Login"
,"XToken":"1906fa0db567ab1dd524a2fd7fb84e6d"}
[14:32:13.930][83d64ede] IMAP[NOTE]: Start connection to "tcp://127.0.0.1:143"
[14:32:13.930][83d64ede] IMAP[NOTE]: Connected (success)
[14:32:13.930][83d64ede] IMAP[TIME]: 0.00013589859008789 (raw connection)
[14:32:13.938][83d64ede] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.

[14:32:13.938][83d64ede] IMAP[TIME]: 0.0085339546203613 (*)
[14:32:13.938][83d64ede] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN

[14:32:13.939][83d64ede] IMAP[DATA]: < +

[14:32:13.939][83d64ede] IMAP[TIME]: 0.00043797492980957 (TAG1)
[14:32:13.939][83d64ede] IMAP[SECURE]: > *******

[14:32:13.964][83d64ede] IMAP[DATA]: < * BYE Internal error occurred. Refer to server log for more information.

--- FlushLogCache: Trigger
[14:32:13.964][83d64ede] IMAP[ERROR]: Stream Meta: Array
(
    [timed_out] =>
    [blocked] => 1
    [eof] => 1
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] =>
)

[14:32:13.964][83d64ede] IMAP[ERROR]: MailSo\Net\Exceptions\SocketReadException: MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 515) in /apps/www/RainLoop-1.21.1/rainloop/v
/1.12.1/app/libraries/MailSo/Net/NetClient.php:515
Stack trace:
#0 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(2033): MailSo\Net\NetClient->getNextBuffer()
#1 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(1899): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response))
#2 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(1951): MailSo\Imap\ImapClient->parseResponse('TAG1', false)
#3 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(281): MailSo\Imap\ImapClient->parseResponseWithValidation()
#4 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Mail/MailClient.php(92): MailSo\Imap\ImapClient->Login('dev@podias.fr', '*******', '', true, false)
#5 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Model/Account.php(451): MailSo\Mail\MailClient->Login('dev@podias.fr', '*******', '', true, false)
#6 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2078): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#7 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2329): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#8 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2383): RainLoop\Actions->LoginProcess('dev@podias.fr', '*******', '', '', false)
#9 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoLogin()
#10 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#11 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#12 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#13 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/handle.php(94): RainLoop\Service::Handle()
#14 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/include.php(228): include('/apps/www/RainL...')
#15 /apps/www/RainLoop-1.21.1/index.php(13): include('/apps/www/RainL...')
#16 {main}
[14:32:14.965][83d64ede] INFO[ERROR]: MailSo\Net\Exceptions\SocketReadException: MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 515) in /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Net/NetClient.php:515
Stack trace:
#0 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(2033): MailSo\Net\NetClient->getNextBuffer()
#1 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(1899): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response))
#2 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(1951): MailSo\Imap\ImapClient->parseResponse('TAG1', false)
#3 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Imap/ImapClient.php(281): MailSo\Imap\ImapClient->parseResponseWithValidation()
#4 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/MailSo/Mail/MailClient.php(92): MailSo\Imap\ImapClient->Login('dev@podias.fr', '*******', '', true, false)
#5 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Model/Account.php(451): MailSo\Mail\MailClient->Login('dev@podias.fr', '*******', '', true, false)
#6 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2078): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application))
#7 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2329): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#8 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2383): RainLoop\Actions->LoginProcess('dev@podias.fr', '*******', '', '', false)
#9 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoLogin()
#10 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#11 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#12 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#13 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/handle.php(94): RainLoop\Service::Handle()
#14 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/include.php(228): include('/apps/www/RainL...')
#15 /apps/www/RainLoop-1.21.1/index.php(13): include('/apps/www/RainL...')
#16 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php:2107
Stack trace:
#0 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2329): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#1 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Actions.php(2383): RainLoop\Actions->LoginProcess('dev@podias.fr', '*******', '', '', false)
#2 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoLogin()
#3 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(146): RainLoop\ServiceActions->ServiceAjax('')
#4 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#5 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#6 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/app/handle.php(94): RainLoop\Service::Handle()
#7 /apps/www/RainLoop-1.21.1/rainloop/v/1.12.1/include.php(228): include('/apps/www/RainL...')
#8 /apps/www/RainLoop-1.21.1/index.php(13): include('/apps/www/RainL...')
#9 {main}
[14:32:14.965][83d64ede] AJAX[DATA]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1047}
[14:32:14.965][83d64ede] INFO[MEMORY]: Memory peak usage: 2MB
[14:32:14.965][83d64ede] INFO[TIME]: Time delta: 1.0478420257568
[14:32:14.965][83d64ede] IMAP[NOTE]: Disconnected from "tcp://127.0.0.1:143" (success)
[14:32:14.965][83d64ede] IMAP[TIME]: 1.0357060432434 (net session)

**Comment by saurindashadia** [comment]
Any update on this? I am getting same error code 102
