### ISSUE TITLE
Cannot login: "Authentication Failed"

### ISSUE THREAD

**Issue by qpqwill** [RainLoop/rainloop-webmail#1910]
**RainLoop version, browser, OS:**
1.13.0, Chrome Version 76.0.3809.100 (Official Build) (64-bit), macOS Mojave Version 10.14.4

**Expected behavior and actual behavior:**
Expect to login as user but the login fails.
 
**Steps to reproduce the problem:**
Install RainLoop on Centos 7 with postfix and dovecot

**Logs or screenshots:**
[20:23:34.673][3b2be82e] INFO[DATA]: [DATE:31.08.19][OFFSET:-00][RL:1.13.0][PHP:7.2.22][IP:66.74.60.106][PID:20636][nginx/1.12.2][fpm-fcgi]^M
[20:23:34.673][3b2be82e] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]^M
[20:23:34.673][3b2be82e] REQUEST[NOTE]: [POST] https://rainloop.domain.com/?/Ajax/&q[]=/0/^M
[20:23:34.673][3b2be82e] AJAX[NOTE]: Action: DoLogin^M
[20:23:34.673][3b2be82e] POST[DATA]: {"Email":"first.last@domain.com","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"1","Action":"Login","XToken":"dc5400141e2328fafc33eb010d3c35d7"}^M
[20:23:34.673][3b2be82e] PLUGIN[NOTE]: Hook: filter.login-credentials^M
[20:23:34.674][3b2be82e] INFO[NOTICE]: RainLoop\Exceptions\ClientException: AuthError[102] in /data/rainloop.domain.com/htdocs/data/_data_/_default_/plugins/white-list/index.php:25
Stack trace:
#0 /data/rainloop.domain.com/htdocs/rainloop/v/1.13.0/app/libraries/RainLoop/Plugins/Manager.php(437): WhiteListPlugin->FilterLoginCredentials('first.last@domai...', 'first.last@domai...', '*******')
#1 /data/rainloop.qpqueue.com/htdocs/rainloop/v/1.13.0/app/libraries/RainLoop/Actions.php(2243): RainLoop\Plugins\Manager->RunHook('filter.login-cr...', Array)
#2 /data/rainloop.qpqueue.com/htdocs/rainloop/v/1.13.0/app/libraries/RainLoop/Actions.php(2383): RainLoop\Actions->LoginProcess('first.last@domai...', '*******', '2c780be9893a8ce...', '', false)
#3 /data/rainloop.qpqueue.com/htdocs/rainloop/v/1.13.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoLogin()
#4 /data/rainloop.domain.com/htdocs/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceAjax('')
#5 /data/rainloop.domain.com/htdocs/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#6 /data/rainloop.domain.com/htdocs/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#7 /data/rainloop.domain.com/htdocs/rainloop/v/1.13.0/app/handle.php(94): RainLoop\Service::Handle()
#8 /data/rainloop.domain.com/htdocs/rainloop/v/1.13.0/include.php(228): include('/data/rainloop....')
#9 /data/rainloop.domain.com/htdocs/index.php(13): include('/data/rainloop....')
#10 {main}^M
[20:23:34.674][3b2be82e] AJAX[DATA]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":12}^M
[20:23:34.678][3b2be82e] INFO[MEMORY]: Memory peak usage: 2MB^M
[20:23:34.678][3b2be82e] INFO[TIME]: Time delta: 0.016242027282715^M

I notice that "short login" for the domain does not work as I expect. My logins for postfix/dovecot do not have the domain appended, but the script seems to append the domain to the login. How can I make it so that the domain does not get appended to the login?

There are no logs generated by dovecot when the login is attempted with RainLoop. If I log in with Outlook, which is working, logs will show:

Aug 31 21:01:29 mail dovecot: imap-login: Login: user=<first.last>, method=PLAIN, rip=66.74.60.106, lip=172.31.56.8, mpid=3470, TLS, session=<3mDyCnCRKvNCSjxq>

**Comment by qpqwill** [comment]
Fixed this by disabling the white-list integration

**Comment by ahmedbenaw** [comment]
> Fixed this by disabling the white-list integration

That didin't work with me!
