### ISSUE TITLE
CardDav contact sync fails with sql notice

### ISSUE THREAD

**Issue by joshp23** [RainLoop/rainloop-webmail#1923]
**RainLoop version, browser, OS:**
1.13.0, Firefox, Ubuntu
**Expected behavior and actual behavior:**
When I attempt to either sync my contact list with Nextcloud, _or_ test the contact database connection in the admin panel this error arises:
`SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "rainloop_ab_contacts" already exists`
I even tried to delete the table and resync. The table recreated itself, but the same error arose.
**Steps to reproduce the problem:**
See above.
**Logs or screenshots:**  
This one's from the connection test:
```
[16:53:44.217][d2d7253b] INFO[DATA]: [DATE:28.09.19][OFFSET:-00][RL:1.13.0][PHP:7.2.19-0ubuntu0.18.04.2][IP:2601:40d:4280:4a46:b986:7b31:309e:a464][PID:10637][nginx/1.14.0][fpm-fcgi]
[16:53:44.217][d2d7253b] INFO[DATA]: [Suhosin:off][APC:on][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[16:53:44.217][d2d7253b] REQUEST[NOTE]: [POST] https://TOTALLY_REDACTED.com/?/Ajax/&q[]=/0/
[16:53:44.217][d2d7253b] AJAX[NOTE]: Action: DoAdminContactsTest
[16:53:44.218][d2d7253b] POST[DATA]: {"ContactsPdoType":"pgsql","ContactsPdoDsn":"pgsql:host=127.0.0.1;port=5432;dbname=REDACTED","ContactsPdoUser":"REDACTED","ContactsPdoPassword":"**********","Action":"AdminContactsTest","XToken":"SOME_REDACTED_STRING"}
[16:53:45.228][d2d7253b] SQL[DATA]: SELECT value_int FROM rainloop_system WHERE sys_name = ?
[16:53:45.230][d2d7253b] SQL[DATA]: CREATE TABLE rainloop_ab_contacts (
	id_contact		bigserial		PRIMARY KEY,
	id_contact_str	varchar(128)	NOT NULL DEFAULT '',
	id_user			integer			NOT NULL,
	display			varchar(255)	NOT NULL DEFAULT '',
	changed			integer			NOT NULL default 0,
	deleted			integer			NOT NULL default 0,
	etag			varchar(128)	NOT NULL DEFAULT ''
)
[16:53:45.298][d2d7253b] SQL[DATA]: PDOException: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "rainloop_ab_contacts" already exists in /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Common/PdoAbstract.php:575
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Common/PdoAbstract.php(575): PDO->exec('CREATE TABLE ra...')
#1 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(1908): RainLoop\Common\PdoAbstract->dataBaseUpgrade('pgsql-ab-versio...', Array)
#2 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(1732): RainLoop\Providers\AddressBook\PdoAddressBook->SyncDatabase()
#3 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Providers/AddressBook.php(35): RainLoop\Providers\AddressBook\PdoAddressBook->Test()
#4 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Actions.php(3886): RainLoop\Providers\AddressBook->Test()
#5 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoAdminContactsTest()
#6 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceAjax('')
#7 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#8 /var/www/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#9 /var/www/rainloop/rainloop/v/1.13.0/app/handle.php(94): RainLoop\Service::Handle()
#10 /var/www/rainloop/rainloop/v/1.13.0/include.php(228): include('/var/www/rainlo...')
#11 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#12 {main}
[16:53:45.299][d2d7253b] AJAX[DATA]: {"Action":"AdminContactsTest","Result":{"Result":false,"Message":"SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"rainloop_ab_contacts\" already exists"},"Time":1092}
[16:53:45.299][d2d7253b] INFO[MEMORY]: Memory peak usage: 2MB
[16:53:45.299][d2d7253b] INFO[TIME]: Time delta: 1.09290599823
```

**Comment by joshp23** [comment]
H'm,

I just deleted all the `ab` tables again, and re-tested, it seems to work now, CardDav is syncing and everything. Not sure why, this behavior was observed before upgrading to 1.13.0 as well. If this happens again, I'll re-open.
