### ISSUE TITLE
sending email: Sender header invalid

### ISSUE THREAD

**Issue by bit4bit** [RainLoop/rainloop-webmail#1934]
**RainLoop version, browser, OS:**
1.13.0 Parabola Gnu/Linux-libre

**Expected behavior and actual behavior:**
Send a email

**Steps to reproduce the problem:**
exim server with acl:
~~~
  deny    !verify =     header_syntax
          message =     header syntax
          log_message = header syntax ($acl_verify_message)
~~~

**Logs or screenshots:**

log exim:
~~~bash
2019-10-14 17:40:23 1iK4KV-0011rA-HZ H=(mail.somxslibres.net) [127.0.0.1] X=TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128 CV=no F=<bit4bit@somxslibres.net> A=PLAIN: rejected after DATA: header syntax (no local part: failing address in "Sender:" header is: @somxslibres.net): no local part: failing address in "Sender:" header is: @somxslibres.net
~~~
log rainloop:
~~~
...
[17:45:16.916][37d06bb2] SMTP[TIME]: 0.00022101402282715
[17:45:16.916][37d06bb2] SMTP[NOTE]: Message data.
[17:45:16.916][37d06bb2] SMTP[DATA]: > .\r\n
[17:45:17.435][37d06bb2] SMTP[DATA]: < 550 header syntax\r\n
[17:45:17.436][37d06bb2] SMTP[ERROR]: MailSo\Smtp\Exceptions\NegativeResponseException: 550 header syntax in /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/MailSo/Smtp/SmtpClient.php:794
Stack trace:
#0 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/MailSo/Smtp/SmtpClient.php(674): MailSo\Smtp\SmtpClient->validateResponse(Array, '')
#1 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/MailSo/Smtp/SmtpClient.php(516): MailSo\Smtp\SmtpClient->sendRequestWithCheck('.', 250)
#2 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Actions.php(6311): MailSo\Smtp\SmtpClient->DataWithStream(Resource id #90)
#3 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Actions.php(6393): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #90, 919, false, true)
#4 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoSendMessage()
#5 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceAjax('')
#6 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#7 /srv/http/rainloop/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
...
~~~

**Comment by quocanh9ak2** [comment]
Hi. you can try this:
[http://www.sussex.ac.uk/its/help/faq?faqid=2478]
