### ISSUE TITLE
Can't change password with ISPConfig

### ISSUE THREAD

**Issue by przemekjagielski** [RainLoop/rainloop-webmail#1946]
**RainLoop version, browser, OS:** 
Rainloop: latest, 1.13.0
Browser: Firefox 70.0.1 (64 bits)
OS: Windows 10

**Expected behavior and actual behavior:**
Rainloop connected with db and try change password, but action ent with error. 

**Steps to reproduce the problem:**
Stack on server:
nginx 1.16.1 from nginx repo
php 7.3.12-1+0~20191128.49+debian9~1.gbp24559b from sury repo
Mysql: mysql  Ver 14.14 Distrib 5.7.28-31, for debian-linux-gnu (x86_64) using  7.0 (Percona)
ISPConfig: latest, 3.1.15p2
**Logs or screenshots:**
[09:40:51.261][1b997b09] AJAX[NOTE]: Action: DoChangePassword
[09:40:51.261][1b997b09] POST[DATA]: {"PrevPassword":"*******","NewPassword":"*******","Action":"ChangePassword","XToken":"c3602cad2c9f345a374cb2d8da2e8a51"}
[09:40:51.263][1b997b09] INFO[DATA]: ISP: Try to change password for test@domain.tld
--- FlushLogCache: Trigger
[09:40:52.264][1b997b09] INFO[NOTICE]: Error: Can't change password for test@domain.tld account.
[09:40:52.265][1b997b09] INFO[NOTICE]: RainLoop\Exceptions\ClientException: CouldNotSaveNewPassword[130] in /var/www/clients/client2/web3/web/rainloop/v/1.13.0/app/libraries/RainLoop/Providers/ChangePassword.php:79
Stack trace:
#0 /var/www/clients/client2/web3/web/rainloop/v/1.13.0/app/libraries/RainLoop/Actions.php(5069): RainLoop\Providers\ChangePassword->ChangePassword(Object(RainLoop\Model\Account), '*******', '*******')
#1 /var/www/clients/client2/web3/web/rainloop/v/1.13.0/app/libraries/RainLoop/ServiceActions.php(172): RainLoop\Actions->DoChangePassword()
#2 /var/www/clients/client2/web3/web/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(152): RainLoop\ServiceActions->ServiceAjax('')
#3 /var/www/clients/client2/web3/web/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#4 /var/www/clients/client2/web3/web/rainloop/v/1.13.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#5 /var/www/clients/client2/web3/web/rainloop/v/1.13.0/app/handle.php(94): RainLoop\Service::Handle()
#6 /var/www/clients/client2/web3/web/rainloop/v/1.13.0/include.php(228): include('/var/www/client...')
#7 /var/www/clients/client2/web3/web/index.php(13): include('/var/www/client...')
#8 {main}
[09:40:52.265][1b997b09] AJAX[DATA]: {"Action":"ChangePassword","Result":false,"ErrorCode":130,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1017}
[09:40:52.266][1b997b09] INFO[MEMORY]: Memory peak usage: 2MB
[09:40:52.267][1b997b09] INFO[TIME]: Time delta: 1.0182549953461

**Comment by Progressed36** [comment]
Just a fair warning. If your running a multi server enviroment the change password plugin is a waste of your time. It replaces the password on the main server DB and does not use the API so it changes on all servers.

**Comment by przemekjagielski** [comment]
It's not a problem with multiserver - this server isn't in multiserver ecosystem.

**Comment by jult** [comment]
Did you ever get this working? I'm getting this same error, latest rainloop, latest stable ISPConfig on a debian 10 server. For crying out loud, a user can't even change his/her password. Is this really so hard to code? Use perl for all I care and borrow it from the squirrelmail plugins that already did this with a php frontend.
