### ISSUE TITLE
Can't use my aol.com account with Rainloop...

### ISSUE THREAD

**Issue by accnetdev** [RainLoop/rainloop-webmail#1956]
**RainLoop version, browser, OS:**
RainLoop
1.13.0
Microsoft Windows [version 10.0.18363.535]
Google Chrome est à jour
Version 79.0.3945.88 (Build officiel) (64 bits)

**Expected behavior and actual behavior:**
Authentification failed.

**Steps to reproduce the problem:**
Configure an aol.com account using these settings :
Incoming mail server (IMAP): imap.aol.com 
Outgoing mail server (SMTP): smtp.aol.com | IMAP-993-SSLSMTP-465-SSL
-- | -- | --

**Logs or screenshots:**

**Comment by Schneereich** [comment]
Try the settings from the screenshot, for me it is working with the german servers:
![image](https://user-images.githubusercontent.com/6184685/73214389-5d7fc600-4152-11ea-865f-d6f0340b9bff.png)

IMAP: imap.de.aol.com:993 SSL/TLS
SMTP: smtp.de.aol.com:465 SSL/TLS

Otherwise contact the aol.com support and check if your servers ip address is somehow blocked.

**Comment by accnetdev** [comment]
All is OK with the same config like yours all is green, but I can't connect with my email and password.
In the aol webmail no problem to connect using the same credentials.
I am not blacklisted.

**Comment by 0FaKE** [comment]
> but I can't connect with my email and password

Same here.
Looks like AOL doesn't support this anymore.

`< TAG1 NO [AUTHENTICATIONFAILED] AUTHENTICATE Invalid credentials`

The login credentials are not wrong.

`[18:34:37.312][8cb909e8] INFO[DATA]: [DATE:07.03.20][OFFSET:-00][RL:1.14.0][PHP:7.3.2][IP:x.x.x.x][PID:5484][Apache/2.4.38 (Win64) OpenSSL/1.1.1b PHP/7.3.2][apache2handler]
[18:34:37.315][8cb909e8] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[18:34:37.319][8cb909e8] REQUEST[NOTE]: [POST] https://webmail.mydomain.xyz/?/Ajax/&q[]=/0/
[18:34:37.323][8cb909e8] AJAX[NOTE]: Action: DoLogin
[18:34:37.327][8cb909e8] POST[DATA]: {"Email":"s****@aol.com","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"0","Action":"Login","XToken":"2a6ed2377fb3fc43ddd110c2c39dfb4a"}
[18:34:37.332][8cb909e8] IMAP[NOTE]: Start connection to "ssl://imap.de.aol.com:993"
[18:34:37.559][8cb909e8] IMAP[NOTE]: Connected (success)
[18:34:37.567][8cb909e8] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello\r\n
[18:34:37.570][8cb909e8] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[18:34:37.624][8cb909e8] IMAP[DATA]: < + \r\n
[18:34:37.630][8cb909e8] IMAP[SECURE]: > *******\r\n
[18:34:41.722][8cb909e8] IMAP[DATA]: < TAG1 NO [AUTHENTICATIONFAILED] AUTHENTICATE Invalid credentials\r\n
[18:34:41.732][8cb909e8] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in ..\apps\webmail\rainloop\v\1.14.0\app\libraries\MailSo\Imap\ImapClient.php:1876
Stack trace:
#0 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\MailSo\Imap\ImapClient.php(1953): MailSo\Imap\ImapClient->validateResponse(Array)
#1 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\MailSo\Imap\ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\MailSo\Mail\MailClient.php(93): MailSo\Imap\ImapClient->Login('s****@aol.c...', '*******', '', true, false)
#3 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\Model\Account.php(508): MailSo\Mail\MailClient->Login('s****@aol.c...', '*******', '', true, false)
#4 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\Actions.php(2154): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#5 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\Actions.php(2405): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#6 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\Actions.php(2457): RainLoop\Actions->LoginProcess('s****@aol.c...', '*******', '', '', false)
#7 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\ServiceActions.php(174): RainLoop\Actions->DoLogin()
#8 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\Service.php(150): RainLoop\ServiceActions->ServiceAjax('')
#9 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\Service.php(62): RainLoop\Service->localHandle()
#10 ..\apps\webmail\rainloop\v\1.14.0\app\libraries\RainLoop\Service.php(85): RainLoop\Service->__construct()
#11 ..\apps\webmail\rainloop\v\1.14.0\app\handle.php(94): RainLoop\Service::Handle()
#12 ..\apps\webmail\rainloop\v\1.14.0\include.php(228): include('...')
#13 ..\apps\webmail\index.php(13): include('...')
#14 {main}`

**Comment by Faillinx** [comment]
I believe this is similiar to what Gmail is going to do, which is disable unsecured applications and force Oauth2.

**Comment by accnetdev** [comment]
Hi,
@Faillinx : you were right, the issue came from AOL's Oauth2.

https://help.aol.com/articles/allow-apps-that-use-less-secure-sign-in?guccounter=1
https://help.aol.com/articles/Create-and-manage-app-password

Using the above pages, I managed to create a password for an "other app" rainloop (my rainloop script on my hosting).
It works well but obviously much slower than using the official AOL's webmail.

Happy new year to all !
