### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by caywin25** [RainLoop/rainloop-webmail#2049]
Hello, 

I'm using the latest version of Rainloop (1.14) with openbsd httpd and I get the error: Authentication failed when I try to log in.

I'm sure my password is good.
Here is the log I have when I log in (my information has been changed): 

```
[14:14:20.705][d8e775e6] INFO[DATA]: [DATE:10.12.20][OFFSET:-00][RL:1.14.0][PHP:7][IP:127.0.0.1][PID:60626][OpenBSD httpd][fpm-fcgi]
[14:14:20.705][d8e775e6] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:~][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[14:14:20.705][d8e775e6] REQUEST[NOTE]: [GET] http://webmail.hostname.org/
[14:14:20.718][d8e775e6] INFO[MEMORY]: Memory peak usage: 2MB
[14:14:20.718][d8e775e6] INFO[TIME]: Time delta: 0.055972814559937

[14:14:21.013][eabafbae] INFO[DATA]: [DATE:10.12.20][OFFSET:-00][RL:1.14.0][PHP:7][IP:127.0.0.1][PID:78919][OpenBSD httpd][fpm-fcgi]
[14:14:21.013][eabafbae] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:~][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[14:14:21.013][eabafbae] REQUEST[NOTE]: [GET] http://webmail.hostname.org/?/Css/0/User/-/Default/-/0f02fb6f9897aaf90b9e885d94f38646/Hash/-/
[14:14:21.027][eabafbae] INFO[MEMORY]: Memory peak usage: 2MB
[14:14:21.027][eabafbae] INFO[TIME]: Time delta: 0.057579040527344

[14:14:21.352][150fd65c] INFO[DATA]: [DATE:10.12.20][OFFSET:-00][RL:1.14.0][PHP:7][IP:127.0.0.1][PID:60626][OpenBSD httpd][fpm-fcgi]
[14:14:21.352][150fd65c] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:~][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[14:14:21.352][150fd65c] REQUEST[NOTE]: [GET] http://webmail.hostname.org/?/AppData@no-mobile-0/0/20782881742404158/
[14:14:21.357][150fd65c] APPDATA[DATA]: if(window.__initAppData){window.__initAppData({"Auth":false,"AccountHash":"","AccountSignMe":false,"AuthAccountHash":"","MailToEmail":"","Email":"","DevEmail":"","DevPassword":"","Title":"Webmail","LoadingDescription":"RainLoop","LoadingDescriptionEsc":"RainLoop","FaviconUrl":"","LoginDescription":"","LoginLogo":"","LoginBackground":"","LoginCss":"","UserLogo":"","UserLogoTitle":"","UserLogoMessage":"","UserCss":"","WelcomePageUrl":"","WelcomePageDisplay":"","IncludeCss":"","IncludeBackground":"","LoginDefaultDomain":"","DetermineUserLanguage":true,"DetermineUserDomain":false,"UseLoginWelcomePage":false,"StartupUrl":"","SieveAllowFileintoInbox":false,"ContactsIsAllowed":false,"ChangePasswordIsAllowed":false,"RequireTwoFactor":false,"Community":true,"PremType":false,"Admin":[],"Capa":["FOLDERS","MESSAGELIST_ACTIONS","DANGEROUS_ACTIONS","RELOAD","QUOTA","SETTINGS","ADDITIONAL_ACCOUNTS","IDENTITIES","THEMES","FILTERS","HELP","ATTACHMENTS_ACTIONS","MESSAGE_ACTIONS","COMPOSER","CONTACTS","SEARCH","SEARCH_ADV","GRAVATAR","ATTACHMENT_THUMBNAILS","PREFETCH","AUTOLOGOUT"],"Plugins":[],"System":{"version":"1.14.0","admin":false,"mobile":false,"mobileDevice":false,"webPath":"","webVersionPath":"rainloop\/v\/1.14.0\/","token":"3403b0f22542428af9e5222eb33737af","inIframe":false,"allowHtmlEditorSourceButton":false,"allowHtmlEditorBitiButtons":false,"allowCtrlEnterOnCompose":true,"customLoginLink":"","customLogoutLink":"","forgotPasswordLinkUrl":"","registrationLinkUrl":"","hideSubmitButton":true,"jsHash":"e87e39e557c3733406066e3c4c5a2253","useImapThread":true,"useImapSubscribe":true,"allowAppendMessage":false,"materialDesign":true,"folderSpecLimit":50,"faviconStatus":true,"allowCmdInterface":false,"useNativeScrollbars":false,"listPermanentFiltered":false,"themes":["Default","A","Blurred","DarkShine","Linen","Love","Snow","Squares","SquaresDark","Stripes","Wood","Xv","Clear"],"languages":["ar_SA","bg_BG","cs_CZ","da_DK","de_DE","el_GR","en_GB","en_US","es_ES","et_EE","fa_IR","fi_FI","fr_FR","hu_HU","id_ID","is_IS","it_IT","ja_JP","ko_KR","lt_LT","lv_LV","nb_NO","nl_NL","pl_PL","pt_BR","pt_PT","ro_RO","ru_RU","sk_SK","sl_SI","sv_SE","tr_TR","uk_UA","zh_CN","zh_TW"],"languagesAdmin":["cs_CZ","da_DK","de_DE","en_US","es_ES","fa_IR","fi_FI","fr_FR","hu_HU","id_ID","it_IT","ja_JP","lt_LT","nb_NO","nl_NL","pl_PL","pt_BR","ru_RU","sk_SK","sl_SI","sv_SE","zh_CN"],"appVersionType":"community","attachmentsActions":[]},"AdditionalLoginError":"","AllowGoogleSocial":false,"AllowGoogleSocialAuth":false,"AllowGoogleSocialAuthGmail":false,"AllowGoogleSocialDrive":false,"AllowGoogleSocialPreview":false,"GoogleClientID":"","GoogleApiKey":"","AllowFacebookSocial":false,"AllowTwitterSocial":false,"AllowDropboxSocial":false,"DropboxApiKey":"","SupportedFacebookSocial":true,"ProjectHash":"0f02fb6f9897aaf90b9e885d94f38646","NewMoveToFolder":true,"AllowLanguagesOnSettings":true,"AllowLanguagesOnLogin":true,"AttachmentLimit":26214400,"SignMe":"DefaultOff","UseLocalProxyForExternalImages":false,"ShowImages":false,"MPP":20,"SoundNotification":false,"DesktopNotifications":false,"Layout":1,"EditorDefaultType":"Html","UseCheckboxesInList":true,"AutoLogout":30,"UseThreads":false,"AllowDraftAutosave":true,"ReplySameFolder":false,"ContactsAutosave":true,"EnableTwoFactor":false,"ParentEmail":"","InterfaceAnimation":true,"UserBackgroundName":"","UserBackgroundHash":"","Theme":"Default","NewThemeLink":".\/?\/Css\/0\/User\/-\/Default\/-\/0f02fb6f9897aaf90b9e885d94f38646\/Hash\/-\/","Language":"en_US","LanguageAdmin":"en_US","UserLanguageRaw":"en_US","UserLanguage":"en_US","UserLanguageAdmin":"en_US","PluginsLink":"","LangLink":".\/?\/Lang\/0\/App\/en_US\/0f02fb6f9897aaf90b9e885d94f38646\/","TemplatesLink":".\/?\/Templates\/0\/App\/0f02fb6f9897aaf90b9e885d94f38646\/","StaticLibJsLink":"rainloop\/v\/1.14.0\/static\/js\/min\/libs.min.js?community","StaticAppJsLink":"rainloop\/v\/1.14.0\/static\/js\/min\/app.min.js?community","StaticAppJsNextLink":"rainloop\/v\/1.14.0\/static\/js\/app.next.js?community","StaticEditorJsLink":"rainloop\/v\/1.14.0\/static\/ckeditor\/ckeditor.js?community"});}
[14:14:21.364][150fd65c] INFO[MEMORY]: Memory peak usage: 2MB
[14:14:21.364][150fd65c] INFO[TIME]: Time delta: 0.055611848831177
[14:14:29.309][30ec4816] INFO[DATA]: [DATE:10.12.20][OFFSET:-00][RL:1.14.0][PHP:7][IP:127.0.0.1][PID:78919][OpenBSD httpd][fpm-fcgi]
[14:14:29.310][30ec4816] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:~][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2,tlsv1.3]
[14:14:29.310][30ec4816] REQUEST[NOTE]: [POST] http://webmail.hostname.org/?/Ajax/&q[]=/0/
[14:14:29.312][30ec4816] AJAX[NOTE]: Action: DoLogin
[14:14:29.312][30ec4816] POST[DATA]: {"Email":"user@hostname.org","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"0","Action":"Login","XToken":"3403b0f22542428af9e5222eb33737af"}
[14:14:29.322][30ec4816] IMAP[NOTE]: Start connection to "ssl://mail.hostname.org:993"
[14:14:29.369][30ec4816] IMAP[NOTE]: Connected (success)
[14:14:29.567][30ec4816] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot ready.\r\n
[14:14:29.568][30ec4816] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[14:14:29.570][30ec4816] IMAP[DATA]: < + \r\n
[14:14:29.570][30ec4816] IMAP[SECURE]: > *******\r\n
[14:14:31.137][30ec4816] IMAP[DATA]: < TAG1 NO [AUTHENTICATIONFAILED] Authentication failed.\r\n
[14:14:31.138][30ec4816] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php:1876
Stack trace:
#0 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(1953): MailSo\Imap\ImapClient->validateResponse()
#1 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login()
#3 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login()
#4 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2154): RainLoop\Model\Account->IncConnectAndLoginHelper()
#5 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2405): RainLoop\Actions->CheckMailConnection()#6 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2457): RainLoop\Actions->LoginProcess()
#7 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#8 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax()
#9 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#10 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#11 /htdocs/mail/rainloop/v/1.14.0/app/handle.php(94): RainLoop\Service::Handle()
#12 /htdocs/mail/rainloop/v/1.14.0/include.php(228): include('/htdocs/mail/ra...')
#13 /htdocs/mail/index.php(13): include('/htdocs/mail/ra...')
#14 {main}
[14:14:31.138][30ec4816] IMAP[NOTICE]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php:1876
Stack trace:
#0 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(1953): MailSo\Imap\ImapClient->validateResponse()
#1 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login()
#3 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login()
#4 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2154): RainLoop\Model\Account->IncConnectAndLoginHelper()
#5 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2405): RainLoop\Actions->CheckMailConnection()
#6 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2457): RainLoop\Actions->LoginProcess()
#7 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#8 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax()
#9 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#10 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#11 /htdocs/mail/rainloop/v/1.14.0/app/handle.php(94): RainLoop\Service::Handle()
#12 /htdocs/mail/rainloop/v/1.14.0/include.php(228): include('/htdocs/mail/ra...')
#13 /htdocs/mail/index.php(13): include('/htdocs/mail/ra...')
#14 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException: MailSo-Imap-Exceptions-LoginBadCredentialsException (ImapClient.php ~ 314) in /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php:314
Stack trace:
#0 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login()
#1 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login()
#2 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2154): RainLoop\Model\Account->IncConnectAndLoginHelper()
#3 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2405): RainLoop\Actions->CheckMailConnection()
#4 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2457): RainLoop\Actions->LoginProcess()
#5 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#6 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax()
#7 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#8 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#9 /htdocs/mail/rainloop/v/1.14.0/app/handle.php(94): RainLoop\Service::Handle()
#10 /htdocs/mail/rainloop/v/1.14.0/include.php(228): include('/htdocs/mail/ra...')
#11 /htdocs/mail/index.php(13): include('/htdocs/mail/ra...')
#12 {main}
[14:14:31.140][30ec4816] INFO[ERROR]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php:1876
Stack trace:
#0 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(1953): MailSo\Imap\ImapClient->validateResponse()
#1 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login()
#3 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login()
#4 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2154): RainLoop\Model\Account->IncConnectAndLoginHelper()
#5 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2405): RainLoop\Actions->CheckMailConnection()
#6 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2457): RainLoop\Actions->LoginProcess()
#7 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#8 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax()
#9 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#10 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#11 /htdocs/mail/rainloop/v/1.14.0/app/handle.php(94): RainLoop\Service::Handle()
#12 /htdocs/mail/rainloop/v/1.14.0/include.php(228): include('/htdocs/mail/ra...')
#13 /htdocs/mail/index.php(13): include('/htdocs/mail/ra...')
#14 {main}
Next MailSo\Imap\Exceptions\LoginBadCredentialsException: MailSo-Imap-Exceptions-LoginBadCredentialsException (ImapClient.php ~ 314) in /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Imap/ImapClient.php:314
Stack trace:
#0 /htdocs/mail/rainloop/v/1.14.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login()
#1 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login()
#2 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2154): RainLoop\Model\Account->IncConnectAndLoginHelper()
#3 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2405): RainLoop\Actions->CheckMailConnection()
#4 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2457): RainLoop\Actions->LoginProcess()
#5 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#6 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax()
#7 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#8 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#9 /htdocs/mail/rainloop/v/1.14.0/app/handle.php(94): RainLoop\Service::Handle()
#10 /htdocs/mail/rainloop/v/1.14.0/include.php(228): include('/htdocs/mail/ra...')
#11 /htdocs/mail/index.php(13): include('/htdocs/mail/ra...')
#12 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php:2173
Stack trace:
#0 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2405): RainLoop\Actions->CheckMailConnection()
#1 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Actions.php(2457): RainLoop\Actions->LoginProcess()
#2 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#3 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax()
#4 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#5 /htdocs/mail/rainloop/v/1.14.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#6 /htdocs/mail/rainloop/v/1.14.0/app/handle.php(94): RainLoop\Service::Handle()
#7 /htdocs/mail/rainloop/v/1.14.0/include.php(228): include('/htdocs/mail/ra...')
#8 /htdocs/mail/index.php(13): include('/htdocs/mail/ra...')
#9 {main}
[14:14:31.140][30ec4816] AJAX[DATA]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1867}
[14:14:31.145][30ec4816] INFO[MEMORY]: Memory peak usage: 2MB
[14:14:31.145][30ec4816] INFO[TIME]: Time delta: 1.8704500198364
[14:14:31.146][30ec4816] IMAP[NOTE]: Disconnected from "ssl://mail.hostname.org:993" (success)
```
Please could you help me ?
Thank's

**Comment by caywin25** [comment]
Issue solved like used short login user.
