### ISSUE TITLE
Blank rainloop admin panel

### ISSUE THREAD

**Issue by dupgit** [RainLoop/rainloop-webmail#2057]
**RainLoop version, browser, OS:**

Server debian 10.7, nginx 1.14.2 and php-fpm 7.3.19-1~deb10u1, Fresh installation of nextcloud 20.0.4, rainloop 7.0.3

**Expected behavior and actual behavior:**

expected behavior : when clicking on rainloop admin panel link in webmail section of additional settings should display the admin panel.
actual behavior : clicking on the rainloop admin panel link in webmail section of additional settings displays a blank page.

**Steps to reproduce the problem:**
Click on the link…

**Logs or screenshots:**
2021/01/12 18:51:03 [error] 10361#10361: *14252 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /var/www/nextcloud/apps/rainloop/app/index.php:8
Stack trace:
#0 /var/www/nextcloud/apps/rainloop/app/rainloop/v/1.14.0/include.php(57): __get_custom_data_full_path()
#1 /var/www/nextcloud/apps/rainloop/app/index.php(23): include('/var/www/nextcl...')
#2 {main}
  thrown in /var/www/nextcloud/apps/rainloop/app/index.php on line 8" while reading response header from upstream, client: my.pubilc.ip.addr, server: cloud.domain.tld, request: "GET /apps/rainloop/app/?admin HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "cloud.domain.tld"

No log in php-fpm log file.

**Comment by dupgit** [comment]
Wrong repository. This issue is related to rainloop in nextcloud (see https://github.com/pierre-alain-b/rainloop-nextcloud/issues/215#)
