### ISSUE TITLE
[AUTHENTICATIONFAILED] with Strato Domains

### ISSUE THREAD

**Issue by slgfire** [RainLoop/rainloop-webmail#2083]
**RainLoop version, browser, OS:**
Version 1.15.0, Browser: Chrome and Firefox

**problem:**
i have the problem, that i cant add my strato domain. error message is authentication failed but de password is right.
when i logged me in here: https://communicator.strato.com/appsuite/ with full email address is all ok.
gmx and gmail is no problem with my rainloop installation.

**Logs or screenshots:**
here is my log, domains/password chaned to dummy

`[22:03:07.212][a01059cb] INFO[DATA]: [DATE:28.03.21][OFFSET:-00][RL:1.15.0][PHP:7.3.27][IP:95.88.185.37][PID:13936][Apache/2.4.46 (Unix)][cgi-fcgi]
[22:03:07.213][a01059cb] INFO[DATA]: [APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[22:03:07.213][a01059cb] REQUEST[NOTE]: [POST] http://DOMAIN.de/mail/?/Ajax/&q[]=/_mjehavkmqmp-wATTNjpNuEJoF9NI-2e8pdwLVwey8hgYx_CMCxSLalNV-DexHFJjLUz2fWgOUmn6_zzD2QO_wasdaloshaha-e9qKLVH38maDUF5E43zZQI201TEdN0Tsj2PoAnXMYMtY1BwXdOAYn6asdasdasdasdasdasdXKsrSV-UTnKFbHF_9jB1YNTW_EZoNJ88wJ2C1GEelqVBdtsdasdAsq5KYsn1VOn13XOLq9LcgssvjZr_yiqzVrPWHKVV2g0TMr5_92A4mz568gs8yGTN-cALvkBcWHOfDWmABTTy8tnjWZkHR-8kzGJAKUikj6MA/
[22:03:07.215][a01059cb] AJAX[NOTE]: Action: DoAccountSetup
[22:03:07.215][a01059cb] POST[DATA]: {"Email":"","Password":"PASSWORD123","New":"1","Action":"AccountSetup","XToken":"950561474030af972369e1337296013c"}
[22:03:07.228][a01059cb] IMAP[NOTE]: Start connection to "ssl://imap.strato.de:993"
[22:03:07.236][a01059cb] IMAP[NOTE]: Connected (success)
[22:03:07.237][a01059cb] IMAP[DATA]: < * OK [CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=LOGIN AUTH=CRAM-MD5 AUTH=DIGEST-MD5 CHILDREN ENABLE I18NLEVEL=2 ID IDLE MOVE MULTIAPPEND NAMESPACE QUOTA SORT STATUS=SIZE UIDPLUS UNSELECT WITHIN XLIST] IMAP server ready (P6 TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384)\r\n
[22:03:07.239][a01059cb] IMAP[DATA]: > TAG1 AUTHENTICATE PLAIN\r\n
[22:03:07.239][a01059cb] IMAP[DATA]: < + \r\n
[22:03:07.240][a01059cb] IMAP[SECURE]: > *******\r\n
[22:03:15.245][a01059cb] IMAP[DATA]: < TAG1 NO [AUTHENTICATIONFAILED] mail@DOMAIN.de Authentication failed\r\n
[22:03:15.249][a01059cb] IMAP[WARNING]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in /mnt/web202/d0/97/53865097/htdocs/strato/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php:1876
Stack trace:
#0 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php(1953): MailSo\Imap\ImapClient->validateResponse(Array)
#1 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login('mail@DOMAIN...', '*******', '', true, false)
#3 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login('mail@DOMAIN...', '*******', '', true, false)
#4 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2153): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#5 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#6 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2936): RainLoop\Actions->LoginProcess('mail@DOMAIN...', '*******', '', '', false, true)
#7 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoAccountSetup()
#8 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax('')
#9 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#10 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#11 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/handle.php(94): RainLoop\Service::Handle()
#12 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/include.php(243): include('/mnt/web202/d0/...')
#13 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/index.php(13): include('/mnt/web202/d0/...')
#14 {main}
[22:03:15.251][a01059cb] IMAP[NOTICE]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php:1876
Stack trace:
#0 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php(1953): MailSo\Imap\ImapClient->validateResponse(Array)
#1 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login('mail@DOMAIN...', '*******', '', true, false)
#3 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login('mail@DOMAIN...', '*******', '', true, false)
#4 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2153): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#5 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#6 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2936): RainLoop\Actions->LoginProcess('mail@DOMAIN...', '*******', '', '', false, true)
#7 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoAccountSetup()
#8 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax('')
#9 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#10 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#11 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/handle.php(94): RainLoop\Service::Handle()
#12 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/include.php(243): include('/mnt/web202/d0/...')
#13 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/index.php(13): include('/mnt/web202/d0/...')
#14 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException: MailSo-Imap-Exceptions-LoginBadCredentialsException (ImapClient.php ~ 314) in /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php:314
Stack trace:
#0 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login('mail@DOMAIN...', '*******', '', true, false)
#1 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login('mail@DOMAIN...', '*******', '', true, false)
#2 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2153): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#3 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#4 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2936): RainLoop\Actions->LoginProcess('mail@DOMAIN...', '*******', '', '', false, true)
#5 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoAccountSetup()
#6 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax('')
#7 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#8 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#9 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/handle.php(94): RainLoop\Service::Handle()
#10 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/include.php(243): include('/mnt/web202/d0/...')
#11 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/index.php(13): include('/mnt/web202/d0/...')
#12 {main}
[22:03:15.256][a01059cb] INFO[ERROR]: MailSo\Imap\Exceptions\NegativeResponseException: MailSo-Imap-Exceptions-NegativeResponseException (ImapClient.php ~ 1876) in /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php:1876
Stack trace:
#0 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php(1953): MailSo\Imap\ImapClient->validateResponse(Array)
#1 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#2 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login('mail@DOMAIN...', '*******', '', true, false)
#3 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login('mail@DOMAIN...', '*******', '', true, false)
#4 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2153): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#5 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#6 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2936): RainLoop\Actions->LoginProcess('mail@DOMAIN...', '*******', '', '', false, true)
#7 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoAccountSetup()
#8 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax('')
#9 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#10 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#11 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/handle.php(94): RainLoop\Service::Handle()
#12 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/include.php(243): include('/mnt/web202/d0/...')
#13 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/index.php(13): include('/mnt/web202/d0/...')
#14 {main}

Next MailSo\Imap\Exceptions\LoginBadCredentialsException: MailSo-Imap-Exceptions-LoginBadCredentialsException (ImapClient.php ~ 314) in /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Imap/ImapClient.php:314
Stack trace:
#0 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login('mail@DOMAIN...', '*******', '', true, false)
#1 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login('mail@DOMAIN...', '*******', '', true, false)
#2 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2153): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#3 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#4 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2936): RainLoop\Actions->LoginProcess('mail@DOMAIN...', '*******', '', '', false, true)
#5 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoAccountSetup()
#6 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax('')
#7 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#8 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#9 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/handle.php(94): RainLoop\Service::Handle()
#10 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/include.php(243): include('/mnt/web202/d0/...')
#11 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/index.php(13): include('/mnt/web202/d0/...')
#12 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php:2172
Stack trace:
#0 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#1 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Actions.php(2936): RainLoop\Actions->LoginProcess('mail@DOMAIN...', '*******', '', '', false, true)
#2 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoAccountSetup()
#3 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(150): RainLoop\ServiceActions->ServiceAjax('')
#4 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#5 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#6 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/app/handle.php(94): RainLoop\Service::Handle()
#7 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/rainloop/v/1.15.0/include.php(243): include('/mnt/web202/d0/...')
#8 /mnt/web202/d0/97/53865097/htdocs/stratro/mail/index.php(13): include('/mnt/web202/d0/...')
#9 {main}
[22:03:15.257][a01059cb] AJAX[DATA]: {"Action":"AccountSetup","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":8063}
[22:03:15.259][a01059cb] INFO[MEMORY]: Memory peak usage: 2MB
[22:03:15.260][a01059cb] INFO[TIME]: Time delta: 8.0651228427887
[22:03:15.261][a01059cb] IMAP[NOTE]: Disconnected from "ssl://imap.strato.de:993" (success)
`

**Comment by the-djmaze** [comment]
Port 993 is oldschool.
Did you try 143 with STARTTLS?

**Comment by slgfire** [comment]
same issue :(
prots from here:
https://www.strato.de/faq/mail/so-lauten-die-strato-e-mail-server/

**Comment by Psychi1** [comment]
Hello,

this is my working config:

```
imap_host = "imap.strato.de"
imap_port = 993
imap_secure = "SSL"
imap_short_login = Off
sieve_use = Off
sieve_allow_raw = Off
sieve_host = ""
sieve_port = 4190
sieve_secure = "None"
smtp_host = "smtp.strato.de"
smtp_port = 587
smtp_secure = "TLS"
smtp_short_login = Off
smtp_auth = On
smtp_php_mail = On
white_list = ""
```

if you are using your own domain setup, you have to create an alias.
