### ISSUE TITLE
RainLoop cannot log in, auth failed

### ISSUE THREAD

**Issue by Weltolk** [RainLoop/rainloop-webmail#2114]
**RainLoop version, browser, OS:**
RainLoop version:1.16.0
brower version:edge latest
OS version:Linux VM-0-7-debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

**Expected behavior and actual behavior:**
Expected behavior:Log in to RainLoop
actual behavior:auth failed

**Steps to reproduce the problem:**
1.Install and set up postfix, dovecot and nginx
2.Install and set up RainLoop
3.Create a users file under /etc/dovecot/, add users
```
root@VM-0-7-debian:~# cat /etc/dovecot/users 
admin@xxxx.com:{PLAIN}ab123456::::::
```
4.Visit mail.xxxx.com and log in

**Logs or screenshots:**
RainLoop settings:
![image](https://user-images.githubusercontent.com/40228052/129531635-2cad52a6-a81b-489e-b799-17ce6a1c5448.png)

RainLoop log:
```
[07:48:11.119][bcf3f8cd] INFO[DATA]: [DATE:16.08.21][OFFSET:-00][RL:1.16.0][PHP:7.3.27-1~deb10u1][IP:112.9.209.202][PID:18643][nginx/1.21.0][fpm-fcgi]
[07:48:11.119][bcf3f8cd] INFO[DATA]: [APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[07:48:11.119][bcf3f8cd] REQUEST[NOTE]: [GET] https://mail.xxxx.com/
[07:48:11.126][bcf3f8cd] INFO[MEMORY]: Memory peak usage: 2MB
[07:48:11.126][bcf3f8cd] INFO[TIME]: Time delta: 0.017277956008911

[07:48:11.316][9b38137a] INFO[DATA]: [DATE:16.08.21][OFFSET:-00][RL:1.16.0][PHP:7.3.27-1~deb10u1][IP:112.9.209.202][PID:18642][nginx/1.21.0][fpm-fcgi]
[07:48:11.316][9b38137a] INFO[DATA]: [APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[07:48:11.316][9b38137a] REQUEST[NOTE]: [GET] https://mail.xxxx.com/?/AppData@no-mobile-0/0/6627665166583501/
[07:48:11.317][9b38137a] APPDATA[DATA]: if(window.__initAppData){window.__initAppData({"Auth":false,"AccountHash":"","AccountSignMe":false,"AuthAccountHash":"","MailToEmail":"","Email":"","DevEmail":"","DevPassword":"","Title":"RainLoop Webmail","LoadingDescription":"RainLoop","LoadingDescriptionEsc":"RainLoop","FaviconUrl":"","LoginDescription":"","LoginLogo":"","LoginBackground":"","LoginCss":"","UserLogo":"","UserLogoTitle":"","UserLogoMessage":"","UserCss":"","WelcomePageUrl":"","WelcomePageDisplay":"","IncludeCss":"","IncludeBackground":"","LoginDefaultDomain":"","DetermineUserLanguage":true,"DetermineUserDomain":false,"UseLoginWelcomePage":false,"StartupUrl":"","SieveAllowFileintoInbox":false,"ContactsIsAllowed":false,"ChangePasswordIsAllowed":false,"RequireTwoFactor":false,"Community":true,"PremType":false,"Admin":[],"Capa":["FOLDERS","MESSAGELIST_ACTIONS","DANGEROUS_ACTIONS","RELOAD","QUOTA","SETTINGS","ADDITIONAL_ACCOUNTS","IDENTITIES","THEMES","FILTERS","HELP","ATTACHMENTS_ACTIONS","MESSAGE_ACTIONS","COMPOSER","CONTACTS","SEARCH","SEARCH_ADV","GRAVATAR","ATTACHMENT_THUMBNAILS","PREFETCH","AUTOLOGOUT"],"Plugins":[],"System":{"version":"1.16.0","admin":false,"mobile":false,"mobileDevice":false,"webPath":"","webVersionPath":"rainloop\/v\/1.16.0\/","token":"cada4e670b703470561df70d1998066c","inIframe":false,"allowHtmlEditorSourceButton":false,"allowHtmlEditorBitiButtons":false,"allowCtrlEnterOnCompose":true,"customLoginLink":"","customLogoutLink":"","forgotPasswordLinkUrl":"","registrationLinkUrl":"","hideSubmitButton":true,"jsHash":"aa2dc94ce825a27ef328f4fff639aca2","useImapThread":true,"useImapSubscribe":true,"allowAppendMessage":false,"materialDesign":true,"folderSpecLimit":50,"faviconStatus":true,"allowCmdInterface":false,"useNativeScrollbars":false,"listPermanentFiltered":false,"themes":["Default","A","Blurred","DarkShine","Linen","Love","Snow","Squares","SquaresDark","Stripes","Wood","Xv","Clear"],"languages":["ar_SA","bg_BG","ca","ca_ES","cs_CZ","da_DK","de_DE","el_GR","en_GB","en_US","es_ES","et_EE","eu","fa_IR","fi_FI","fr_FR","hu_HU","id_ID","is_IS","it_IT","ja_JP","ko_KR","lt_LT","lv_LV","nb_NO","nl_NL","pl_PL","pt_BR","pt_PT","ro_RO","ru_RU","sk_SK","sl_SI","sv_SE","tr_TR","uk_UA","zh_CN","zh_TW"],"languagesAdmin":["ca","ca_ES","cs_CZ","da_DK","de_DE","en_US","es_ES","eu","fa_IR","fi_FI","fr_FR","hu_HU","id_ID","it_IT","ja_JP","lt_LT","nb_NO","nl_NL","pl_PL","pt_BR","ru_RU","sk_SK","sl_SI","sv_SE","zh_CN"],"appVersionType":"community","attachmentsActions":["zip"]},"AdditionalLoginError":"","AllowGoogleSocial":false,"AllowGoogleSocialAuth":false,"AllowGoogleSocialAuthGmail":false,"AllowGoogleSocialDrive":false,"AllowGoogleSocialPreview":false,"GoogleClientID":"","GoogleApiKey":"","AllowFacebookSocial":false,"AllowTwitterSocial":false,"AllowDropboxSocial":false,"DropboxApiKey":"","SupportedFacebookSocial":true,"ProjectHash":"1c6a6bc68ba5f92d85485ab98a7fc6d4","NewMoveToFolder":true,"AllowLanguagesOnSettings":true,"AllowLanguagesOnLogin":true,"AttachmentLimit":1073741824,"SignMe":"DefaultOff","UseLocalProxyForExternalImages":false,"ShowImages":false,"MPP":20,"SoundNotification":false,"DesktopNotifications":false,"Layout":1,"EditorDefaultType":"Html","UseCheckboxesInList":true,"AutoLogout":30,"UseThreads":false,"AllowDraftAutosave":true,"ReplySameFolder":false,"ContactsAutosave":true,"EnableTwoFactor":false,"ParentEmail":"","InterfaceAnimation":true,"UserBackgroundName":"","UserBackgroundHash":"","Theme":"Default","NewThemeLink":".\/?\/Css\/0\/User\/-\/Default\/-\/1c6a6bc68ba5f92d85485ab98a7fc6d4\/Hash\/-\/","Language":"zh_CN","LanguageAdmin":"zh_CN","UserLanguageRaw":"zh_CN","UserLanguage":"zh_CN","UserLanguageAdmin":"zh_CN","PluginsLink":"","LangLink":".\/?\/Lang\/0\/App\/zh_CN\/1c6a6bc68ba5f92d85485ab98a7fc6d4\/","StaticLibJsLink":"rainloop\/v\/1.16.0\/static\/js\/min\/libs.min.js?community","StaticAppJsLink":"rainloop\/v\/1.16.0\/static\/js\/min\/app.min.js?community","StaticAppJsNextLink":"rainloop\/v\/1.16.0\/static\/js\/app.next.js?community","StaticEditorJsLink":"rainloop\/v\/1.16.0\/static\/ckeditor\/ckeditor.js?community"});}
[07:48:11.318][9b38137a] INFO[MEMORY]: Memory peak usage: 2MB
[07:48:11.318][9b38137a] INFO[TIME]: Time delta: 0.012088060379028

[07:48:13.314][d9eb3708] INFO[DATA]: [DATE:16.08.21][OFFSET:-00][RL:1.16.0][PHP:7.3.27-1~deb10u1][IP:112.9.209.202][PID:18643][nginx/1.21.0][fpm-fcgi]
[07:48:13.314][d9eb3708] INFO[DATA]: [APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[07:48:13.314][d9eb3708] REQUEST[NOTE]: [POST] https://mail.xxxx.com/?/Ajax/&q[]=/0/
[07:48:13.314][d9eb3708] AJAX[NOTE]: Action: DoLogin
[07:48:13.314][d9eb3708] POST[DATA]: {"Email":"admin@xxxx.com","Login":"","Password":"*******","Language":"","AdditionalCode":"","AdditionalCodeSignMe":"0","SignMe":"1","Action":"Login","XToken":"cada4e670b703470561df70d1998066c"}
[07:48:13.315][d9eb3708] IMAP[NOTE]: Start connection to "tcp://mail.xxxx.com:143"
[07:48:13.321][d9eb3708] IMAP[NOTE]: Connected (success)
[07:48:13.325][d9eb3708] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.\r\n
[07:48:13.325][d9eb3708] IMAP[DATA]: > TAG1 STARTTLS\r\n
[07:48:13.325][d9eb3708] IMAP[DATA]: < TAG1 OK Begin TLS negotiation now.\r\n
[07:48:13.329][d9eb3708] IMAP[DATA]: > TAG2 CAPABILITY\r\n
[07:48:13.329][d9eb3708] IMAP[DATA]: < * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN\r\n
[07:48:13.370][d9eb3708] IMAP[DATA]: < TAG2 OK Pre-login capabilities listed, post-login capabilities have more.\r\n
[07:48:13.371][d9eb3708] IMAP[DATA]: > TAG3 AUTHENTICATE PLAIN\r\n
[07:48:13.371][d9eb3708] IMAP[DATA]: < + \r\n
[07:48:13.371][d9eb3708] IMAP[SECURE]: > *******\r\n
[07:48:13.377][d9eb3708] IMAP[DATA]: < * BYE Internal error occurred. Refer to server log for more information.\r\n
[07:48:13.377][d9eb3708] IMAP[ERROR]: Stream Meta: Array
(
    [crypto] => Array
        (
            [protocol] => TLSv1.2
            [cipher_name] => ECDHE-RSA-AES128-GCM-SHA256
            [cipher_bits] => 128
            [cipher_version] => TLSv1.2
        )

    [timed_out] => 
    [blocked] => 1
    [eof] => 1
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] => 
)

[07:48:13.377][d9eb3708] IMAP[ERROR]: MailSo\Net\Exceptions\SocketReadException: MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 523) in /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Net/NetClient.php:523
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(2095): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(1946): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response))
#2 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(1998): MailSo\Imap\ImapClient->parseResponse('TAG3', false)
#3 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#4 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login('admin@xxxx...', '*******', '', true, false)
#5 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login('admin@xxxx...', '*******', '', true, false)
#6 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2153): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#7 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#8 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2456): RainLoop\Actions->LoginProcess('admin@xxxx...', '*******', 'f8f5e3e2a9c7c27...', '', false)
#9 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#10 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(151): RainLoop\ServiceActions->ServiceAjax('')
#11 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#12 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#13 /var/www/rainloop/rainloop/v/1.16.0/app/handle.php(94): RainLoop\Service::Handle()
#14 /var/www/rainloop/rainloop/v/1.16.0/include.php(243): include('/var/www/rainlo...')
#15 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#16 {main}
[07:48:14.378][d9eb3708] INFO[ERROR]: MailSo\Net\Exceptions\SocketReadException: MailSo-Net-Exceptions-SocketReadException (NetClient.php ~ 523) in /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Net/NetClient.php:523
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(2095): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(1946): MailSo\Imap\ImapClient->partialParseResponseBranch(Object(MailSo\Imap\Response))
#2 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(1998): MailSo\Imap\ImapClient->parseResponse('TAG3', false)
#3 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Imap/ImapClient.php(283): MailSo\Imap\ImapClient->parseResponseWithValidation()
#4 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/MailSo/Mail/MailClient.php(93): MailSo\Imap\ImapClient->Login('admin@xxxx...', '*******', '', true, false)
#5 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Model/Account.php(508): MailSo\Mail\MailClient->Login('admin@xxxx...', '*******', '', true, false)
#6 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2153): RainLoop\Model\Account->IncConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Mail\MailClient), Object(RainLoop\Config\Application), Array)
#7 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#8 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2456): RainLoop\Actions->LoginProcess('admin@xxxx...', '*******', 'f8f5e3e2a9c7c27...', '', false)
#9 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#10 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(151): RainLoop\ServiceActions->ServiceAjax('')
#11 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#12 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#13 /var/www/rainloop/rainloop/v/1.16.0/app/handle.php(94): RainLoop\Service::Handle()
#14 /var/www/rainloop/rainloop/v/1.16.0/include.php(243): include('/var/www/rainlo...')
#15 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#16 {main}

Next RainLoop\Exceptions\ClientException: AuthError[102] in /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php:2182
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2404): RainLoop\Actions->CheckMailConnection(Object(RainLoop\Model\Account), true)
#1 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Actions.php(2456): RainLoop\Actions->LoginProcess('admin@xxxx...', '*******', 'f8f5e3e2a9c7c27...', '', false)
#2 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/ServiceActions.php(174): RainLoop\Actions->DoLogin()
#3 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(151): RainLoop\ServiceActions->ServiceAjax('')
#4 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(62): RainLoop\Service->localHandle()
#5 /var/www/rainloop/rainloop/v/1.16.0/app/libraries/RainLoop/Service.php(85): RainLoop\Service->__construct()
#6 /var/www/rainloop/rainloop/v/1.16.0/app/handle.php(94): RainLoop\Service::Handle()
#7 /var/www/rainloop/rainloop/v/1.16.0/include.php(243): include('/var/www/rainlo...')
#8 /var/www/rainloop/index.php(13): include('/var/www/rainlo...')
#9 {main}
[07:48:14.378][d9eb3708] AJAX[DATA]: {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":1074}
[07:48:14.378][d9eb3708] INFO[MEMORY]: Memory peak usage: 2MB
[07:48:14.379][d9eb3708] INFO[TIME]: Time delta: 1.0749709606171
[07:48:14.379][d9eb3708] IMAP[NOTE]: Disconnected from "tcp://mail.xxxx.com:143" (success)
```

**Comment by the-djmaze** [comment]
> BYE Internal error occurred. Refer to server log for more information.

Did you check the dovecot log?

**Comment by Weltolk** [comment]
> > BYE Internal error occurred. Refer to server log for more information.
> 
> Did you check the dovecot log?

thx for reply

I followed the log tutorial on the dovecot official website and set the dovecot log to a specified location:
https://doc.dovecot.org/admin_manual/logging/#changing-log-file-paths

this is the log of dovecot:
dovecot.log:
```
Aug 20 18:02:16 imap(admin@studiofow.cn): Error: Invalid settings in userdb: userdb returned 0 as uid
Aug 20 18:02:16 imap(admin@studiofow.cn): Warning: Event 0x555e70d07600 leaked (parent=0x555e70cfbcc0): mail-storage-service.c:1324
Aug 20 18:02:16 imap(admin@studiofow.cn): Warning: Event 0x555e70cfbcc0 leaked (parent=(nil)): main.c:248
```

dovecot-info.log:
```
Aug 20 18:01:46 master: Info: Dovecot v2.3.4.1 (f79e8e7e4) starting up for imap (core dumps disabled)
Aug 20 18:02:16 imap-login: Info: Login: user=<admin@studiofow.cn>, method=PLAIN, rip=62.234.126.161, lip=172.21.0.7, mpid=5188, TLS, session=<3Worw/rJsKQ+6n6h>
```

dovecot-debug.log:
none

rainloop log:
same of before

**Comment by Weltolk** [comment]
> > BYE Internal error occurred. Refer to server log for more information.
> 
> Did you check the dovecot log?

solved,It's not rainloop's problem,it's dovecot's problem,I set the dovecot-related user settings to root. In fact, dovecot is not allowed to use root. When I set the dovecot-related user settings to other users, the problem is solved, and rainloop can also log in normally.thx
