### ISSUE TITLE
iCloud CardDav Sync does not work

### ISSUE THREAD

**Issue by nodomain** [RainLoop/rainloop-webmail#358]
Hi,

after setting up CardDav Sync I only receive an error message. My settings:

https://carddav.icloud.com/
User: my Apple ID
Pass: my app specific password
Rainloop 1.6.10.184
Thanks for help...

**Comment by comeara** [comment]
@nodomain Did you ever get this working? I'm trying to accomplish the same.

**Comment by RainLoop** [comment]
Unfortunately I do not have iOS device (Android in my heart. :)) and Apple ID for iCloud.

But, in the settings you need to specify the full URL to your address book.

Something like:
```
https://contacts.icloud.com/addressbooks/users/<Apple ID>/addressbook/
```

But I do not know the correct URL.

**Comment by muhlba91** [comment]
as for the correct URL: I have previously developed a small PHP script which queries the Calendars as well as the Contacts URL which is available here: https://github.com/muhlba91/icloud

The problem with the Contacts server of iCloud is that their server has a WWW-Authentication header with multiple types which is why the Groovy version has problems due to unsufficient support for this in the Apache HttpClient library.

However, it does not seem to be an issue for PHP cURL requests as there it doesn't need any authentication context and, assuming this won't be an issue for RainLoop neither, the URLs provided by the PHP version should work.
(I didn't test it on my own though since I currently just started evaluating RainLoop for my needs.)

In case, someone is eager developing a plugin based on my code, please do so and I would be happy referencing it as well. :)

**Comment by RainLoop** [comment]
@muhlba91 Thanks!

**Comment by RainLoop** [comment]
Should work in the last version.

![image](https://cloud.githubusercontent.com/assets/5530092/7689341/20f8da1e-fdb4-11e4-88fe-e7598b24bd81.png)

**Comment by nodomain** [comment]
Hi - unfortunately it does not work. I entered the data as shown in the screenshot and used an app-specific password. When I click on the "Carddav sync" submenu, a popup is displayed and states "Synchronization error".

**Comment by RainLoop** [comment]
OK, can you give me (support@rainloop.net) RainLoop logs?

**Comment by nodomain** [comment]
Of course, but how do I get them?

**Comment by RainLoop** [comment]
`./data/.../configs/application.ini`
```ini
[logs]
enable = On
```
`./data/.../logs/*`

**Comment by nodomain** [comment]
I am pretty sure that the password was correct...
```
[09:24:01.978][bba8bdb3] DAV[DATA]: PROPFIND 
[09:24:02.376][bba8bdb3] INFO[NOTICE]: exception 'SabreForRainLoop\DAV\Exception\NotAuthenticated' with message 'Not authenticated' in /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/SabreForRainLoop/DAV/Client.php:429
Stack trace:
#0 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/SabreForRainLoop/DAV/Client.php(179): SabreForRainLoop\DAV\Client->request('PROPFIND', '', '<?xml version="...', Array)
#1 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(467): SabreForRainLoop\DAV\Client->propFind('', Array, 1)
#2 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(644): RainLoop\Providers\AddressBook\PdoAddressBook->checkContactsPath(Object(SabreForRainLoop\DAV\Client), '')
#3 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Providers/AddressBook/PdoAddressBook.php(678): RainLoop\Providers\AddressBook\PdoAddressBook->getDavClient('icloud.com', 'x@xx.xxx', 'xxx', '')
#4 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Providers/AddressBook.php(75): RainLoop\Providers\AddressBook\PdoAddressBook->Sync('x@xx.xxx', 'icloud.com', 'x@xx.xxx', 'xxx')
#5 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php(6518): RainLoop\Providers\AddressBook->Sync('x@xx.xxx', 'icloud.com', 'x@xx.xxx', 'xxx')
#6 [internal function]: RainLoop\Actions->DoContactsSync()
#7 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#8 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#9 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#10 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#11 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#12 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/handle.php(83): RainLoop\Service::Handle()
#13 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/include.php(229): include('/var/www/virtua...')
#14 /var/www/virtual/nodomain/html/r/index.php(12): include('/var/www/virtua...')
#15 {main}
[09:24:02.377][bba8bdb3] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'ContactsSyncError[140]' in /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php:6524
Stack trace:
#0 [internal function]: RainLoop\Actions->DoContactsSync()
#1 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#2 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#3 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#4 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#5 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#6 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/app/handle.php(83): RainLoop\Service::Handle()
#7 /var/www/virtual/nodomain/html/r/rainloop/v/1.9.1.333/include.php(229): include('/var/www/virtua...')
#8 /var/www/virtual/nodomain/html/r/index.php(12): include('/var/www/virtua...')
#9 {main}
[09:24:02.377][bba8bdb3] AJAX[DATA]: {"Action":"ContactsSync","Result":false,"ErrorCode":140,"ErrorMessage":"","ErrorMessageAdditional":"","Time":807}
[09:24:02.378][bba8bdb3] INFO[MEMORY]: Memory peak usage: 1024KB
[09:24:02.378][bba8bdb3] INFO[TIME]: Time delta: 0.80765295028687

**Comment by RainLoop** [comment]
@nodomain 
Have you enabled contacts in the iCloud web interface?

**Comment by nodomain** [comment]
Yes. I use iCloud contacts seamlessly also on my iPhone and iPad.

**Comment by ppadovani** [comment]
Not sure why this issue was closed, this is still not functional in the latest release.
