### ISSUE TITLE
Unknown Error when changing IMAP directory or changing page on pagination.

### ISSUE THREAD

**Issue by tarator** [RainLoop/rainloop-webmail#451]
Hi, since a few version I get errors when changing the IMAP-Folder or switch the page (in the pagination)

Here some error logs:

````
[17:46:38.462][d0aa12c3] INFO[DATA]: [DATE:12.02.15][RL:1.8.0.251][PHP:5.6.1][IP:84.113.208.62][PID:5432][Apache][apache2handler]
[17:46:38.462][d0aa12c3] INFO[DATA]: [Suhosin:on][APC:off][MB:on][PDO:mysql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[17:46:38.462][d0aa12c3] REQUEST[NOTE]: [GET] https://www.mydomain.com/mail/?/Ajax/&s=/_<SOME_VERY_LONG_SECRET??_HERE>/MessageList/<SOME_VERY_LONG_SECRET??_HERE>..
[17:46:38.464][d0aa12c3] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'UnknownError[999]' in /some/path/on/server/rainloop/v/1.8.0.251/app/libraries/RainLoop/ServiceActions.php:177
Stack trace:
#0 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#1 /some/path/on/server/rainloop/v/1.8.0.251/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#2 /some/path/on/server/rainloop/v/1.8.0.251/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /some/path/on/server/rainloop/v/1.8.0.251/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /some/path/on/server/rainloop/v/1.8.0.251/app/handle.php(83): RainLoop\Service::Handle()
#5 /some/path/on/server/rainloop/v/1.8.0.251/include.php(230): include('/some/path/...')
#6 /some/path/on/server/index.php(12): include('/some/path/...')
#7 {main}
[17:46:38.464][d0aa12c3] AJAX[DATA]: {"Action":"Unknown","Result":false,"ErrorCode":999,"ErrorMessage":"","ErrorMessageAdditional":"","Time":18}
[17:46:38.469][d0aa12c3] INFO[MEMORY]: Memory peak usage: 4.25MB
[17:46:38.470][d0aa12c3] INFO[TIME]: Time delta: 0.023345947265625
````

I think the problem is, that the GET request doesn't send enough data to the server. This is what the GET-Request sends:
````
/Ajax/=
s=/_<SOME_VERY_LONG_SECRET??_HERE>/MessageList/<SOME_VERY_LONG_SECRET??_HERE>
````
I can't see any payload like `action` or `offset` or something else.
When I click on Refresh the page/folder loads correctly.
I also had this problem in the previous RainLoop versions.

* RainLoop-Version: 1.8.0.251
* OS: Kubuntu 14.10
* Browser: Firefox 35.0.1
* PHP Version: 5.6.1

![rainloopbug](https://cloud.githubusercontent.com/assets/414814/6173809/f1a69b8e-b2ea-11e4-8d38-7cfd72c19442.png)

**Comment by RainLoop** [comment]
Thanks.

**Comment by tarator** [comment]
Thanks! Problem solved!
