### ISSUE TITLE
Cannot login to webmail - probably not working doFolders function

### ISSUE THREAD

**Issue by mostonek** [RainLoop/rainloop-webmail#617]
As in logs - cannot login to my webmail [checked conf on other webmails and it works] because of this action.

```
[17:55:46.698][21a8533c] INFO[DATA]: [DATE:28.04.15][RL:1.8.3.304][PHP:5.4.26][IP:89.70.51.106][PID:21898][Apache][cgi-fcgi]
[17:55:46.698][21a8533c] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls]
[17:55:46.698][21a8533c] REQUEST[NOTE]: [POST] http://wwff.pl/rainloop/?/Ajax/&q[]=/_Ixtdw7-4bn92eOZIFiIF35mGf26jWjdUzQ-j66pczbQIIXAXN21MBIRQNI61_EKyRXqAuNaOGB-j7qlosddCJT1PM547XFACjkOO_HSXM8pV55g6POP44Qu1OvOsiNBndpQzavBMyG7TgYzS5iJJEfxHEIHWCKyTSfHJL1rV8rdB32KGuQnRLlHvgijVGSBlgg3MVzctfDK2AHLOjD5kieuaKmPLr3FERJnAKvSt1T9uv6dhVW-_iDPWZtnnaIPgEzCp6wrg8H7foLg7RfN4084sJX7JFq65KER5s6p2nKyItieGhtJbepRvsCj9cLquyCwFx_6xcuoUKaUjPPFLORrXM4KMI9XoXSs-T4djuC-tDo3Bp6dekJXVsvp5tyJZH4GNxNKP5kE./
[17:55:46.698][21a8533c] AJAX[NOTE]: Action: DoFolders
[17:55:46.698][21a8533c] POST[DATA]: {"Action":"Folders","XToken":"7f7671d3f7cba06c47dbce32833169f6"}
[17:55:46.699][21a8533c] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'AuthError[102]' in /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/Actions.php:1181
Stack trace:
#0 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/Actions.php(1234): RainLoop\Actions->GetAccountFromCustomToken('', true)
#1 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/Actions.php(8305): RainLoop\Actions->getAccountFromToken()
#2 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/Actions.php(5089): RainLoop\Actions->initMailClientConnection()
#3 [internal function]: RainLoop\Actions->DoFolders()
#4 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#5 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#6 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#7 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/app/handle.php(83): RainLoop\Service::Handle()
#10 /home/mostonek/domains/wwff.pl/public_html/rainloop/rainloop/v/1.8.3.304/include.php(228): include('/home/mostonek/...')
#11 /home/mostonek/domains/wwff.pl/public_html/rainloop/index.php(12): include('/home/mostonek/...')
#12 {main}
[17:55:46.699][21a8533c] AJAX[DATA]: {"Action":"Folders","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","ClearAuth":true,"Time":3}
[17:55:46.699][21a8533c] INFO[MEMORY]: Memory peak usage: 1024KB
[17:55:46.699][21a8533c] INFO[TIME]: Time delta: 0.00329494476318
```

**Comment by RainLoop** [comment]
Try to check apache' logs.
Looks like someone is blocking $_GET parameter.

**Comment by mostonek** [comment]
Last entry from access logs looks fine ... somewhere else to look ?

```
89.70.51.106 - - [28/Apr/2015:21:14:13 +0200] "POST /rainloop/?/Ajax/&q[]=/_Ixtdw7-4bn92eOZIFiIF35mGf26jWjdUzQ-j66pczbQIIXAXN21MBIRQNI61_EKyRXqAuNaOGB-j7qlosddCJT1PM547XFACjkOO_HSXM8pV55g6POP44Qu1OvOsiNBndpQzavBMyG7TgYzS5iJJEfxHEIHWCKyTSfHJL1rV8rdB32KGuQnRLlHvgijVGSBlgg3MVzctfDK2AHLOjD5kieuaKmPLr3FERJnAKvSt1T9uv6dhVW-_iDPWZtnnaIPgEzCp6wrg8H7foLg7RfN4084sJX7JFq65KER5s6p2nKyItieGhtJbepRvsCj9cLquyCwFx_6xcuoUKaUjPPFLORrXM4KMI9XoXSs-T4djuC-tDo3Bp6dekJXVsvp5tyJZH4GNxNKP5kE./ HTTP/1.1" 200 1189 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
89.70.51.106 - - [28/Apr/2015:21:14:13 +0200] "GET /rainloop/ HTTP/1.1" 200 2043 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
89.70.51.106 - - [28/Apr/2015:21:14:14 +0200] "GET /rainloop/rainloop/v/1.8.3.304/static/css/app.min.css HTTP/1.1" 304 210 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
89.70.51.106 - - [28/Apr/2015:21:14:14 +0200] "GET /rainloop/rainloop/v/1.8.3.304/static/js/min/boot.js HTTP/1.1" 304 210 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
89.70.51.106 - - [28/Apr/2015:21:14:14 +0200] "GET /rainloop/?/AppData/_Ixtdw7-4bn92eOZIFiIF35mGf26jWjdUzQ-j66pczbQIIXAXN21MBIRQNI61_EKyRXqAuNaOGB-j7qlosddCJT1PM547XFACjkOO_HSXM8pV55g6POP44Qu1OvOsiNBndpQzavBMyG7TgYzS5iJJEfxHEIHWCKyTSfHJL1rV8rdB32KGuQnRLlHvgijVGSBlgg3MVzctfDK2AHLOjD5kieuaKmPLr3FERJnAKvSt1T9uv6dhVW-_iDPWZtnnaIPgEzCp6wrg8H7foLg7RfN4084sJX7JFq65KER5s6p2nKyItieGhtJbepRvsCj9cLquyCwFx_6xcuoUKaUjPPFLORrXM4KMI9XoXSs-T4djuC-tDo3Bp6dekJXVsvp5tyJZH4GNxNKP5kE./20368940802291036/ HTTP/1.1" 200 2381 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
89.70.51.106 - - [28/Apr/2015:21:14:14 +0200] "GET /rainloop/?/Css/0/User/-/Default/-/c6f013dd8ad9567b7309f1c9bce3cf39/Hash/-/ HTTP/1.1" 304 277 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
89.70.51.106 - - [28/Apr/2015:21:14:14 +0200] "POST /rainloop/?/Ajax/&q[]=/_3KDWS8YfnpFpPbVtxHorkMZ1UrJitIA8Lm5Fq4oXa9KMZDJeuudzAc4bxglyNxmI-buXmxuw04fLMAQYsHKnTsPW-XMtm7w1e5nGFTi0wMQ83Y4w6AildYxCCeQBBaNgSaVEy0n1QT9-Ww51zW0HuhHtBW5CuYPX7N_rr7h-HOqojtjEr4EaKTPKjepJ5p1za5EZTIgMo532ZM1gZm7sFKaCCx78_6Asjv7fANlHL6aNQ7Sxl07BP6CvkqY5b4PA6IPpjWkDQQtaS3A_XXOK95P083XvktkolSn3J1VzFHN1a6zipkQcskFeKPkdWrX8khlDUOicnRPe_FcYkdZOXuhf2SZolC6Hw5WHdAgHWS3okVqXa79eCu-1Ka7lQj-9MBoax9Pad6I./ HTTP/1.1" 200 595 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
89.70.51.106 - - [28/Apr/2015:21:14:15 +0200] "GET /rainloop/rainloop/v/1.8.3.304/static/css/fonts/rainloop.woff HTTP/1.1" 304 209 "http://wwff.pl/rainloop/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
```

**Comment by RainLoop** [comment]
It looks like access log, what error log says?

**Comment by mostonek** [comment]
No errors in error log

**Comment by RainLoop** [comment]
Well, I have no idea.
Maybe "mod_security"?
