### ISSUE TITLE
stream_socket_client() unable to connect to tcp://143 (Connection timed out)

### ISSUE THREAD

**Issue by NemediDev** [RainLoop/rainloop-webmail#684]
Hey guys! :smile:

My current RainLoop installation cannot connect to any IMAP server, here it is a pic with all connection tests:

![All tests](http://s29.postimg.org/l1bpiyuyv/webmail.jpg)

I have just enable the logging in the "application.ini" file and this is the segment with the GMail error:

```
[05:29:23.279][73808db8] INFO[DATA]: [DATE:22.05.15][RL:1.9.1.330][PHP:5.4.34][IP:190.8.250.77][PID:4098][Apache][cgi-fcgi]
[05:29:23.280][73808db8] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls]
[05:29:23.280][73808db8] REQUEST[NOTE]: [POST] http://mydomain.com/?/Ajax/&q%5B%5D=/0/
[05:29:23.286][73808db8] AJAX[NOTE]: Action: DoAdminDomainLoad
[05:29:23.286][73808db8] POST[DATA]: {"Name":"gmail.com","Action":"AdminDomainLoad","XToken":"f8bc83f506b929aeeeccef7bd14e2815"}
[05:29:23.295][73808db8] AJAX[DATA]: {"Action":"AdminDomainLoad","Result":{"@Object":"Object\/Domain","Name":"gmail.com","IncHost":"imap.gmail.com","IncPort":993,"IncSecure":1,"IncShortLogin":false,"UseSieve":false,"SieveHost":"","SievePort":4190,"SieveSecure":0,"SieveAllowRaw":false,"OutHost":"smtp.gmail.com","OutPort":465,"OutSecure"...
[05:29:23.311][73808db8] INFO[MEMORY]: Memory peak usage: 4.75MB
[05:29:23.312][73808db8] INFO[TIME]: Time delta: 0.093016862869263

[05:29:27.083][575ace4d] INFO[DATA]: [DATE:22.05.15][RL:1.9.1.330][PHP:5.4.34][IP:190.8.250.77][PID:4098][Apache][cgi-fcgi]
[05:29:27.084][575ace4d] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls]
[05:29:27.084][575ace4d] REQUEST[NOTE]: [POST] http://mydomain.com/?/Ajax/&q%5B%5D=/0/
[05:29:27.089][575ace4d] AJAX[NOTE]: Action: DoAdminDomainTest
[05:29:27.089][575ace4d] POST[DATA]: {"Name":"gmail.com","IncHost":"imap.gmail.com","IncPort":"993","IncSecure":"1","UseSieve":"0","SieveHost":"","SievePort":"4190","SieveSecure":"0","OutHost":"smtp.gmail.com","OutPort":"465","OutSecure":"1","OutAuth":"1","OutUsePhpMail":"0","Action":"AdminDomainTest","XToken":"f8bc83f506b929aeeeccef7bd14e2815"}
[05:29:27.103][575ace4d] IMAP[NOTE]: Start connection to "ssl://imap.gmail.com:993"
[05:29:32.168][575ace4d] IMAP[NOTE]: Connected (unsuccess)
[05:29:32.168][575ace4d] IMAP[NOTICE]: Socket: [2] stream_socket_client(): unable to connect to ssl://imap.gmail.com:993 (Connection timed out)
[05:29:32.168][575ace4d] IMAP[NOTICE]: exception 'MailSo\Net\Exceptions\SocketCanNotConnectToHostException' with message 'Can't connect to host "ssl://imap.gmail.com:993"' in /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/libraries/MailSo/Net/NetClient.php:292
Stack trace:
#0 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/libraries/MailSo/Imap/ImapClient.php(153): MailSo\Net\NetClient->Connect('imap.gmail.com', 993, 1, false, true)
#1 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/libraries/RainLoop/Actions.php(3963): MailSo\Imap\ImapClient->Connect('imap.gmail.com', 993, 1, false, true)
#2 [internal function]: RainLoop\Actions->DoAdminDomainTest()
#3 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#4 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#5 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#6 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#7 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#8 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/app/handle.php(83): RainLoop\Service::Handle()
#9 /hsphere/local/home/apache/mydomain.com/rainloop/v/1.9.1.330/include.php(228): include('/hsphere/local/...')
#10 /hsphere/local/home/apache/mydomain.com/index.php(12): include('/hsphere/local/...')
#11 {main}
[05:29:32.170][575ace4d] SMTP[NOTE]: Start connection to "ssl://smtp.gmail.com:465"
[05:29:32.362][575ace4d] SMTP[NOTE]: Connected (success)
[05:29:32.362][575ace4d] SMTP[DATA]: < 220 mx.google.com ESMTP 143sm461478qhw.21 - gsmtp\r\n
[05:29:32.363][575ace4d] SMTP[DATA]: > EHLO mydomain.com\r\n
[05:29:32.409][575ace4d] SMTP[DATA]: < 250-mx.google.com at your service, [173.0.137.156]\r\n
[05:29:32.409][575ace4d] SMTP[DATA]: < 250-SIZE 35882577\r\n
[05:29:32.409][575ace4d] SMTP[DATA]: < 250-8BITMIME\r\n
[05:29:32.410][575ace4d] SMTP[DATA]: < 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN XOAUTH\r\n
[05:29:32.410][575ace4d] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n
[05:29:32.410][575ace4d] SMTP[DATA]: < 250-PIPELINING\r\n
[05:29:32.410][575ace4d] SMTP[DATA]: < 250-CHUNKING\r\n
[05:29:32.410][575ace4d] SMTP[DATA]: < 250 SMTPUTF8\r\n
[05:29:32.411][575ace4d] SMTP[NOTE]: Disconnected from "ssl://smtp.gmail.com:465" (success)
[05:29:32.411][575ace4d] AJAX[DATA]: {"Action":"AdminDomainTest","Result":{"Imap":"stream_socket_client(): unable to connect to ssl:\/\/imap.gmail.com:993 (Connection timed out)","Smtp":true,"Sieve":true},"Time":5381}
[05:29:32.419][575ace4d] INFO[MEMORY]: Memory peak usage: 5MB
[05:29:32.419][575ace4d] INFO[TIME]: Time delta: 5.3864929676056
```
Here are some relative specs -I think! :hushed:- of the PHP configuration:

![Specs](http://s23.postimg.org/w0b6fe14r/php.jpg)

So, my question is: ¿anyone knows any way to fix this?

Thanks in advance!!!

:smiley: :+1:

**Comment by alexzeitgeist** [comment]
Did you check if you have firewall rules in place?

**Comment by Emsanator** [comment]
@alexzeitgeist I have same problem but I solved with your answer. 
Thank you! 
From Turkey

**Comment by krsdata** [comment]
I have same problem. Can anyone help me?

**Comment by laoxia123** [comment]
me too

**Comment by Virksaabnavjot** [comment]
for me using mail.mrvirk.com worked instead of just using the domain mrvirk.com

hope this helps
