### ISSUE TITLE
Can login / Can't send emails

### ISSUE THREAD

**Issue by pyheme** [RainLoop/rainloop-webmail#813]
Hi all, 
I have Rainloop installed on the same server as Postfix and Dovecot. The mail server runs virtual users across multiple domains. Dovecot is configured in Postfix to handle SASL. 

I can log in in Rainloop on my various email accounts without problem, whether using or not the STARTTLS and SSL protocols. 

The issue is that, once logged in, I cannot send emails from within Rainloop. It throws the error "Can't authenticate" but doesn't give more info.  Looking at either Rainloop and Postfix/Dovecot logs, I can’t identify the origin of the issue. 

I'm successfully running Roundcube on this server (which I am trying to replace for Rainloop) and can send emails from my phone/outlook without problem (enabling authentication and with or without STARTTLS). 

I'm attaching below the Rainloop logs when sending an email:

<pre>
[00:45:15.087][6c2212be] INFO[DATA]: [DATE:24.08.15][RL:1.9.1.333][PHP:5.5.9-1ubuntu4.11][IP:40.50.60.70][PID:16841][Apache/2.4.7 (Ubuntu)][apache2handler]
[00:45:15.087][6c2212be] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql,pgsql,sqlite][Streams:tcp,udp,unix,udg,ssl,sslv3,tls]
[00:45:15.087][6c2212be] REQUEST[NOTE]: [POST] https://mail.domain.tld/?/Ajax/&q[]=/_ESLQLce29NrAoe6NJ9Xx6br_SVRx1ck3nlV53vhz4E3EjxnUvj-f1Pe-mCkudyF-C4GJ2ADOA8_eosnFbQP3pgFo1xkEDNQCxM7NOhXYm5kDmxTiKprd1oOucJvX69qB_qHgCFTpVzcfFt8MsuqeohmA9zvWXNxnf7t2pQ8WZiUUKK0z9wR2UCiPa1P7sfdVBMMjDkdAp3ezDnLVF8d-Cg6TNSgZ30MieUTpvwgdHdh-f0nmD10KnX2b5Z5pXn2SFCsW2dEhKRl8PnwVkXGVu0GzOzkk4X1SIjD8nV-LMZ0mFj-00yNv-7U8PEm8zPedlJE8FA../
[00:45:15.088][6c2212be] AJAX[NOTE]: Action: DoSendMessage
[00:45:15.088][6c2212be] POST[DATA]: {"IdentityID":"","MessageFolder":"Drafts","MessageUid":"76","SentFolder":"Sent","To":"pierre@otherdomain.tld","Cc":"","Bcc":"","ReplyTo":"","Subject":"test sasl","TextIsHtml":"1","Text":"Testing authentication.","DraftInfo":"","InReplyTo":"","References":"","Dsn":"0","ReadReceiptRequest":"0","MarkAsImportant":"0","Action":"SendMessage","XToken":"57dd838ba89bf66554bc797a5e95ffe5"}
[00:45:15.088][6c2212be] PLUGIN[NOTE]: Hook: ajax.action-pre-call
[00:45:15.091][6c2212be] IMAP[NOTE]: Start connection to "tcp://mail.domain.tld:143"
[00:45:15.091][6c2212be] IMAP[NOTE]: Connected (success)
[00:45:15.099][6c2212be] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot (Ubuntu) ready.\r\n
[00:45:15.099][6c2212be] IMAP[DATA]: > TAG1 STARTTLS\r\n
[00:45:15.100][6c2212be] IMAP[DATA]: < TAG1 OK Begin TLS negotiation now.\r\n
[00:45:15.115][6c2212be] IMAP[SECURE]: > TAG2 LOGIN "pierre@domain.tld" "********"\r\n
[00:45:15.123][6c2212be] IMAP[DATA]: < TAG2 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS SPECIAL-USE BINARY MOVE] Logged in\r\n
[00:45:15.127][6c2212be] PLUGIN[NOTE]: Hook: filter.build-message
[00:45:15.130][6c2212be] SMTP[NOTE]: Start connection to "ssl://mail.domain.tld:465"
[00:45:15.159][6c2212be] SMTP[NOTE]: Connected (success)
[00:45:15.198][6c2212be] SMTP[DATA]: < 220 mail.domain.tld ESMTP Postfix\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: > EHLO mail.domain.tld\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-mail.domain.tld\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-PIPELINING\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-SIZE 31457280\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-ETRN\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-8BITMIME\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250 DSN\r\n
[00:45:15.200][6c2212be] SMTP[NOTICE]: exception 'MailSo\Smtp\Exceptions\LoginBadMethodException' with message 'MailSo-Smtp-Exceptions-LoginBadMethodException (SmtpClient.php ~ 264)' in /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/MailSo/Smtp/SmtpClient.php:264
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Model/Account.php(517): MailSo\Smtp\SmtpClient->Login('pierre@domain.c...', '*******')
#1 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php(6039): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#2 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php(6197): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #29, 2086, false, true)
#3 [internal function]: RainLoop\Actions->DoSendMessage()
#4 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#5 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#6 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#7 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/www/rainloop/rainloop/v/1.9.1.333/app/handle.php(83): RainLoop\Service::Handle()
#10 /var/www/rainloop/rainloop/v/1.9.1.333/include.php(229): include('/var/www/rainlo...')
#11 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#12 {main}
[00:45:15.200][6c2212be] PLUGIN[NOTE]: Hook: filter.ajax-response
[00:45:15.201][6c2212be] INFO[ERROR]: exception 'MailSo\Smtp\Exceptions\LoginBadMethodException' with message 'MailSo-Smtp-Exceptions-LoginBadMethodException (SmtpClient.php ~ 264)' in /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/MailSo/Smtp/SmtpClient.php:264
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Model/Account.php(517): MailSo\Smtp\SmtpClient->Login('pierre@domain.c...', '*******')
#1 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php(6039): RainLoop\Model\Account->OutConnectAndLoginHelper(Object(RainLoop\Plugins\Manager), Object(MailSo\Smtp\SmtpClient), Object(RainLoop\Config\Application), false)
#2 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php(6197): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #29, 2086, false, true)
#3 [internal function]: RainLoop\Actions->DoSendMessage()
#4 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#5 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#6 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#7 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/www/rainloop/rainloop/v/1.9.1.333/app/handle.php(83): RainLoop\Service::Handle()
#10 /var/www/rainloop/rainloop/v/1.9.1.333/include.php(229): include('/var/www/rainlo...')
#11 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#12 {main}

Next exception 'RainLoop\Exceptions\ClientException' with message 'AuthError[102]' in /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php:6138
Stack trace:
#0 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Actions.php(6197): RainLoop\Actions->smtpSendMessage(Object(RainLoop\Model\Account), Object(MailSo\Mime\Message), Resource id #29, 2086, false, true)
#1 [internal function]: RainLoop\Actions->DoSendMessage()
#2 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#3 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#4 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#5 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#6 /var/www/rainloop/rainloop/v/1.9.1.333/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#7 /var/www/rainloop/rainloop/v/1.9.1.333/app/handle.php(83): RainLoop\Service::Handle()
#8 /var/www/rainloop/rainloop/v/1.9.1.333/include.php(229): include('/var/www/rainlo...')
#9 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#10 {main}
[00:45:15.201][6c2212be] AJAX[DATA]: {"Action":"SendMessage","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":118}
[00:45:15.201][6c2212be] SMTP[DATA]: > QUIT\r\n
[00:45:15.201][6c2212be] SMTP[DATA]: < 221 2.0.0 Bye\r\n
[00:45:15.201][6c2212be] SMTP[NOTE]: Disconnected from "ssl://mail.domain.tld:465" (success)
[00:45:15.204][6c2212be] IMAP[DATA]: > TAG3 LOGOUT\r\n
[00:45:15.204][6c2212be] IMAP[DATA]: < * BYE Logging out\r\n
[00:45:15.204][6c2212be] IMAP[DATA]: < TAG3 OK Logout completed.\r\n
[00:45:15.205][6c2212be] IMAP[NOTE]: Disconnected from "tcp://mail.domain.tld:143" (success)
[00:45:15.205][6c2212be] INFO[MEMORY]: Memory peak usage: 4.25MB
[00:45:15.205][6c2212be] INFO[TIME]: Time delta: 0.12205696105957
</pre>

Obviously something is not working in the authentication but I can’t figure out what!

The /var/log/mail.log log does not give much more info, even when adding more details (timezones are off, looks like my Rainloop log is on UTC):

<pre>
Aug 23 18:45:15 main dovecot: imap-login: Login: user=<pierre@domain.tld>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=17755, TLS, session=<twXK7gGe6AB/AAAB>
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: warning: dict_nis_init: NIS domain name not set - NIS lookups disabled
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: initializing the server-side TLS engine
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: connect from localhost.localdomain[127.0.0.1]
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: setting up TLS connection from localhost.localdomain[127.0.0.1]
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: localhost.localdomain[127.0.0.1]: TLS cipher list "aNULL:-aNULL:ALL:!EXPORT:!LOW:+RC4:@STRENGTH"
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:before/accept initialization
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 read client hello A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 write server hello A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 write certificate A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 write key exchange A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 write server done A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 flush data
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 read client key exchange A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 read finished A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 write change cipher spec A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 write finished A
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: SSL_accept:SSLv3 flush data
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: Anonymous TLS connection established from localhost.localdomain[127.0.0.1]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Aug 23 18:45:15 main dovecot: imap(pierre@domain.tld): Disconnected: Logged out in=11 out=401
Aug 23 18:45:15 main postfix/smtps/smtpd[17756]: disconnect from localhost.localdomain[127.0.0.1]
Aug 23 18:45:15 main dovecot: imap-login: Login: user=<pierre@domain.tld>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=17758, TLS, session=<pxlN7gMe9wB/AAAB>
Aug 23 18:45:15 main dovecot: imap(pierre@domain.tld): Disconnected: Logged out in=200 out=2023
</pre>

Am I missing something obvious here?  Is there a setting in Rainloop to define how to authenticate (plain and login enabled in Dovecot)?

Thanks in advance for any help or guidance here.

[EDIT] Just upgraded to the latest (Community) version v1.9.2.353 but the problem persists.

Pierre

**Comment by RainLoop** [comment]
Your SMTP server odes not retern AUTH information in EHLO request
```
[00:45:15.199][6c2212be] SMTP[DATA]: > EHLO mail.domain.tld\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-mail.domain.tld\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-PIPELINING\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-SIZE 31457280\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-ETRN\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-ENHANCEDSTATUSCODES\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250-8BITMIME\r\n
[00:45:15.199][6c2212be] SMTP[DATA]: < 250 DSN\r\n
```
As you can see, there is no any information about AUTH.
Of course, I could try to make a simple authentication in this case, but I do it more strictly.

Correct answer for example :
```
[16:48:19.833][abd2afe8] SMTP[NOTE]: Start connection to "tcp://127.0.0.1:25"
[16:48:19.837][abd2afe8] SMTP[NOTE]: Connected (success)
[16:48:19.844][abd2afe8] SMTP[DATA]: < 220 xxx ESMTP
[16:48:19.846][abd2afe8] SMTP[DATA]: > EHLO demo.rainloop.net
[16:48:19.851][abd2afe8] SMTP[DATA]: < 250-SIZE 20480000
[16:48:19.853][abd2afe8] SMTP[DATA]: < 250 AUTH LOGIN  <---- here
```

**Comment by pyheme** [comment]
You're absolutely right!
Just in case others have the same problem and land there, I had in my Postfix's main.cf the following option that prevented returning the AUTH options to IPs listed in mynetwork:
smtpd_sasl_exceptions_networks = $mynetworks

Commenting the line out restored the 250 AUTH line in the response to EHLO and allowed my Rainloop install to send emails.

Thanks,
Pierre

**Comment by devpuck** [comment]
Hi ，I have the same question，but I don't have smtpd_sasl_exceptions_networks...

**Comment by ervee** [comment]
'''
If you get no AUTH header on the EHLO response; then
  Check mailserver config
else
  Disable SMTP authentication in RainLoop
fi
'''
