### ISSUE TITLE
Try to Update Identity (DEFAULT) returns "Invalid input argument"

### ISSUE THREAD

**Issue by arturbonnett** [RainLoop/rainloop-webmail#845]
Only on Default Identity updating (where email input is locked) is not possible to update: "Invalid input argument".

![settings-rainloop](https://cloud.githubusercontent.com/assets/7110872/10312757/f1fc652c-6c22-11e5-815f-5da947479f1c.png)

**Comment by arturbonnett** [comment]
```log
--- FlushLogCache: WriteOnErrorOnly
[22:31:59.270][a805053b] INFO[DATA]: [DATE:28.10.15][RL:1.9.3.363][PHP:5.6.13][IP:180.2.222.277][PID:15433][Apache][cgi-fcgi]
[22:31:59.270][a805053b] INFO[DATA]: [Suhosin:on][APC:off][MB:on][PDO:sqlite,mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,sslv2,tls,tlsv1.0,tlsv1.1,tlsv1.2]
[22:31:59.270][a805053b] REQUEST[NOTE]: [POST] https://example.com/?/Ajax/&q[]=/_MsdMnrFGZl3JKabzWSTWz3kv03rpO5u3tCElhwyT_xT3dtVzu-noKskGjpSZuikTm3enV3NGpRl7sIpvDp9TWby8P2YQfy_MA9QkBwWJQZgKkHSaq3O3mTAfdqyiORIWm5PPW1qw2JHRg6Lj_PNFH3mWy1dqrANlhUF3GnTsAW4L6ikAGHgustfUdVuu58MpbMeQ49JRmJHAxLAd870Wwux4ps07bJRE_BqnHydFCqOOCH_sQ7Nmqz1pcrElzg6JSkrfWSA3KNd_QPkbvFmekmhSnhMI_seJSX3lEug-gxJuyxuqifu3jBdKTubGVQy037wHGUWtJsfNAjrbWBIOR3-jA1mbbL3_X3tGDA../
[22:31:59.272][a805053b] AJAX[NOTE]: Action: DoIdentityUpdate
[22:31:59.272][a805053b] POST[DATA]: {"Email":"test@example.com","Name":"My Name!","SignatureInsertBefore":"0","Action":"IdentityUpdate","XToken":"b8427e99da1b7fd3f688a342c2198e21"}
[22:31:59.272][a805053b] PLUGIN[NOTE]: Hook: ajax.action-pre-call
--- FlushLogCache: Trigger
[22:31:59.277][a805053b] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientException' with message 'InvalidInputArgument[903]' in /home/example/rainloop/v/1.9.3.363/app/libraries/RainLoop/Actions.php:3049
Stack trace:
#0 [internal function]: RainLoop\Actions->DoIdentityUpdate()
#1 /home/example/rainloop/v/1.9.3.363/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#2 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#3 /home/example/rainloop/v/1.9.3.363/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#4 /home/example/rainloop/v/1.9.3.363/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#5 /home/example/rainloop/v/1.9.3.363/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#6 /home/example/rainloop/v/1.9.3.363/app/handle.php(83): RainLoop\Service::Handle()
#7 /home/example/rainloop/v/1.9.3.363/include.php(228): include('/home/...')
#8 /home/example/index.php(12): include('/home/...')
#9 {main}
[22:31:59.277][a805053b] PLUGIN[NOTE]: Hook: filter.ajax-response
[22:31:59.277][a805053b] AJAX[DATA]: {"Action":"IdentityUpdate","Result":false,"ErrorCode":903,"ErrorMessage":"","ErrorMessageAdditional":"","Time":30}
[22:31:59.283][a805053b] INFO[MEMORY]: Memory peak usage: 5.25MB
[22:31:59.283][a805053b] INFO[TIME]: Time delta: 0.035973072052```

**Comment by arturbonnett** [comment]
This is only happening to me? @RainLoop

**Comment by RainLoop** [comment]
is this issue still relevant?

> This is only happening to me?

Yes.

**Comment by arturbonnett** [comment]
> is this issue still relevant?
No, this problem stopped after rainloop upgrade. Thanks! Regards
