### ISSUE TITLE
Cannot save modified filters (managesieve) due to "Invalid Token"

### ISSUE THREAD

**Issue by wildtree** [RainLoop/rainloop-webmail#861]
RainLoop v1.9.3.363
Imap Server (managesieve server): Dovecot v2.2.19 + Pigeonhole 0.4.9
Http Server: Apache 2.2.31
PHP: 5.5.30 (post_max_size=64M/upload_max_filesize = 32M/memory_limt = 256M)

Invalid Token error is happened when I added a new filter rule and hit Save button.
Is there any work around?

I can reorder existing rules and can save it.
But, I cannot add any new condition into existing rule, and cannot add any new filter...  these operation causes 'Invalid Token' error.

$this->oHttp->GetAction('Action', null) on ServiceAction.php returns null when the issue occurs,
The stack trace is below:

[05:35:43.627][7d6885d8] INFO[NOTICE]: exception 'RainLoop\Exceptions\ClientExce
ption' with message 'InvalidToken[101]' in /var/www/rainloop/rainloop/v/1.9.3.36
3/app/libraries/RainLoop/ServiceActions.php:125
Stack trace:
#0 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#1 /var/www/rainloop/rainloop/v/1.9.3.363/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#2 /var/www/rainloop/rainloop/v/1.9.3.363/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#3 /var/www/rainloop/rainloop/v/1.9.3.363/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#4 /var/www/rainloop/rainloop/v/1.9.3.363/app/handle.php(83): RainLoop\Service::Handle()
#5 /var/www/rainloop/rainloop/v/1.9.3.363/include.php(228): include('/var/www/rainlo...')
#6 /var/www/rainloop/index.php(12): include('/var/www/rainlo...')
#7 {main}
[05:35:43.630][7d6885d8] AJAX[DATA]: {"Action":"Unknown","Result":false,"ErrorCode":101,"ErrorMessage":"","ErrorMessageAdditional":"","Time":177}

--
Thank you,

**Comment by RainLoop** [comment]
- Interesting, there are no differences between these requests.

- There is no such line. `$this->oHttp->GetAction('Action', null)`
Did you mean? - `$this->oHttp->GetPost('Action', null);`

- Does your server (or apache) contain any protection program (seLinux or something similar)?

**Comment by wildtree** [comment]
Yes, I meant $this->oHttp->GetPost('Action', null)
No, my server contains such...

**Comment by russel-online** [comment]
Any update?

I also have this problem with latest version.

**Comment by russel-online** [comment]
The same problem is here #1274 and here #1137 

Problem with a lot of filters.

**Comment by WladyX** [comment]
I get the same error, i cannot submit rule 21, everything is fine until i create rule 21.
