### ISSUE TITLE
Can't get message list for large mailbox - Version 1.9.3.365

### ISSUE THREAD

**Issue by rgudwin** [RainLoop/rainloop-webmail#903]
Hi,
I upgraded Rainloop from version 1.8.1.266 to 1.9.3.365. I have a very large mailbox, with more than 180000 messages. In the older version (1.8.1.266) rainloop was working most of the times. Sometimes I used to have the "Can't get message list", but most of the times the system used to work. Now, after installing 1.9.3.365, I get this message all the times I try to open the folder with 180000 messages. I tried many different tweeks in the application.ini file, following advices from [issue 253](https://github.com/RainLoop/rainloop-webmail/issues/253) and [issue 267](https://github.com/RainLoop/rainloop-webmail/issues/267) . I also found the following lines in the log:
 
[18:54:52.731][30f99981] IMAP[DATA]: > TAG5 UID SORT (REVERSE ARRIVAL) US-ASCII UNDELETED\r\n
[18:54:52.953][30f99981] IMAP[ERROR]: Stream Meta: Array
(
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] => 
    [timed_out] => 
    [blocked] => 1
    [eof] => 1
)

[18:54:52.954][30f99981] IMAP[ERROR]: exception 'MailSo\Net\Exceptions\SocketReadException' with message 'MailSo-Net-Exceptions-Soc
ketReadException (NetClient.php ~ 515)' in /var/www/webmail/rainloop/v/1.9.3.365/app/libraries/MailSo/Net/NetClient.php:515

Do you have any additional clue on why it used to work with the older version and why it is not working anymore ? I would guess it has to do with the [labs] section of application.ini, but I'm afraid the old application.ini is not available anymore, after I upgraded. The interesting thing is that very occasionally, it completes and renders the mailbox correctly, but in a few seconds, it starts getting the list again and it fails. It seems to be some sort of timeout, due to the large size of my mailbox.

**Comment by rgudwin** [comment]
I downloaded the last code from GitHub and compiled version 1.9.4.387. It indeed allowed me to access my mailbox. Now I don't have the "Can't get message list" during ordinary use. But I am still having the "Can't get message list" error while doing a search. I am appending the log for the search. It is interesting because it appears that the search was concluded, for what is in the log. Nevertheless, the message "Can't get message list" appeared before the search was concluded (more or less by the time [20:19:56.250]). I really could not understand what happened. Maybe the system simply got a timeout before the conclusion of the search, and did not refreshed latter ?  

[20:19:23.205][73ee40be] INFO[DATA]: [DATE:07.01.16][RL:1.9.4.387][PHP:5.5.9-1ubuntu4.9][IP:143.106.50.173][PID:29024][Apache/2.4.7 (Ubu
ntu)][apache2handler]
[20:19:23.205][73ee40be] INFO[DATA]: [Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls]
[20:19:23.205][73ee40be] REQUEST[NOTE]: [POST] http://leme.dca.fee.unicamp.br/webmail/?/Ajax/&q[]=/_Pa6ePEOok-cICDwH6X_sMpgGvrIozWJeZVqc
am4tbEEH3oZ_aZixnEuNhooIC-TcFcSjxFSm0MliAIi5v9zmB8cTAY2bjH4JV80DOJSKvKrmK9Sm9R8WMiWlwSG6mhisCOw9MtEgeGVAqzXRjogUZ3TUjuh-QhTi2xOYgKy5gPq-
wmL_NqFct32kQwmFBUcpU3lgaJoqX5vbZ-xdSCJQXhf4v9Es-MAuW20WDgfyd5wb9b_pjxX_R1x5Y641YY0gnUrsUWaP4WWvYoh1lQtWY4eiul6lYXmWaLo4q7ZK5xXRgmVGhJpI
gKTmoChtay99qWCPzZeDcvYB0qn8BrxL7_IbkQAvzg1F/

[20:19:23.205][73ee40be] AJAX[NOTE]: Action: DoMessageList
[20:19:23.205][73ee40be] POST[DATA]: {"Folder":"INBOX","Offset":"0","Limit":"100","Search":"ericsson.com.br","UidNext":"181615","UseThre
ads":"0","ThreadUid":"","Action":"MessageList","XToken":"f7466d332d12c1edb2fdf05405bafa21"}
[20:19:23.209][73ee40be] IMAP[NOTE]: Start connection to "ssl://imap.dca.fee.unicamp.br:993"
[20:19:23.228][73ee40be] IMAP[NOTE]: Connected (success)
[20:19:23.267][73ee40be] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot re
ady.

[20:19:23.268][73ee40be] IMAP[SECURE]: > TAG1 LOGIN "gudwin" "********"

[20:19:23.286][73ee40be] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY T
HREAD=REFERENCES THREAD=REFS MULTIAPPEND UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT S
EARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS] Logged in

[20:19:23.288][73ee40be] IMAP[DATA]: > TAG2 SELECT "INBOX"

[20:19:23.297][73ee40be] IMAP[DATA]: < * FLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk $Forwarded $NotJunk $Junk)

[20:19:23.297][73ee40be] IMAP[DATA]: < * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft NonJunk $Forwarded $NotJunk $Junk 
\*)] Flags permitted.

[20:19:23.297][73ee40be] IMAP[DATA]: < * 175727 EXISTS

[20:19:23.298][73ee40be] IMAP[DATA]: < * 0 RECENT

[20:19:23.298][73ee40be] IMAP[DATA]: < * OK [UNSEEN 19] First unseen.

[20:19:23.298][73ee40be] IMAP[DATA]: < * OK [UIDVALIDITY 1355780416] UIDs valid

[20:19:23.298][73ee40be] IMAP[DATA]: < * OK [UIDNEXT 181615] Predicted next UID

[20:19:23.298][73ee40be] IMAP[DATA]: < * OK [HIGHESTMODSEQ 6559] Highest

[20:19:23.298][73ee40be] IMAP[DATA]: < TAG2 OK [READ-WRITE] Select completed.

[20:19:23.299][73ee40be] IMAP[DATA]: > TAG3 CAPABILITY

[20:19:23.299][73ee40be] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=R
EFERENCES THREAD=REFS MULTIAPPEND UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRE
S WITHIN CONTEXT=SEARCH LIST-STATUS

[20:19:23.300][73ee40be] IMAP[DATA]: < TAG3 OK Capability completed.

[20:19:23.300][73ee40be] IMAP[DATA]: > TAG4 STATUS "INBOX" (MESSAGES UNSEEN UIDNEXT HIGHESTMODSEQ)

[20:19:23.300][73ee40be] IMAP[DATA]: < * OK [HIGHESTMODSEQ 6559] Highest

[20:19:23.301][73ee40be] IMAP[DATA]: < * STATUS "INBOX" (MESSAGES 175727 UIDNEXT 181615 UNSEEN 175530 HIGHESTMODSEQ 6559)

[20:19:23.301][73ee40be] IMAP[DATA]: < TAG4 OK [CLIENTBUG] Status on selected mailbox completed.

[20:19:23.454][73ee40be] IMAP[DATA]: > TAG5 UID SORT (REVERSE ARRIVAL) US-ASCII UNDELETED

[20:19:25.263][73ee40be] IMAP[DATA]: [cutted:1120072] < * SORT 181614 181613 181612 181611 181610 181609 181608 181607 181606 181605 181
604 181603 181602 181601 181600 181599 181598 181597 181596 181595 181594 181593 181592 181591 181590 181589 181588 181587 181586 181585
 181584 181583 181582 181581 181580 181579 181578 181577 181576 181575 181574 181573 181572 181571 181570 181569 181568 181567 181566 18
1565 181564 181563 181562 181561 181560 181559 181558 181557 181556 181555 181554 181553 181552 181551 181550 181549 181548 181547 18154
6 181545 181544 181543 181542 181541 181540 181539 181538 181537 181536 181535 181534 181533 181532 181531 181530 181529 181528 181527 1
81526 181525 181524 181523 181522 181521 181520 181519 181518 181517 181516 181515 181514 181513 181512 181511 181510 181509 181508 1815
07 181506 181505 181504 181503 181502 181501 181500 181499 181498 181497 181496 181495 181494 181493 181492 181491 181490 181489 181488 
181487 181486 181485 181484 181483 181482 181481 181480 181479 181478 181477 181475 181476 181473 181474 181472 181471 181470 181469 181
468 181467 181466 181465 181464 181463 181462 181461 181460 181459 181458 181457 181456 181455 181454 181453 181452 181451 181450 181449
 181448 181447 181446 181445 181444 181443 181442 181441 181440 181439 181438 181437 181436 181435 181434 181433 181432 181431 181430 18
1429 181428 181427 181426 181425 181424 181423 181422 181421 181420 181419 181418 181417 181416 181415 181414 181413 181412 181411 18141
0 181409 181408 181407 181406 181405 181404 181403 181402 181401 181400 181399 181398 181397 181396 181395 181394 181393 181392 181391 1
81390 181389 181388 181387 181386 181385 181384 181383 181382 181381 181380 181379 181378 181377 181376 181375 181374 181373 181371 1813
72 181370 181369 181368 181367 181366 181365 181364 181363 181362 181361 181360 181359 181358 181357 181356 181355 181354 181353 181352 
181351 181350 181349 181348 181347 181346 181345 181344 181343 181342 181341 181340 181339 181338 181337 181336 181335 181334 181333 181
332 181331 181330 181329 181328 181327 181326 181325 181324 181323 181322 181321 181320 181319 181318 181317 181316 181315 181314 181313
 181312 181311 181310 181309 181308 181307 181306 181305 181304 181303 181302 181301 181300 181299 181298 181297 181296 181295 181294 18
1293 181292 181291 181290 181289 181288 181287 181286 181285 181284 181283 181282 181281 181280 181279 181278 181277 181276 181275 18127
4 181273 181272 181271 181270 181269 181268 181267 181266 181265 181264 181263 181262 181261 181260 181259 181258 181257 181256 181255 1
81254 181253 181252 181251 181250 181249 181248 181247 181246 181245 181244 181243 181242 181241 181240 181239 181238 181237 181236 1812
35 181234 181233 181232 181231 181230 181229 181228 181227 181226 181225 181224 181223 181222 181221 181220 181219 181218 181217 181216 
181215 181214 181213 181212 181211 181210 181209 181208 181207 181206 181205 181204 181203 181202 181201 181200 181199 181198 181197 181
196 181195 181194 181193 181192 181191 181190 181189 181188 181187 181186 181185 181184 181183 181182 181181 181180 181179 181178 181177
 181176 181175 181174 181172 181173 181171 181170 181169 181168 181167 181166 181165 181164 181163 181162 181161 181160 181159 181158 18
1157 181156 181155 181154 181153 181152 181151 181150 181149 181148 181147 181146 181145 181144 181143 181142 181141 181140 181139 18113
8 181137 181136 181135 181134 181133 181132 181131 181130 181129 181128 181127 181126 181125 181124 181123 181122 181121 181120 181119 1
81118 181117 181116 181115 181114 181113 181112 181111 181110 181109 181108 181107 181106 181105 181104 181103 181102 181101 181100 1810
99 181098 181097 181096 181095 181094 181093 181092 181091 181090 181089 181088 181087 181086 181085 181084 181083 181082 181081 181080 
181079 181078 181077 181076 181075 181074 181073 181072 181071 181070 181069 181068 181067 181066 181065 181064 181063 181062 181061 181
060 181059 181058 181057 181056 181055 181054 181053 181052 181051 181050 181049 181048 181047 181046 181045 181044 181043 181042 181041
 181040 181039 181038 181037 181036 181035 181034 181033 181032 181031 181030 181029 181028 181027 181026 181025 181024 181023 181022 18
1021 181020 181019 181018 181017 181016 181015 181014 181013 181012 181011 181010 181009 181008 181007 181006 181005 181004 181003 18100
2 181001 181000 180999 180998 180997 180996 180995 180994 180993 180992 180991 180990 180989 180988 180987 180986 180985 180984 180982 1
80983 180981 180980 180979 180978 180977 180976 180975 180974 180973 180972 180971 180970 180969 180968 180967 180966 180965 180964 1809
63 180962 180961 180960 180959 180958 180957 180956 180955 180954 180953 180952 180951 180950 180949 180948 180947 180946 180945 180944 
180943 180942 180941 180940 180939 180938 180937 180936 180935 180934 180933 180932 180931 180930 180929 180928 180927 180926 180925 180
924 180923 180922 180921 180920 180919 180918 180917 180916 180915 180914 180913 180912 180911 180910 180909 180908 180907 180906 180905
 180904 180903 180902 18...
--- FlushLogCache: Trigger
[20:19:25.576][73ee40be] INFO[ERROR]: PartialParseOver: 100000
[20:19:26.346][73ee40be] INFO[ERROR]: PartialParseOverResult: 351458
[20:19:26.347][73ee40be] IMAP[DATA]: < TAG5 OK Sort completed (1.593 secs).\r\n
[20:19:26.515][73ee40be] INFO[DATA]: Save Serialized UIDS to cache ("INBOX" / UNDELETED) [count:175727]
[20:19:26.536][73ee40be] IMAP[DATA]: > TAG6 UID SEARCH TEXT "ericsson.com.br" UNDELETED\r\n
[20:19:36.506][73ee40be] IMAP[DATA]: < * OK Searched 3% of the mailbox, ETA 4:41\r\n
[20:19:46.082][73ee40be] IMAP[DATA]: < * OK Searched 6% of the mailbox, ETA 4:55\r\n
[20:19:56.250][73ee40be] IMAP[DATA]: < * OK Searched 9% of the mailbox, ETA 4:31\r\n
... <many lines deleted here to avoid unnecessary space> .... 
[20:29:30.239][73ee40be] IMAP[DATA]: < * OK Searched 97% of the mailbox, ETA 0:15\r\n
[20:29:40.183][73ee40be] IMAP[DATA]: < * OK Searched 98% of the mailbox, ETA 0:10\r\n
[20:29:50.671][73ee40be] IMAP[DATA]: < * OK Searched 99% of the mailbox, ETA 0:06\r\n
[20:30:00.150][73ee40be] IMAP[DATA]: < * OK Searched 99% of the mailbox, ETA 0:00\r\n
[20:30:00.888][73ee40be] IMAP[DATA]: < * SEARCH\r\n
[20:30:00.976][73ee40be] IMAP[DATA]: < TAG6 OK Search completed (634.349 secs).\r\n
[20:30:01.040][73ee40be] INFO[DATA]: Save Serialized UIDS to cache ("INBOX" / TEXT "ericsson.com.br" UNDELETED) [count:0]
[20:30:01.063][73ee40be] AJAX[DATA]: {"Action":"MessageList","Result":{"@Object":"Collection\/MessageCollection","@Count":0,"@Collection":[],"MessageCount":175727,"MessageUnseenCount":175530,"MessageResultCount":0,"Folder":"INBOX","FolderHash":"58dd492a6399409d6bf4d417859652e1","UidNext":"181615","ThreadUid":"","NewMessages":[],"Filter...
[20:30:01.063][73ee40be] IMAP[DATA]: > TAG7 LOGOUT\r\n
[20:30:01.067][73ee40be] IMAP[DATA]: < * BYE Logging out\r\n
[20:30:01.067][73ee40be] IMAP[DATA]: < TAG7 OK Logout completed.\r\n
[20:30:01.068][73ee40be] IMAP[NOTE]: Disconnected from "ssl://imap.dca.fee.unicamp.br:993" (success)
[20:30:01.068][73ee40be] INFO[MEMORY]: Memory peak usage: 85.25MB
[20:30:01.068][73ee40be] INFO[TIME]: Time delta: 637.86634707451

**Comment by RainLoop** [comment]
Yes, system (on client side) got timeout and display error.

Search command (IMAP) has taken more than 10 minutes. It is not good.
```
[20:30:00.976][73ee40be] IMAP[DATA]: < TAG6 OK Search completed (634.349 secs).\r\n
```

We have 2 possible ways to fix your issue.
1) Increase search speed of imap server (IMHO it is a right way)
2) Increase client (RainLoop) timeout, but it does not matter, because you should wait 10 mins to display message list, that is not usable at all.

**Comment by rgudwin** [comment]
It is interesting ... after that I tried to manually refresh, and then an error appeared. Do you think we can limit the range of the search, to avoid the system trying to search the whole mailbox ? For example, the last 1000 messages ? Or a configurable limit ? 
There follows the log for the error .... 

[21:06:14.443][6247babd] IMAP[ERROR]: exception 'MailSo\Net\Exceptions\SocketReadException' with message 'MailSo-Net-Exceptions-SocketRe
adException (NetClient.php ~ 515)' in /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Net/NetClient.php:515
Stack trace:
#0 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Imap/ImapClient.php(2003): MailSo\Net\NetClient->getNextBuffer()
#1 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Imap/ImapClient.php(1869): MailSo\Imap\ImapClient->partialParseResponseBra
nch(Object(MailSo\Imap\Response))
#2 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Imap/ImapClient.php(1921): MailSo\Imap\ImapClient->parseResponse(NULL, fal
se)
#3 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Imap/ImapClient.php(1130): MailSo\Imap\ImapClient->parseResponseWithValida
tion()
#4 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Mail/MailClient.php(1853): MailSo\Imap\ImapClient->MessageSimpleSort(Array
, 'UNDELETED', true)
#5 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Mail/MailClient.php(1973): MailSo\Mail\MailClient->GetUids(Object(MailSo\C
ache\CacheClient), '', '', 'INBOX', 'ab5d18b763fdcf5...', true)
#6 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Actions.php(5786): MailSo\Mail\MailClient->MessageList('INBOX', 0, 100, 
'', '181619', Object(MailSo\Cache\CacheClient), true, false, '', '')
#7 [internal function]: RainLoop\Actions->DoMessageList()
#8 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/ServiceActions.php(164): call_user_func(Array)
#9 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#10 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Service.php(143): call_user_func(Array)
#11 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#12 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#13 /var/www/webmail/rainloop/v/1.9.4.387/app/handle.php(88): RainLoop\Service::Handle()
#14 /var/www/webmail/rainloop/v/1.9.4.387/include.php(228): include('/var/www/webmai...')
#15 /var/www/webmail/index.php(12): include('/var/www/webmai...')
#16 {main}
[21:06:14.467][6247babd] AJAX[DATA]: {"Action":"MessageList","Result":false,"ErrorCode":201,"ErrorMessage":"","ErrorMessageAdditional":"","Time":784}
[21:06:14.467][6247babd] IMAP[ERROR]: exception 'MailSo\Net\Exceptions\SocketUnreadBufferException' with message 'MailSo-Net-Exceptions-SocketUnreadBufferException (NetClient.php ~ 426)' in /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Net/NetClient.php:426
Stack trace:
#0 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Imap/ImapClient.php(1760): MailSo\Net\NetClient->sendRaw('TAG6 LOGOUT', true, '')
#1 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Imap/ImapClient.php(1800): MailSo\Imap\ImapClient->SendRequest('LOGOUT', Array)
#2 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Imap/ImapClient.php(368): MailSo\Imap\ImapClient->SendRequestWithCheck('LOGOUT', Array)
#3 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Mail/MailClient.php(118): MailSo\Imap\ImapClient->Logout()
#4 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/MailSo/Mail/MailClient.php(140): MailSo\Mail\MailClient->Logout()
#5 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Actions.php(382): MailSo\Mail\MailClient->LogoutAndDisconnect()
#6 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Service.php(219): RainLoop\Actions->BootEnd()
#7 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Service.php(56): RainLoop\Service->localHandle()
#8 /var/www/webmail/rainloop/v/1.9.4.387/app/libraries/RainLoop/Service.php(79): RainLoop\Service->__construct()
#9 /var/www/webmail/rainloop/v/1.9.4.387/app/handle.php(88): RainLoop\Service::Handle()
#10 /var/www/webmail/rainloop/v/1.9.4.387/include.php(228): include('/var/www/webmai...')
#11 /var/www/webmail/index.php(12): include('/var/www/webmai...')
#12 {main}
[21:06:14.467][6247babd] INFO[MEMORY]: Memory peak usage: 27.25MB
[21:06:14.467][6247babd] INFO[TIME]: Time delta: 0.78506398200989
[21:06:14.468][6247babd] IMAP[NOTE]: Disconnected from "ssl://imap.dca.fee.unicamp.br:993" (success)

**Comment by RainLoop** [comment]
Could you send me a log above this line?
`[21:06:14.443][6247babd] IMAP[ERROR]: exception 'MailSo\Net\Exceptions\SocketReadException'`

**Comment by rgudwin** [comment]
There follows the log ... do you want me to post at the web site too ?

[21:06:13.686][6247babd] INFO[DATA]:
[DATE:07.01.16][RL:1.9.4.387][PHP:5.5.9-1ubuntu4.9][IP:143.106.50.173][PID:19034][Apache/2.4.7
(Ubuntu)][apache2handler]
[21:06:13.686][6247babd] INFO[DATA]:
[Suhosin:off][APC:off][MB:on][PDO:mysql][Streams:tcp,udp,unix,udg,ssl,sslv3,tls]
[21:06:13.686][6247babd] REQUEST[NOTE]: [POST]
http://leme.dca.fee.unicamp.br/webmail/?/Ajax/&q[]=/_Pa6ePEOok-cICDwH6X_sMpgGvrIozWJeZVqcam4tbEEH3oZ_aZixnEuNhooIC-TcFcSjxFSm0MliAIi5v9zmB8cTAY2bjH4JV80DOJSKvKrmK9Sm9R8WMiWlwSG6mhisCOw9MtEgeGVAqzXRjogUZ3TUjuh-QhTi2xOYgKy5gPq-wmL_NqFct32kQwmFBUcpU3lgaJoqX5vbZ-xdSCJQXhf4v9Es-MAuW20WDgfyd5wb9b_pjxX_R1x5Y641YY0gnUrsUWaP4WWvYoh1lQtWY4eiul6lYXmWaLo4q7ZK5xXRgmVGhJpIgKTmoChtay99qWCPzZeDcvYB0qn8BrxL7_IbkQAvzg1F/
[21:06:13.686][6247babd] AJAX[NOTE]: Action: DoMessageList
[21:06:13.686][6247babd] POST[DATA]:
{"Folder":"INBOX","Offset":"0","Limit":"100","Search":"","UidNext":"181619","UseThreads":"0","ThreadUid":"","Action":"MessageList","XToken":"f7466d332d12c1edb2fdf05405bafa21"}
[21:06:13.689][6247babd] IMAP[NOTE]: Start connection to "ssl://
imap.dca.fee.unicamp.br:993"
[21:06:13.707][6247babd] IMAP[NOTE]: Connected (success)
[21:06:13.743][6247babd] IMAP[DATA]: < * OK [CAPABILITY IMAP4rev1 LITERAL+
SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN] Dovecot ready.

[21:06:13.744][6247babd] IMAP[SECURE]: > TAG1 LOGIN "gudwin" "********"

[21:06:13.762][6247babd] IMAP[DATA]: < TAG1 OK [CAPABILITY IMAP4rev1
LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY
THREAD=REFERENCES THREAD=REFS MULTIAPPEND UNSELECT CHILDREN NAMESPACE
UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES
WITHIN CONTEXT=SEARCH LIST-STATUS] Logged in

[21:06:13.764][6247babd] IMAP[DATA]: > TAG2 SELECT "INBOX"

[21:06:13.773][6247babd] IMAP[DATA]: < * FLAGS (\Answered \Flagged \Deleted
\Seen \Draft NonJunk $Forwarded $NotJunk $Junk)

[21:06:13.773][6247babd] IMAP[DATA]: < * OK [PERMANENTFLAGS (\Answered
\Flagged \Deleted \Seen \Draft NonJunk $Forwarded $NotJunk $Junk \*)] Flags
permitted.

[21:06:13.773][6247babd] IMAP[DATA]: < * 175731 EXISTS

[21:06:13.774][6247babd] IMAP[DATA]: < * 0 RECENT

[21:06:13.774][6247babd] IMAP[DATA]: < * OK [UNSEEN 19] First unseen.

[21:06:13.774][6247babd] IMAP[DATA]: < * OK [UIDVALIDITY 1355780416] UIDs
valid

[21:06:13.774][6247babd] IMAP[DATA]: < * OK [UIDNEXT 181619] Predicted next
UID

[21:06:13.774][6247babd] IMAP[DATA]: < * OK [HIGHESTMODSEQ 6563] Highest

[21:06:13.774][6247babd] IMAP[DATA]: < TAG2 OK [READ-WRITE] Select
completed.

[21:06:13.775][6247babd] IMAP[DATA]: > TAG3 CAPABILITY

[21:06:13.775][6247babd] IMAP[DATA]: < * CAPABILITY IMAP4rev1 LITERAL+
SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES
THREAD=REFS MULTIAPPEND UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED
I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH
LIST-STATUS

[21:06:13.775][6247babd] IMAP[DATA]: < TAG3 OK Capability completed.

[21:06:13.776][6247babd] IMAP[DATA]: > TAG4 STATUS "INBOX" (MESSAGES UNSEEN
UIDNEXT HIGHESTMODSEQ)

[21:06:13.776][6247babd] IMAP[DATA]: < * OK [HIGHESTMODSEQ 6563] Highest

[21:06:13.777][6247babd] IMAP[DATA]: < * STATUS "INBOX" (MESSAGES 175731
UIDNEXT 181619 UNSEEN 175534 HIGHESTMODSEQ 6563)

[21:06:13.777][6247babd] IMAP[DATA]: < TAG4 OK [CLIENTBUG] Status on
selected mailbox completed.

[21:06:13.937][6247babd] IMAP[DATA]: > TAG5 UID SORT (REVERSE ARRIVAL)
US-ASCII UNDELETED

--- FlushLogCache: Trigger
[21:06:14.442][6247babd] IMAP[ERROR]: Stream Meta: Array
(
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] =>
    [timed_out] =>
    [blocked] => 1
    [eof] => 1
)

**Comment by kt1024** [comment]
when my email count reach 25xxx (don't know the exact number when causing issues), 8GB+ , after login, "can't get message list". 
tried delete some email , then rainloop can connect again. (maybe email count is 252xx, not sure). after minutes became "can't ... " again.

now using other webmail clients, works, incl compose/searching/read, searching speed is ok. ( but the ui/ux is not good as rainloop)
so the email server performance is not a problem.

**Comment by alphamichael** [comment]
Could it be Dovecot's `vsz_limit` is too low? See https://github.com/RainLoop/rainloop-webmail/issues/1737#issuecomment-595818780
