### ISSUE TITLE
can not use imap with SSL

### ISSUE THREAD

**Issue by atmouse-** [RainLoop/rainloop-webmail#98]
i had setup nginx and php.
after install and login into admin panel on setting 'gmail' domain.
i got test fail on imap or smtp. 

turn log's switch On in application.ini, then i found _data_63ba5802d3bac4d3fdbd410b245d4ee9/_default_/logs/log-2014-02-24.txt shows SSL isn't supported

```
[06:39:15.012] REQUEST[NOTE]: POST: 192.168.55.3/webmail/index.php?/Ajax/0/
[06:39:15.013] INFO[DATA]: [PHP:5.5.9][RL:1.6.3.712][DATE:24.02.14]
[06:39:15.017] AJAX[NOTE]: Action: DoAdminDomainTest
[06:39:15.018] POST[DATA]: {"IncHost":"imap.gmail.com","IncPort":"993","IncSecure":"1","OutHost":"smtp.gmail.com","OutPort":"465","OutSecure":"1","OutAuth":"1","Action":"AdminDomainTest","XToken":""}
[06:39:15.027] IMAP[ERROR]: exception 'MailSo\Net\Exceptions\SocketUnsuppoterdSecureConnectionException' with message 'SSL isn't supported' in /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/MailSo/Net/NetClient.php:192
Stack trace:
#0 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/MailSo/Imap/ImapClient.php(141): MailSo\Net\NetClient->Connect('imap.gmail.com', 993, 1)
#1 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/RainLoop/Actions.php(2327): MailSo\Imap\ImapClient->Connect('imap.gmail.com', 993, 1)
#2 [internal function]: RainLoop\Actions->DoAdminDomainTest()
#3 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/RainLoop/ServiceActions.php(157): call_user_func(Array)
#4 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#5 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/RainLoop/Service.php(164): call_user_func(Array)
#6 /srv/http/webmail/rainloop/v/1.6.3.712/app/handle.php(41): RainLoop\Service->Handle()
#7 /srv/http/webmail/rainloop/v/1.6.3.712/index.php(148): include('/srv/http/webma...')
#8 /srv/http/webmail/index.php(21): include('/srv/http/webma...')
#9 {main}
[06:39:15.028] SMTP[ERROR]: exception 'MailSo\Net\Exceptions\SocketUnsuppoterdSecureConnectionException' with message 'SSL isn't supported' in /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/MailSo/Net/NetClient.php:192
Stack trace:
#0 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/MailSo/Smtp/SmtpClient.php(156): MailSo\Net\NetClient->Connect('smtp.gmail.com', 465, 1)
#1 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/RainLoop/Actions.php(2343): MailSo\Smtp\SmtpClient->Connect('smtp.gmail.com', 465, '127.0.0.1', 1)
#2 [internal function]: RainLoop\Actions->DoAdminDomainTest()
#3 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/RainLoop/ServiceActions.php(157): call_user_func(Array)
#4 [internal function]: RainLoop\ServiceActions->ServiceAjax()
#5 /srv/http/webmail/rainloop/v/1.6.3.712/app/libraries/RainLoop/Service.php(164): call_user_func(Array)
#6 /srv/http/webmail/rainloop/v/1.6.3.712/app/handle.php(41): RainLoop\Service->Handle()
#7 /srv/http/webmail/rainloop/v/1.6.3.712/index.php(148): include('/srv/http/webma...')
#8 /srv/http/webmail/index.php(21): include('/srv/http/webma...')
#9 {main}
[06:39:15.029] AJAX[DATA]: {"Action":"AdminDomainTest","Result":{"Imap":false,"Smtp":false},"Time":30}
[06:39:15.029] INFO[MEMORY]: Memory peak usage: 3.5MB
```

**Comment by rbongers** [comment]
I use HHVM and i've got also this issue. Does it work with HHVM?
